deploy/roles/role.yaml
The operator was failing with rbac errors for getting/creating serviceaccounts & routes.
=> Add missing rbac rules for routes & serviceaccounts

Makefile, cmd/manager/main.go, pkg/controller/grafana/controller_config.go, pkg/controller/grafana/templateHelper.go
Make the Grafana Image and Tag configurable using command line args.
Verification:
1. Create an empty namespace using grafana
1. Run the operator locally using `operator-sdk up local --namespace=grafana --operator-flags "--grafana-image registry.redhat.io/openshift3/grafana --grafana-image-tag v3.11"`
1. Deploy a grafana instance to this namespace using `oc create -f deploy/examples/Grafana.yaml`
1. Wait until everything is deployed.
1. Inspect the Grafana deployment and make sure it is using the specified Red Hat image.
1. Delete the Grafana CR and restart the operator without the extra flags
1. Deploy another Grafana instance
1. Make sure that this time it is using the public community Grafana image.
=> Configurable image

pkg/apis/integreatly/v1alpha1/grafana_types.go, pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go, pkg/controller/grafana/grafana_controller.go, pkg/controller/grafana/resourceHelper.go, pkg/controller/grafana/resourceHelper_test.go, pkg/controller/grafana/testing_shared.go
Allow extra containers (like auth proxies) to be specified in the Grafana CR and add them to the deployment.
1. Create a new empty namespace
1. Run the Operator from this branch against that namespace
1. Deploy Grafana using the following CR:
```yaml
kind: Grafana
metadata:
name: example-grafana
spec:
containers:
- image: busybox
command:
- sleep
- "3600"
imagePullPolicy: IfNotPresent
name: busybox
prometheusUrl: "http://prometheus-application-monitoring:9090"
dashboardNamespaceSelector:
matchLabels:
monitoring-key: middleware
```
Make sure that everything deploys fine and there is an extra `busybox` container in the Grafana deployment.
ping @laurafitzgerald
=> allow extra containers in cr

README.md, cmd/manager/main.go, pkg/controller/common/controller_config.go, pkg/controller/grafana/templateHelper.go, templates/grafana-deployment.yaml
Allows to configure the plugin init container tag in addition to https://github.com/integr8ly/grafana-operator/pull/15
ping @neoludo
=> plugin init container tag configurable per flag

pkg/apis/integreatly/v1alpha1/grafanadatasource_types.go, pkg/controller/grafanadatasource/datasource_controller.go, version/version.go
Check a data source for changes before updating and restarting Grafana. This needs to be done because on OpenShift it looks like a resource sometimes is reconciled even when there are no changes.
With this PR we store the md5 hash of the last configuration of the data source in it's status and check updates against that.
=> Compare resources

pkg/controller/common/controller_config.go, pkg/controller/grafanadashboard/dashboard_controller.go
When a dashboard is deleted, it's plugins should be removed too unless they are also required by another dashboard.
1. Run the operator and prepare two dashboards (you can use the one under `examples/dashboards`):
1. One dashboard that requires plugin A and B and the other that only requires A
1. Create the dashboards, make sure the operator installs both plugins
1. Remove the dashboard that only requires A
1. After the grafana restart, make sure that plugin B (and only plugin B) has been removed.
=> delete plugins when dashboard is deleted

deploy/cluster_roles/cluster_role.yaml, deploy/roles/role.yaml, documentation/deploy_grafana.md, templates/grafana-route.yaml
* Update the roles for the operator on OpenShift (finalizer permissions were missing) 
* Ignore the `hostname` property when using routes instead of ingress: setting the hostname is not permitted, but OpenShift will automatically assign a value.
* Document the behavior of the `hostname` property in ingresses and routes.
An image with the changes has been pushed to `quay.io/integreatly/grafana-operator:latest`
1. Try this on a fresh cluster
1. Create the crds: `oc create -f deploy/crds`
1. Create the roles: `oc create -f deploy/roles`
1. Deploy the operator:
4.1. If on OpenShift, modify `operator.yaml` to include the `--openshift` flag
4.2. On Kubernetes no modification is required
1. Make sure the operator is running and no errors are in its log
1. Deploy Grafana: `oc …
=> Intly 2704

pkg/controller/common/kubeHelper.go, pkg/controller/grafanadatasource/datasource_controller.go
After a controller restart, a datasource was not reimported, even if gone from the configmap. The new policy is:
1. Check if a datasource is already in the configmap
1. If no, always import it
1. If yes, check for changes and only import if updated
1. Deploy Grafana, create a data source and make sure it's imported
1. Uninstall Grafana by removing the CR, make sure the data source CR is still present
1. Restart the operator and reinstalll Grafana
1. Make sure the old datasource gets reimported
=> always import new data sources

README.md, deploy/operator.yaml, documentation/deploy_grafana.md, pkg/controller/common/controller_config.go
Downstream issue: https://issues.jboss.org/browse/INTLY-2724
Verification:
* Create a new project `oc new-project grafana`
* Install the operator from a build of this branch (`quay.io/integreatly/grafana-operator:update-grafana-version`), or alternatively run the operator locally against a remote cluster using `make code/run`
* Create a Grafana CR from the template `oc create -f ./deploy/examples/Grafana.yaml`. You may need to modify the host field before creating this, or alternatively create another route via the openshift UI after to the Grafana service.
* Go to the Grafana console & verify the version (bottom left ? symbol) is 6.2.4.
=> Update default grafana image to version used in openshift 4.2 (6.2.4)

Gopkg.lock, pkg/apis/integreatly/v1alpha1/grafanadashboard_types.go, pkg/controller/common/kubeHelper.go, pkg/controller/grafana/grafana_controller.go, pkg/controller/grafana/pluginsHelper.go, pkg/controller/grafanadashboard/dashboard_controller.go
Check cr for valid JSON before importing dashboard.
1. Install the operator from this branch
1. Create a dashboard with invalid json and try to import it
1. The operator should log a meaningful error and the dashboard should not get imported
1. Check the dashboard CR: a status message with the json error should have been appended
1. fix the json and make sure the dashboard is imported now
=> INTLY-2712 check cr for valid json

cmd/manager/main.go, pkg/apis/integreatly/v1alpha1/grafanadashboard_types.go, pkg/apis/integreatly/v1alpha1/grafanadatasource_types.go, pkg/apis/integreatly/v1alpha1/selectors.go, pkg/controller/common/controller_config.go, pkg/controller/common/kubeHelper.go, pkg/controller/common/resource_states.go, pkg/controller/grafana/grafana_controller.go, pkg/controller/grafanadashboard/dashboard_controller.go, pkg/controller/grafanadatasource/datasource_controller.go
When Grafana is uninstalled and then reinstalled (by deleting and recreating the CR) without restarting the operator, dashboards that were imported previously will no longer be discovered. This is because the dashboards are already marked as imported and as long as they are not updated the Operator will not attempt to re import them.
There are two ways to fix this:
1) Introduce the concept of 'orphaned' dashboards: When Grafana is uninstalled, the operator would list all dashboards and set them to status `orphaned`. In this status, the dashboard controller continually reschedules them. It will do this as long as there are dashboards and no Grafana installation. When Grafana is reinstalled, it would move the dashboard back into a `ready for import` status and stop the periodic scheduling. …
=> reimport dashboards after operator restart if not already imported

cmd/manager/main.go, documentation/deploy_grafana.md, pkg/controller/common/controller_config.go, pkg/controller/common/kubeHelper.go, pkg/controller/grafana/templateHelper.go, templates/grafana-deployment.yaml, templates/grafana-ingress.yaml, templates/grafana-service.yaml
Allow users to customize the value of the label that is assigend to the grafana pod. This can be useful in scenarios where another unmanaged grafana instance is running in the same namespace.
I prefer to use an operator flag instead of a CR property to make it clearer that this is not to support multiple managed grafana instances.
Implements #37 
1. Deploy the operator using the ` customize-pod-label ` tag
2. Provide an extra operator flag `--pod-label-value=grafana2`
3. Install grafana
4. Make sure everything still works as expected (access UI, import dashboar and data source).
5. Make sure the pod is labelled `grafana2`
@jjaferson mind taking a look?
=> Customize pod label

pkg/controller/grafana/grafana_controller.go, version/version.go
JIRA: https://issues.jboss.org/browse/INTLY-3843
Related PRs:
- https://github.com/integr8ly/manifests/pull/75
- https://github.com/integr8ly/application-monitoring-operator/pull/87
- https://github.com/integr8ly/application-monitoring-operator/pull/88
- https://github.com/integr8ly/integreatly-operator/pull/142
- https://github.com/integr8ly/installation/pull/1075/files
Periodically reconcile the service accounts for Grafana Prometheus and AlertManager to make sure the annotations are in place.
Bumping integreatly operator version 1.9.5
Bumping application monitoring operator version 0.0.28
Bumping grafana operator version 1.3.2
=> Periodically reconcile oauth annotations onto the grafana service account

deploy/cluster_roles/cluster_role.yaml, deploy/roles/role.yaml, pkg/controller/common/clusterActions.go, pkg/controller/common/readiness_checks.go, pkg/controller/grafana/grafana_controller.go, pkg/controller/grafana/grafana_reconciler.go, pkg/controller/grafanadashboard/dashboard_controller.go, pkg/controller/grafanadashboard/grafana_client.go
updates to ensure the operator works on vanilla kubernetes. Grafana api client must be able to connect to Grafana with or without an Ingress.
=> Kube support

pkg/controller/model/grafanaDeployment.go
Use correct prefix for volumes created from configmaps.
Fixes #88 
* Use the ldap example: https://github.com/integr8ly/grafana-operator/tree/master/deploy/examples/ldap
* Create the configmap
* Deploy Grafana using Grafana.yaml
Deployment should get created and the container should have a file ldap.toml mounted under `/etc/grafana-configmaps/ldap-config/ldap.toml`.
=> fix configmap prefix

deploy/examples/ha/README.md, deploy/examples/ha/grafana.yaml, deploy/examples/ha/postgres.yaml, documentation/README.md, pkg/controller/config/grafanaIni.go
Adds a high availability example where Postgres is used as a backing database for Grafana.
Provides a solution for: #63 
* follow the steps described in https://github.com/integr8ly/grafana-operator/compare/master...pb82:grafana-ha?expand=1#diff-97febf83a0872839b69a71afa6b2e9ca
* Get the login credentials from the secret `grafana-admin-credentials`
* Login using the route, make sure that the session is not lost after multiple browser refreshes.
=> add grafana/postgres ha example

deploy/operator.yaml
The latest release of this operator says it deploys Grafana 6.5.1 but with the current defaults in the operator.yml 6.2.something gets deployed. suggest removing the args in the operatyor.yml so by default the default image set in the operator gets picked up
=> operator.yaml - update so it deploys the latest grafana image as set by the operator by default

deploy/examples/GrafanaWithIngressHost.yaml, documentation/deploy_grafana.md, pkg/controller/model/grafanaRoute.go
Allow to set the host for routes too (previously only allowed for Ingresses)
fixes #96
=> Route host

deploy/operator.yaml
since only one operator pod can be master at a time with the default deployment strategy for `rolling` the roll never successfully happens because the old pod is staying up till the new pod is healthy but the new pod can never be healthy because its not the leader. for operator best to just set strategy to `recreate`
=> deploy/operator.yaml - update stratigy to be recreate since rolling wont work with an operator where only one pod can be the master

deploy/roles/role.yaml
need this permission to be able to use the `GrafanaWithIngressHost.yaml` on OpenShift.
=> roles/role.yaml - add 'routes/custom-host' so that custom host can be set

pkg/controller/model/grafanaDeployment.go, pkg/controller/model/grafanaIngress.go, pkg/controller/model/grafanaRoute.go, pkg/controller/model/grafanaService.go, pkg/controller/model/grafanaServiceAccount.go, pkg/controller/model/utils.go
fixes #127 
Merge annotations with previously existing ones instead of overwriting them. This prevents an infinite loop of reconciliations where OpenShift adds an annotation to be removed by the Operator to be added by OpenShift...
One problem with this is that removing annotations by removing them from the CR doesn't work anymore: you have to remove them from the CR *and* the resource now.
=> merge annotations

deploy/ansible/README.md, deploy/ansible/localhost.ini, deploy/ansible/openshift-monitoring-update-prometheus-authentication.yaml
This isn't strictly Grafana specific but is "needed" to be able to attach Grafana to Prometheus running in OpenShift. If you don't think it belongs here I will put it in https://github.com/redhat-cop/openshift-toolkit.
If you think it belongs here I will also update the documentation but if decide not to put this here may still put in a PR here to link over to where it ends up since it will be a common enough use case I presume that it would be helpful for people.
=> openshift-monitoring-update-prometheus-authentication.yaml - init add

pkg/controller/grafana/grafana_controller.go, pkg/controller/grafanadashboard/dashboard_pipeline.go
fix for #136 and #137 
fixes a case where one dashboard could overwrite another if Grafana was restarted (due to plugins) and upon reimport old dashboard IDs (from the status block) were reused.
=> Improvements to 3 0 2

deploy/examples/dashboards/DashboardFromConfigMap.yaml, deploy/roles/role.yaml, pkg/apis/integreatly/v1alpha1/grafanadashboard_types.go, pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go, pkg/controller/grafanadashboard/dashboard_controller.go, pkg/controller/grafanadashboard/dashboard_pipeline.go
Adding the option to load json from a ConfigMap would allow loading of dashboard json in a decoupled manner. Other controllers would in theory be able to fetch or generate json without being aware of the grafana-operator. Additionally every method for fetching json would not have to be implemented in this controllers.
=> Add option to load dashboard json from a ConfigMap

deploy/examples/oauth/session-secret.yaml
This file `session-secret.yaml` have an invalid `Secret` format and can not apply to k8s cluster.
```
root@oauth(master)$ k apply -f session-secret.yaml
error: error validating "session-secret.yaml": error validating data: ValidationError(Secret.metadata): unknown field "type" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta; if you choose to ignore these errors, turn validation off with --validate=false
```
=> fix invalid yaml format

pkg/controller/config/controller_config.go
https://issues.redhat.com/browse/INTLY-7215
Using the `--scan-all` flag to watch for dashboards in all namespaces caused a operator to crash due to a data race condition.
- Openshift 4 cluster
- Operator-SDK. If possible, use version `0.16.0`, as versions `0.15.1` and `0.17.0` will not work when running the operator locally
- `oc login` to you OS4 cluster
- Create a large number of namespaces (70 is recommended) and populate each with a number of dashboards
- Create a new Grafana namespace: `oc new-project grafana`
- Add the following matchExpression to the `deploy/examples/Grafana.yaml` file:
```
- matchExpressions:
- {key: app, operator: In, values: [syndesis]}
```
- Deploy Grafana to your cluster: `oc apply -f deploy/examples/Grafana.yaml -n grafana`
- Run the operator, passing in the …
=> Lock added to prevent data race

pkg/controller/grafana/grafana_controller.go
This commit refer the issue #145
Debug a bit, I saw that if the Dashboard updates the variable in this condition, in dashboard_controller the func reconcileDashboards will not falling in the loop to new/update dashboard, causing a not insert dashboards like mentioned in #145.
=> Don't update dashboards

deploy/cluster_roles/README.md, deploy/cluster_roles/cluster_role_grafana_operator.yaml, deploy/crds/Grafana.yaml, documentation/multi_namespace_support.md, pkg/apis/integreatly/v1alpha1/grafana_types.go, pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go, pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go, pkg/controller/common/controllerState.go, pkg/controller/grafana/grafana_controller.go, pkg/controller/grafanadashboard/dashboard_controller.go
[Jira](https://issues.redhat.com/browse/INTLY-7239)
1. Bring up the grafana operator using this branch
2. Modify the grafan cr to include the following 
``` 
dashboardNamespaceSelector:
matchLabels:
monitoring-key: middleware
```
2. Create 2 namespaces one without the namespace label "monitoring-key: middleware" the other with.
3. Inside each Namespace create a dashboard with the same label as above.
4. Check grafana you should see only the dashboard from the namespace with labels
=> Intly 7239 grafana operator should watch rhmi namespaces for crs

deploy/examples/persistentvolume/Grafana.yaml, deploy/examples/persistentvolume/README.md, pkg/apis/integreatly/v1alpha1/grafana_types.go, pkg/apis/integreatly/v1alpha1/helper.go, pkg/controller/common/clusterState.go, pkg/controller/grafana/grafana_reconciler.go, pkg/controller/model/constants.go, pkg/controller/model/grafanaDataPvc.go, pkg/controller/model/grafanaDeployment.go
Now in order to persist the data, we need to deploy a mysql or postgres database, wait for the database to start, and then config the grafana.spec.database field. 
I think if the operator can provide the ability to customize the persistent storage, it will be greatly simplified.
This PR refer the issue #147.
=> Support to provide persistent storage for grafana database

cmd/manager/main.go, deploy/operator.yaml
JIRA Link: https://issues.redhat.com/browse/INTLY-8046
There is a dead lock, due to the code ordering. Suggestion was to remove
the readiness probe from the code. This occurs during a rolling update and not in
recreate strategy.
Verfied that the upgrade works for rolling upgrade and recreate.
Verified that there was no deadlock happening during the upgrade.
=> Fix for deadlock during rolling-upgrade

deploy/roles/role.yaml
deploy/roles/role.yaml is missing a "deployments/finalizers" resource in the "app" group. Without it, a service for "grafana-operator-metrics" is not created and an error is written to the logs. This maybe due to an upstream issue in the operator-sdk.
Before:
``` json
{
"level":"error",
"ts":1593431909.364457,
"logger":"cmd",
"msg":"error starting metrics service",
"error":"failed to create or get service for metrics: services \"grafana-operator-metrics\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>",
"stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgrafana-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\tgrafana-operator/cmd/manager/main.go:215\nruntime.main\n\t/home/travis/.gimme/ver …
```
=> Need deployment finalizer for metrics service

deploy/examples/oauth/Grafana.yaml, deploy/examples/oauth/README.md, deploy/examples/oauth/ocp-injected-certs.yml
Due to what happens when you add a custom certificate to OCP you need to add the root ca to the operator.
Explained here: https://docs.openshift.com/container-platform/4.4/networking/configuring-a-custom-pki.html#certificate-injection-using-operators_configuring-a-custom-pki
It also works when you haven't added a custom ca :)
=> Add configmap for OCP oath example

Makefile, documentation/deploy_grafana.md, documentation/minikube.md
Adding some documentation around running and setting up the operator in minikube, easy option for developing the operator without an actual cluster.
This is intended to be a living document, with additions as needed.
=> Add documentation for running the operator on minikube

deploy/examples/datasources/Stackdriver.yaml, pkg/apis/integreatly/v1alpha1/grafanadatasource_types.go
fixes #220 
Adds datasource `jsonData` and `secureJsonData` options to support stackdriver. Also adds an example DS.
=> support stackdriver datasource options

.github/dependabot.yml
Fix for
```
Error parsing reference: "quay.io/integreatly/grafana-operator:dependabot/go_modules/github.com/pkg/errors-0.9.1" is not a valid repository/tag: invalid reference format
```
=> Use hyphen branch separator

pkg/controller/grafanadashboard/dashboard_pipeline.go
Fixes the issue where a change in a jsonnet dashbaord was not reconciled. The hash did not include the jsonnet source code.
=> fix: jsonnet changes in dashboards went undetected

pkg/apis/integreatly/v1alpha1/grafana_types.go, pkg/controller/grafana/grafana_controller.go, pkg/controller/model/grafanaService.go
1. in some cases, we need to deploy headless service, this PR aims to support it.
2. For loadbalancer type service, nodeport is continually overwrote by operator that cause lb service created failed. So do not overwrite nodeport.
=> support grafana headless service and no overwrite nodeport

README.md, documentation/dashboards.md
- Added information about the grafana-operator slack channel
- Removed "panels" from the plugin section of dashboards.md, this caused some confusion previously.
=> Update Readme and Dashboards.md

.gitmodules
- setting the release hash to v0.1.0 for the grafonnet-lib submodule
- adding ignore field for dirty repo states : `Dirty status = the repo in question has tracked files (files that have previously been committed) that have modifications that have not been committed, and/or there are new untracked files. `
=> Set grafonnet release hash to v0.1.0 and add `ignore=dirty` to submodule

documentation/README.md, documentation/env_vars.md, go.mod, go.sum, pkg/controller/common/clusterActions.go, pkg/controller/common/controllerState.go, pkg/controller/grafana/grafana_controller.go, pkg/controller/grafana/grafana_reconciler.go, pkg/controller/grafanadashboard/dashboard_controller.go, pkg/controller/model/adminUserSecret.go
Solves the problem where the operator needs to know the admin credentials even if they are provided from a user provided secret or config map.
The operator needs an admin account to communicate with Grafana. The following behaviour applies:
1. If not told otherwise, the operator creates an admin secret and exposes the credentials as env vars to the running (operator) container.
2. The username and password are either taken from `spec.security` or are created randomly.
3. This also applies if `spec.deployment.envFrom` is used to mount external secretes or config maps as env vars.
4. If the user wishes to provide admin credentials from one of those external resources, they *must* set `spec.deployment.skipCreatingAdminAccount` to stop the operator from overriding it.
5. In that case, the …
=> Admin creds from env

pkg/controller/grafanadashboard/dashboard_controller.go, pkg/controller/grafanadashboard/dashboard_pipeline.go
If dashboard has only URL set in `GrafanaDashboard` spec, the operator should fetch it once and avoid refetching it on every reconciliation. Fetched contents would be written in `.spec.json`.
Dashboard provider may start throwing "429 Too Many Requests" after some time (i.e. grafana.com),
so dashboard can no longer be fetched.
URL may change contents, so users should remove `.spec.json` in order to refetch dashboard contents.
Related to #45 (not entirely sure if it fixes it)
=> pkg/controller/grafanadashboard: avoid refetching URL

deploy/crds/Grafana.yaml, pkg/apis/integreatly/v1alpha1/grafana_types.go, pkg/controller/model/grafanaDeployment.go
Allow setting the pod priority class name. Fixes #287 
1. Deploy Grafana setting the pod priority class name
2. Ensure the class is correctly set on the deployment & pod
3. Ensure that by default the value is empty
=> allow setting the pod priority class name for the Grafana deployment

build/Dockerfile, deploy/examples/dashboards/DashboardFromURL.yaml, documentation/dashboards.md, documentation/deploy_grafana.md
Updating documentation to cover recent changes in:
- URL based dashboards <- now require an empty json field to properly fetch dashboards from urls.
- priorityClassName support <-  allows to set a priority class to the grafana deployment pod.
Changing base image to ubi:8 
- easier compatibility with openshift-ci, as well as to keep this consistent with other repos in this org.
#287 #288 
N/A
=> update docs and change base-image to ubi:8

pkg/apis/integreatly/v1alpha1/grafana_types.go, pkg/controller/config/grafanaIni.go
grafana-operator v3.5.0 lacks support for TLS settings in [generic_oauth](https://grafana.com/docs/grafana/latest/auth/generic-oauth/). That's very unfortunate, because there are plenty of companies using self-signed certificates in combination with OIDC (e.g. Keycloak). Thus, there's the need to either feed Grafana with custom certificates or skip TLS verification at all.
The PR adds support for these fields:
* tls_skip_verify_insecure
* tls_client_cert
* tls_client_key
* tls_client_ca
Note: VS Code adjusted formatting a bit, and the change looked reasonable, so I kept it. I hope that's fine.
#192
```yaml
secrets:
- ca-bundle
config:
auth.generic_oauth:
tls_client_ca: /etc/grafana-secrets/ca-bundle/ca.crt
tls_skip_verify_insecure: false
tls_client_cert: …
```
=> Add support for TLS settings in AuthGenericOauth

deploy/examples/datasources/Azure.yaml, pkg/apis/integreatly/v1alpha1/grafanadatasource_types.go
- Adds new fields for Azure monitoring 
#268 
Would require a running azure instance, which I currently do not have access to, going off Grafana documentation [here](https://grafana.com/docs/grafana/latest/datasources/azuremonitor/) and the fields required by @rbeckerpf
=> Add Azure monitoring fields for grafanadatasources

pkg/controller/grafanadashboard/dashboard_controller.go, pkg/controller/grafanadashboard/grafana_client.go
During every reconciliation run, the operator opens a new Grafana API connection to sync the managed folders. These connections are kept alive indefinitely, eventually exhausting the resources available.
I have a bare metal `kubeadm` cluster, and I've installed `grafana-operator` using the [manual method](https://github.com/integr8ly/grafana-operator/blob/master/documentation/deploy_grafana.md#manual-procedure). Everything seemed to run normally, but after a few days, the operator pod started logging messages like this:
{"level":"error","ts":1603676475.339174,"logger":"controller_grafanadashboard","msg":"failed to get or create namespace folder %v for dashboard %v with error %v","monitoring":"","error":"Get http://admin:***@10.108.29.90:3000/api/folders: dial tcp 10.108.29.90:3000: …
=> close idle HTTP client connections at the end of a reconciliation run

cmd/manager/main.go, documentation/deploy_grafana.md, go.mod, pkg/controller/common/clusterActions.go, pkg/controller/grafana/grafana_controller.go, pkg/controller/grafana/grafana_reconciler.go, pkg/controller/grafana/grafonnet_utils.go, pkg/controller/grafana/pluginsHelper.go, pkg/controller/grafanadashboard/dashboard_controller.go, pkg/controller/grafanadashboard/dashboard_pipeline.go, pkg/controller/grafanadashboard/grafana_client.go, pkg/controller/grafanadatasource/datasource_controller.go
- Adding zapper as the new logger
- introducing log levels 
- no `--zap-level` = only errors and failed reconcile steps
- `-zap-level=1` = Info level logging
- `--zap-level=2` = Debug level logging <- To be added
#214 
1. Run the operator using 
`operator-sdk run local --watch-namespace=grafana --operator-flags='--zap-level=1'`
and confirm that the output is as normal/expected or the same as that from master
2. Run the operator using
`operator-sdk run local --watch-namespace=grafana`
and confirm that only error/failed reconcile info is logged (apart from initial logging for versions etc.)
=> Fix-214- use zapper for logging and set log levels

pkg/controller/common/clusterActions.go, pkg/controller/grafana/grafana_controller.go, pkg/controller/grafana/grafana_reconciler.go, pkg/controller/grafanadashboard/dashboard_controller.go
The "verbs"(like `%s` and `%v`) in some log messages are not replaced correctly because of the lack of `fmt.Sprintf`.
Like this:
```
{"level":"error","ts":1606811391.4938138,"logger":"controller_grafanadashboard","msg":"failed to get or create namespace folder %v for dashboard %v with error %v","monitoring":"","error":"Get http://admin:***@<IP_ADDR>:3000/api/folders: dial tcp <IP_ADDR>:3000: connect: connection refused","stacktrace":"<STACK_TRACE>"}
```
=> Format strings in some log messages are not replaced

pkg/apis/integreatly/v1alpha1/grafanadashboard_types.go
When I changed the `.spec.datasources` field in GrafanaDashboard CR, grafana-operator did not update the dashboard.
The hash method of GrafanaDashboard may wrong. Could you review this?
=> Calculate hash value with datasources

pkg/controller/grafana/grafana_controller.go, pkg/controller/grafanadashboard/dashboard_controller.go, pkg/controller/grafanadashboard/grafana_client.go
Signed-off-by: H.Muraoka <hiroshi-muraoka@cybozu.co.jp>
The conntrack table on which a grafana opeartor v3.6.0 is running is filled with too many(~35k) entries as shown below.
I think this is caused by the dashboard operator, which creates an http client but leaves it unclosed every time it runs a reconciliation loop.
[The golang official document](https://golang.org/pkg/net/http/#Client) indicates that:
> The Client's Transport typically has internal state (cached TCP connections), so Clients should be reused instead of created as needed. Clients are safe for concurrent use by multiple goroutines.
This PR fixes the connection leak by reusing the TCP connection and fixes [the client timeout assignment logic](https://github.com/integr8ly/grafana-operator/blob/14a623c4b4468f5321c2a7500443419 …
=>  Reuse TCP transport to prevent connection leak

pkg/apis/integreatly/v1alpha1/grafanadatasource_types.go
This change adds support for `jsonData` and `secureJsonData` fields in the `GrafanaDatasource` resource that are used by InfluxDB.
`jsonData`-
- `defaultBucket`
- `httpMode`
- `version`
- `organization`
`secureJsonData` -
- `token`
Resolves https://github.com/integr8ly/grafana-operator/issues/322
Deploy a GrafanaDatasource for an InfluxDB instance using any of the new fields. These should be pulled across to Grafana and the datasource should function.
=> Add missing InfluxDB datasource jsonData fields

pkg/controller/grafana/grafana_controller.go
Grafana cr is constantly update causing errors where the resource is out of date. These updates are updating the CR with the same information in the status block and are uneeded. This pr only updates when the status block is different. 
https://issues.redhat.com/browse/MGDAPI-1030
install current 3.7.0 version and verify that the CR is constantly updated. In Openshift, view the CR yaml and click the reload button each time its update and verify the increase in version revision. 
Install from this branch and verify CR is only updated as status changes happen rather than on every reconciliation
=> Mgdapi 1030

build/Dockerfile
This PR is trying to address vulnerabilities with the current image
- use `ubi-minimal` instead of prior `ubi` (half of the things that come with ubi aren't used by us anyway)
- use the latest tagged release: `8.3` 
***openshift-release config will most likely have to be updated as well to ensure CI builds run correctly***
- run `make image/build` 
- the image should build properly
=> change base image to ubi-minimal and use 8.3

pkg/apis/integreatly/v1alpha1/grafana_types.go, pkg/controller/config/grafanaIni.go
This fixes log.console grafana.ini section, thus enabling json logging
fixes https://github.com/integr8ly/grafana-operator/issues/328
Configure as per docs, observe no json logs, apply this patch, observe it works. 
Let me know what you think!
=> Add log console for json

pkg/controller/config/controller_config.go, pkg/controller/config/controller_config_test.go, pkg/controller/grafana/grafana_reconciler.go
The grafana-operator can periodically crash with this error:
```
fatal error: concurrent map iteration and map write
goroutine 1964 [running]:
runtime.throw(0x169597f, 0x26)
/home/travis/.gimme/versions/go1.13.15.linux.amd64/src/runtime/panic.go:774 +0x72 fp=0xc0000217d8 sp=0xc0000217a8 pc=0x42e642
runtime.mapiternext(0xc0000218f0)
/home/travis/.gimme/versions/go1.13.15.linux.amd64/src/runtime/map.go:858 +0x579 fp=0xc000021860 sp=0xc0000217d8 pc=0x40f259
github.com/integr8ly/grafana-operator/v3/pkg/controller/grafana.(*GrafanaReconciler).getGrafanaPluginsDesiredState(0xc000021b68, 0xc000287c00, 0x4, 0x4)
grafana-operator/pkg/controller/grafana/grafana_reconciler.go:300 +0xe9 fp=0xc000021960 sp=0xc000021860 pc=0x12b9e99
github.com/integr8ly/grafana-operator/v3/pkg/controller/grafana.(*Grafa …
```
=> INTLY-10372: Safely read and write plugins concurrently

pkg/apis/integreatly/v1alpha1/grafanadatasource_types.go
Grafana has an option to forward user's upstream OAuth identity to a data source. Basically, it means that a user's jwt token gets passed along in the Authorization header with every request sent to a data source. - It's incredible useful in environments where token claims influence authorization decisions (like whether a user should have access to certain metrics or endpoints).
The option is called "Forward OAuth Identity" ([oauthPassThru](https://github.com/grafana/grafana/blob/1d689888b0fc2de2dbed6e606eee19561a3ef006/packages/grafana-ui/src/components/DataSourceSettings/HttpProxySettings.tsx#L38)):
The proposed change adds support for that.
I've added an example below, you might want to include it in the documentation. Though, I'm not sure if we should document every possible option :) …
=> Added support for Datasource OauthPassThru (Forward OAuth Identity)

deploy/cluster_roles/cluster_role_grafana_operator.yaml
Added missing permission to create events in case operator is being set up to manage dashboards in multiple namespaces.
Without these permissions the following error happens:
`User "system:serviceaccount:epic-system:grafana-operator" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)`
=> Add permissions to create events

deploy/examples/dashboards/DashboardFromConfigMap.yaml, deploy/examples/dashboards/DashboardFromURL.yaml, deploy/examples/dashboards/DashboardWithCustomFolder.yaml, deploy/examples/dashboards/DashboardWithPlugins.yaml, deploy/examples/dashboards/KeycloakDashboard.yaml, deploy/examples/dashboards/SimpleDashboard.yaml, documentation/dashboards.md, pkg/apis/integreatly/v1alpha1/grafanadashboard_types.go
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>
This PR removes spec.name from doc, dashboards examples and schema
Fixes: https://github.com/integr8ly/grafana-operator/issues/339
=> Remove unusued spec.name

documentation/deploy_grafana.md, pkg/apis/integreatly/v1alpha1/grafana_types.go, pkg/controller/model/grafanaDeployment.go
Deploying a Grafana instance in a restricted network requires one to override the default Grafana image (`grafana/grafana`) as well as the default Grafana Plugins Init Container image (`quay.io/integreatly/grafana_plugins_init`).
Within the Grafana custom resource, there is currently support for passing `baseImage` into its `spec`.  This Pull Request will provide support for passing `initImage` into its `spec` as well, so that both can be supplied within the CR exclusively and not via the operator deployment's `args` section.  This will make it easier for users in a restricted network to configure custom images.
1. Deploy new operator
2. Deploy Grafana CR with `spec.initImage` supplied:
```
kind: Grafana
metadata:
name: example-grafana
namespace: …
```
=> Adding support for overriding Grafana plugins init image

pkg/apis/integreatly/v1alpha1/grafana_types.go, pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go, pkg/controller/config/grafanaIni.go, pkg/controller/model/constants.go
Sigv4 is a prerequisite for connecting to a Prometheus data source that is managed by AWS
https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-query-standalone-grafana.html
Upgrade to Grafana 7.3.1 is required since sigv4 is introduced there
=> Add sigv4 authentication

deploy/crds/Grafana.yaml, documentation/deploy_grafana.md, pkg/apis/integreatly/v1alpha1/grafana_types.go, pkg/controller/model/grafanaIngress.go
Kubernetes 1.18 brought a few [changes](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/) in API for ingress:
* A new `pathType` field that can specify how Ingress paths should be matched.
* A new `IngressClass` resource that can specify how Ingresses should be implemented by controllers.
* Support for wildcards in hostnames.
This PR covers the first two (I guess, the third one should already work, haven't checked it).
1. `pathType` could be one of the following: `ImplementationSpecific`, `Exact`, `Prefix` (defaults to `ImplementationSpecific`).
API gives controllers freedom to decide what `ImplementationSpecific` means to them. - They could treat it as a separate `PathType` or identically to `Prefix` or `Exact` path types …
=> Added support for pathType, ingressClassName

pkg/controller/grafana/grafana_controller.go
Don't rely on the service ClusterIP, always prefer the DNS name.
#337 
1. Deploy the operator from this image: quay.io/pb82/grafana-operator:latest
2. Create a Grafana CR with `preferService` set to `true`.
3. Create some dashboards, make sure they are imported.
4. Delete the dashboards.
5. You should not see any failed API requests in the Operator logs.
=> fix: dont rely on service clusterip, prefer dns name

documentation/deploy_grafana.md, pkg/controller/model/grafanaDeployment.go
Add containerSeucirtyContext to init-container to be able to start the grafana-operator in a hardly locked down psp environment.
https://github.com/integr8ly/grafana-operator/issues/372
This could potentially break custom init-containers where they want to be allowed to use other containerSecurityContext vs what they have in there normal grafana containers. Rather low risk but still possible.
- [x ] This change requires a documentation update 
make code/run
Apply the following yaml:
```yaml
kind: Grafana
metadata:
name: grafana
spec:
deployment:
containerSecurityContext:
allowPrivilegeEscalation: false
capabilities:
drop:
- NET_RAW
readOnlyRootFilesystem: true
```
When your deployment/rs/pod have been created you will be able to see the following: …
=> Add containerSecurityContext init-container #372

pkg/apis/integreatly/v1alpha1/grafanadatasource_types.go
The suggested change adds support for [httpMethod](https://grafana.com/docs/grafana/latest/administration/provisioning/#example-datasource-config-file), which lets you specify a preferred HTTP method for a datasource (GET / POST).
Motivation:
* Grafana is moving to use POST by default for new instances ([PR](https://github.com/grafana/grafana/pull/31292)). You might want to keep using GET due to some constraints.
* You might want to actually use POST in older versions of Grafana as it offers a larger query body.
1. Include `httpMethod: POST` within `jsonData` block inside `GrafanaDataSource` CR.
```yaml
kind: GrafanaDataSource
metadata:
name: example-grafanadatasource
spec:
name: middleware.yaml
datasources:
- name: Prometheus
type: prometheus
access: …
```
=> Added support for httpMethod

pkg/apis/integreatly/v1alpha1/grafana_types.go, pkg/controller/config/grafanaIni.go
Enables support fot the auth.okta section of the grafana.ini parser.
https://github.com/integr8ly/grafana-operator/issues/378
Use a CRD with with the auth.okta enabled and validate it is rendered in the grafana.ini configmap.
```
kind: Grafana
metadata:
name: grafana
namespace: grafana
spec:
deployment:
nodeSelector:
nodegroup: kube-addons
ingress:
enabled: true
ingressClassName: nginx-private
hostname: grafana.foo.net
path: /
annotations:
kubernetes.io/ingress.class: nginx-private
cert-manager.io/cluster-issuer: vault
external-dns/private-record: 'true'
tlsEnabled: true
tlsSecretName: grafana-tls
termination: edge
config:
alerting:
enabled: false
analytics:
check_for_updates: false
reporting_enabled: false
auth.okta:
enabled: true
allow_sign_up: true …
```
=> Add in support for auth.okta to grafana.ini parser.

deploy/cluster_roles/cluster_role_grafana_operator.yaml, deploy/examples/dashboards/DashboardFromConfigMap.yaml
Add configmaps to cluster permissions for the operator
- Create a GrafanaDashboard with configmap ref.
- Create a Configmap which holds a Dashboard or Jsonnet Lib
- Ensure the operator has created a valid dashboard with the configmap contents
=> add configmaps to cluster_role permissions

pkg/controller/model/grafanaDeployment.go
Fixes the rolling update strategy,
The grafana web UI should no longer return 503's when resources are added to the grafana instance
- Check out the master branch
- Run the operator and open the web UI presented through the ingress/route
- add datasources from `deploy/examples/datasources` 
- The web UI should return 503 
-  Restart the operator from this branch
- add more datasources, the web UI should no longer return 503's while the operator adds datasources
=> change maxUnavailable and MaxSurge to use percentages as opposed to int

deploy/examples/ha/postgres.yaml
Update the Postgres deployment in HA example, it used an old apiVersion.
=> Update apiVersion of postgres deployment in HA example

pkg/apis/integreatly/v1alpha1/grafanadatasource_types.go
There is a typo for the Azure datasource field subscriptionId which prevents the operator of parsing the datasource correctly
- use operator with existing Azure datasource example: https://github.com/integr8ly/grafana-operator/blob/master/deploy/examples/datasources/Azure.yaml
- subscriptionId should be parsed correctly now
=> .Fix typo subscriptionId

deploy/examples/datasource-env-vars/Grafana.yaml, deploy/examples/datasource-env-vars/Prometheus.yaml, deploy/examples/datasource-env-vars/secret.yaml, documentation/README.md, documentation/env_vars.md
Add an example and docs to show how to use environment variables in data sources.
Docs and example only.
fixes #393
=> docs: describe using environment variables in data sources

documentation/deploy_grafana.md, pkg/controller/model/constants.go
In OpenShift, if you use a pull secret for Docker Hub, it will only be used if the fully qualified image name is used. The common reason for a pull secret is to deal with the Docker Hub rate limit.
Otherwise I have to overwrite with `baseimage` to work around the rate limit.
https://developers.redhat.com/blog/2021/02/18/how-to-work-around-dockers-new-download-rate-limit-on-red-hat-openshift/
Pod is deployed with the FQIN in its spec.
=> Use fully qualified image name

pkg/controller/grafanadashboard/grafana_client.go
Before:
```
{"msg": "cannot submit dashboard monitoring/gitlab-projects","error":"error creating dashboard, expected status 200 but got 400"}"
```
After:
```
{"msg": "cannot submit dashboard monitoring/gitlab-projects","error":"error creating dashboard, expected status 200 but got 400: {\"message\":\"Dashboard title cannot be empty\"}"
```
Debugging a 400 error recently while migrating from grafonnet to grafonnet-7.0. There's not a migration guide at the moment, so I've been playing whack-a-mole updating things. Eventually got to a point where my jsonnet was rendering but the dash was 4xx'ing.
Adding this little bit of logging was clutch in making me realize I had to provide a dashboard title in my `grafana.dashboard.new` call.
* https://github.com/integr8ly/grafana-operator/issues/370: …
=> provide additional error context during failures

api/integreatly/v1alpha1/grafana_types.go, api/integreatly/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/integreatly.org_grafanas.yaml, config/manager/kustomization.yaml, controllers/model/grafanaDeployment.go, documentation/deploy_grafana.md
This change adds support to override the default deployment strategy
given to Grafana deployments through the Grafana CRD.
The existing default behaviour remains unchanged, but override can
now be performed by setting Deployment.Strategy on the GrafanaSpec.
This is particularly useful for deployments that use RWO PVC storage
where deployment strategy type 'Recreate' is required.
Resolves #406 
Test Cases:
- `Grafana` resource with no `deployment` property set
- Should observe Grafana deployment has deployment strategy of 25%/25% Rolling Update
- `Grafana` resource with `deployment` property set, but `strategy` left unset
- Should observe Grafana deployment has deployment strategy of 25%/25% Rolling Update
- `Grafana` resource with `deployment.strategy` set to something other than the …
=> Add support to override default deployment strategy

main.go
The operator was not constraining the Grafana controller to the operator namespace.
Set the namespace when creating the controller manager in main.go.
* Deploy the operator using operator.yaml, but make sure to point to an image created from master
* Make sure that Grafana CRs in other namespaces are not discovered
* Make sure that Grafana CRs in the operators namespace are discovered
=> fix: add watch namespace back to mgr

api/integreatly/v1alpha1/grafana_types.go
This should solve #388.
Making sure that both Name and Version is defined in GrafanaPlugin
the error rate among users should become lower.
https://github.com/integr8ly/grafana-operator/issues/388
Sadly I can't verify this since we are  currently using operator-sdk v.0.18.2.
I have tested to do similar things on operator-sdk v1.3.2 and I can see that the CRD definition get's updated.
These changes won't create any effect until the upgrade to v1.3.2  is done: https://github.com/integr8ly/grafana-operator/pull/327.
=> Set GrafanaPlugin name & version to requiered

pkg/controller/model/grafanaDataPvc.go
Thank you for your great works! I fixed some behavior.
use default storage class when class is not defined
When Grafana.spec.dataStorage.class is not defined or set nil, generated PVC.spec.storageClassName is set "".
But I think we prefer to use default storageClass.
```yaml
kind: Grafana
metadata:
name: grafana
spec:
baseImage: grafana/grafana:7.4.3
...
dataStorage:
accessModes:
- ReadWriteOnce
size: 5Gi
```
* default bahavior
```yaml
$ k -n grafana get pvc grafana-pvc -oyaml | k neat
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: grafana-pvc
namespace: grafana
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 5Gi
storageClassName: ""
```
* newer bahavior
```yaml
$ k -n grafana get pvc grafana-pvc -oyaml | k neat
apiVersion: …
```
=> fix: use default storage class when class is not defined

build/Dockerfile, deploy/olm-catalog/grafana-operator/3.x.x/3.10.2/grafana-operator.v3.10.2.clusterserviceversion.yaml, deploy/olm-catalog/grafana-operator/3.x.x/3.10.2/grafanadashboards.integreatly.org.crd.yaml, deploy/olm-catalog/grafana-operator/3.x.x/3.10.2/grafanadatasources.integreatly.org.crd.yaml, deploy/olm-catalog/grafana-operator/3.x.x/3.10.2/grafanas.integreatly.org.crd.yaml, deploy/operator.yaml, version/version.go
- Update the base image to ubi-minimal:8.4 to mitigate vulnerabilities
=> Upgrade dockerfile base image and prepare the v3.10.2 release 

controllers/grafana/grafana_controller.go, deploy/operator.yaml
Fixes an issue where the constructed service DNS name was invalid when using the `preferService` option.
1. Create a custom image and deploy the Operator to a cluster using that image.
2. Deploy grafana makeing sure that `client.preferService` is set to `true` in the spec.
3. Create dashboards and make sure they can be imported and deleted.
=> fix: use correct service dns name

controllers/model/grafanaDeployment.go
- Fixes a missed nil check on the Deployment struct when attempting to access httpProxy config.
```
E0706 21:20:02.234098  916414 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 655 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1648f40, 0x23c4850)
/home/hstefans/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/home/hstefans/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1648f40, 0x23c4850)
/usr/lib/golang/src/runtime/panic.go:965 +0x1b9
github.com/integr8ly/grafana-operator/controllers/model.getInitContainers(0xc000261000, 0x0, 0x0, 0x8, …
```
=> fix nil pointer exception on cr.Spec.Deployment

controllers/grafanadashboard/dashboard_pipeline.go, documentation/dashboards.md
Right now the dashboard fetch priority by parameters provided in `GrafanaDashboard` resource is: configmap > json > url > jsonnet. This is inconsistent with the [code comments](https://github.com/grafana-operator/grafana-operator/blob/3de75fec6c15bba8feb94af3cd5ced0c7b4cbb01/controllers/grafanadashboard/dashboard_pipeline.go#L108-L113).
Also, if the url for an existing dashboard is updated, it won't update the fetched json (mentioned in [issue](https://github.com/grafana-operator/grafana-operator/issues/440#issuecomment-869139846)). 
This PR will change the fetch priority to: url > configmap > json > jsonnet. Which in turn will fix the above mentioned issue.
https://github.com/grafana-operator/grafana-operator/issues/440#issuecomment-869139846
1. Deploy Changes
2. Deploy Dashboard which …
=> [GrafanaDashboard] Fetch dashboard from url even if json parameter is set

config/rbac/role.yaml, controllers/grafana/grafana_controller.go, controllers/grafanadashboard/grafanadashboard_controller.go, controllers/grafanadatasource/datasource_controller.go
In the master branch there a bunch of missing roles that doesn't get generated.
- #465 
Follow https://github.com/grafana-operator/grafana-operator/blob/master/documentation/develop.md#kind-load-docker-image
```shell
kubectl apply -f deploy/examples/Grafana.yaml
```
You shouldn't see any errors in the logs about missing access to perform certain tasks.
Note that I didn't add a bunch off access defined in the old rbac, https://github.com/grafana-operator/grafana-operator/blob/master/deploy/role.yaml
For example I don't think we need access to perform tasks against `pods & endpoints`.
I don't know to what degree you should be able to patch/update a event as a operator, naturally for me it feels like it should be only create, get, list.
We do not need access to look at `replicasets, …
=> Add missing kubebuilder rbac

.github/workflows/pr-validation.yaml
This way if the developer have forgotten to check in the latest
manifest files it will be cought.
And the reviewers don't have to guess
Create a PR that would generate manifests changes but forget to run make manifests.
=> Check manifest generation at PR

deploy/examples/Grafana.yaml
This addresses a compatibility issue with Kubernetes v1.20+
Solves #487 
```shell script
kind create cluster --image=kindest/node:v1.20.7
make install 
make cluster/prepare/local
make run
```
=> Chore: Update example Grafana to add path and pathType fields

config/crd/bases/integreatly.org_grafanas.yaml, controllers/grafanadashboard/dashboard_pipeline.go, controllers/grafanadashboard/grafana_client.go, controllers/grafanadashboard/grafanadashboard_controller.go
Dashboards delete via the Grafana console will still exist as CRs and won't be recreated. They should be recreate if deleete this way. The correct way to delete a dashboard is to delete the CR.
https://github.com/grafana-operator/grafana-operator/issues/432
1. Create a grafanadashboard CR
2. Log into the Grafana console
3. Delete the dashboard from Dashboard settings in the console
4. Wait for a periodic reconcile
5. Check in the Grafana console that the dashboard has been recreated
=> Recreate dashboards deleted via Grafana console

api/integreatly/v1alpha1/grafana_types.go, api/integreatly/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/integreatly.org_grafanas.yaml, controllers/model/grafanaDeployment.go, go.mod, go.sum
Termination grace period is required and this change makes it so it is not required and it will now default to the kubernetes default
https://github.com/grafana-operator/grafana-operator/issues/462
Deploy a grafana instance with the deployment override included but without specifying a termination grace period. The grafana instance should be created without any errors.
=> Made termination grace period not required

api/integreatly/v1alpha1/grafana_types.go, api/integreatly/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/integreatly.org_grafanas.yaml, controllers/config/grafanaIni.go
Add `role_attribute_strict` bool flag in the generic and okta oauth configs.
This was added in upstream grafana in the following PR: https://github.com/grafana/grafana/pull/28021
Resolves https://github.com/grafana-operator/grafana-operator/issues/498
1. Deploy Operator
2. Deploy Grafana
3. Add the following in grafana resource
```yaml
config:
auth.generic_oauth:
enabled: true
role_attribute_strict: true
```
4. The created grafana container should have a `grafana.ini` with the following string `role_attribute_strict: true`
=> Add `role_attribute_strict` flag in generic/okta oauth config

api/integreatly/v1alpha1/grafana_types.go, api/integreatly/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/integreatly.org_grafanas.yaml, controllers/model/grafanaDeployment.go
This is a simple change. I've simply added an "env" field of type v1/EnvVar to Grafana.Deployment.Spec.
This lets you create environment variables from ConfigMap and Secret keys (rather than converting a ConfigMap/Secret to env vars as the envFrom field does). 
It helped me in my use case, thought I'd share that.
Tested this on my own Kubernetes environment
=> "env" field in Grafana.Deployment.Spec

deploy/crds/Grafana.yaml, documentation/deploy_grafana.md, pkg/apis/integreatly/v1alpha1/grafana_types.go, pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go, pkg/controller/model/grafanaDeployment.go
Backport 558b175a119ac3fc7ab70b94b1ce8598ea52d4d9 to v3 branch.
Add support to override default deployment strategy
This change adds support to override the default deployment strategy
given to Grafana deployments through the Grafana CRD.
The existing default behaviour remains unchanged, but override can
now be performed by setting Deployment.Strategy on the GrafanaSpec.
This is particularly useful for deployments that use RWO PVC storage
where deployment strategy type 'Recreate' is required.
#415 #463 #453
=> Backport 558b175a119ac3fc7ab70b94b1ce8598ea52d4d9

.github/workflows/pr-validation.yaml, Makefile, documentation/README.md, documentation/api.md, documentation/dashboards.md, documentation/datasources.md, documentation/deploy_grafana.md
* Update makefile and auto run after test, this way they are always run by a developer
* Add to CI to check for dirty file-system
* Create documentation/api/ to store the new api docs.
#519 
#502
=> Autogenerate API docs

api/integreatly/v1alpha1/grafanadatasource_types.go, config/crd/bases/integreatly.org_grafanadatasources.yaml, documentation/api.md
Add the field 'clusterUrl' for Azure Data Sources (e.g. Azure Data Explorer).
https://github.com/grafana-operator/grafana-operator/issues/523
=> Add known field 'clusterUrl' for Azure data sources

controllers/model/grafanaRoute.go
Sets default path (/) when creating an ingress and no explicit path is set by user
https://github.com/grafana-operator/grafana-operator/issues/487
* Operator deployed locally with using example Grafana instance with `path: " "` in `spec.ingress`
* Grafana ingress object should contain default path of `path: /`
=> Issue #487: set default ingress path 

api/integreatly/v1alpha1/grafana_types.go, bundle/manifests/integreatly.org_grafanadashboards.yaml, bundle/manifests/integreatly.org_grafanadatasources.yaml, bundle/manifests/integreatly.org_grafanas.yaml, config/crd/bases/integreatly.org_grafanas.yaml
Improve the bundle CRDs by adding nullable to all non-struct pointer fields. When running the v3.10.x, some of the fields in the CR get set to `null` when only partially specifying a config struct. Those fields can't be parsed when they are not set to nullable and cause a validation error when upgrading the CRD.
=> add nullable to non struct pointer fields to support cr migration

config/rbac/role.yaml, controllers/grafananotificationchannel/grafananotificationchannel_controller.go
GrafanaNotificationChannel was added to master. Deploying operator via `kustomize build config/install |kubectl apply -f -
`, the operator logs the following error:
```
E0929 06:59:09.118594       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1alpha1.GrafanaNotificationChannel: failed to list *v1alpha1.GrafanaNotificationChannel: grafananotificationchannels.integreatly.org is forbidden: User "system:serviceaccount:grafana-operator-system:default" cannot list resource "grafananotificationchannels" in API group "integreatly.org" in the namespace "grafana-operator-system"
```
- Deploy fresh operator following supplied documentation on current master to note the error.
- Modify the manager-role and add rules for the …
=> Add rules for GrafanaNotificationChannel to ClusterRole manager-role

deploy/operator.yaml
The referenced Image was never build.
This PR adds the correct one, so if anyone would try to deploy it, he would not fail to do so.
#585 
- spin a Kubernetes distribution and add deployment via kubectl
=> #585: changes image to current version in deploy of operator

Dockerfile, deploy/examples/dashboards/DashboardFromGrafana.yaml, hack/clean_e2e.sh, hack/e2e.sh
Adds the root CA bundle to the final docker image so enable downloading dashboards from public HTTPS URLs
#591 
I haven't properly tested in a cluster, however I've verified the ca-bundle.crt file in my workaround described in #591 is in the same location, permissions and contents compared to running the new docker image locally.
You can verify this by creating a dashboard like so:
```yaml
kind: GrafanaDashboard
metadata:
name: node-exporter-full
labels:
app: grafana
spec:
datasources:
- inputName: "DS_PROMETHEUS"
datasourceName: "Prometheus"
grafanaCom:
id: 1860
revision: 23
json: ""
```
I need to jump on work things so don't have time to verify in a cluster myself. I may have time at the weekend, failing that I can make time next week, but if someone …
=> fix: add root CA bundle to docker image (#591)

api/integreatly/v1alpha1/grafana_types.go, config/crd/bases/integreatly.org_grafanas.yaml, controllers/config/grafanaIni.go, documentation/api.md
Added the option to change the default home dashboard path.
Relates to #578
=> Added default_home_dashboard_path

api/integreatly/v1alpha1/grafanadatasource_types.go, config/crd/bases/integreatly.org_grafanadatasources.yaml, deploy/examples/datasources/Alertmanager.yaml, documentation/api.md
=> Forwardport from grafana-operator v3 the json data field `implementation` for Alertmanager Datasource.

api/integreatly/v1alpha1/grafanadashboard_types.go, api/integreatly/v1alpha1/grafanadatasource_types.go, api/integreatly/v1alpha1/grafananotificationchannel_types.go, bundle.Dockerfile, bundle/manifests/grafana-operator-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/grafana-operator.clusterserviceversion.yaml, bundle/manifests/integreatly.org_grafanadashboards.yaml, bundle/manifests/integreatly.org_grafanadatasources.yaml, bundle/manifests/integreatly.org_grafananotificationchannels.yaml, bundle/manifests/integreatly.org_grafanas.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml, config/crd/bases/integreatly.org_grafanadashboards.yaml, config/crd/bases/integreatly.org_grafananotificationchannels.yaml, config/manifests/bases/grafana-operator.clusterserviceversion.yaml, documentation/api.md
- adds `omitempty` to `dashboard.spec.json`
- regenerates api-docs
- fixes misplaced comments in structs, adding descriptions where they aren't supposed to be
- Set serviceAccountName: grafana-operator-controller-manager
=> fix: add omitempty to dashboard spec json field and generate docs

bundle/manifests/grafana-operator.clusterserviceversion.yaml
This is necessary for the operator to be displayed in the OpenShift web console OperatorHub on non-x86 architectures.
=> Add architecture labels to CSV

bundle/manifests/grafana-operator.clusterserviceversion.yaml, config/manifests/bases/grafana-operator.clusterserviceversion.yaml
v4.0.2 is replaces v4.0.1 and not v4.0.0
Missed one value when creating the tag. Sadly this won't be part of 4.0.2 tag but it won't create any issues for operatorhub.io. I have manually updated this change in the PR.
=> Set correct replace in OLM config for v4.0.2

config/rbac/role.yaml, controllers/grafana/grafana_controller.go, deploy/manifests/latest/rbac.yaml
This way --scan-all don't have to add any custom clusterroles.
Solves #630
#630 
- Update the deployment, to use --scan-all: https://github.com/grafana-operator/grafana-operator/blob/master/deploy/manifests/latest/deployment.yaml
- k apply -k deploy/manifests
- k apply -f deploy/examples/Grafana.yaml
- Add dashboards to a random namespace with the correct selectors.
You shouldn't see any errors.
=> RBAC add possability to patch events

config/manager/manager.yaml, config/manager/manager_auth_proxy_patch.yaml, deploy/manifests/latest/deployment.yaml
Solves #629, currently leader-elect is broken so for now we disable it.
In the future we will most likley re-enable it again.
#629 
#631 
#620 
- k apply -k deploy/manifests
- Wait and see that the operator starts
- Update the deployment, for example set log level to debug in `deploy/manifests/latest/deployment.yaml`
- k apply -k deploy/manifests
The operator will be recreated without any issues and won't complain about missing node access.
=> Stop using leader-elect, use deployment recreate

config/rbac/role.yaml, controllers/grafana/grafana_controller.go, deploy/manifests/latest/rbac.yaml
When using custom host for Grafana's ingress at OpenShift, Grafana provisioning is failing with insufficient permissions error:
```yaml
kind: Grafana
metadata:
name: grafana
spec:
ingress:
enabled: true
hostname: grafana.apps.openshift-cluster.com  # <-- custom host
...
status:
message: >-
Route.route.openshift.io "grafana-route" is invalid: spec.host: Forbidden:
you do not have permission to set the host field of the route
phase: failing
```
To allow Grafana's controller to edit custom host in OpenShift's routes, it should have access to `routes/custom-host` resource. 
-  [x] Bug fix (non-breaking change which fixes an issue)
1. Install Grafana Operator from OpenShift's Operator Hub (`v4.1.0` at the moment)
2. Create Grafana CR with custom …
=> Added OpenShift specific permissions to set custom host for route

README.md
Fix a typo in the README: Developement => Development.
=> Fix a typo in the README: Developement => Development

api/integreatly/v1alpha1/grafanadatasource_types.go, config/crd/bases/integreatly.org_grafanadatasources.yaml, deploy/examples/datasources/Instana.yaml, deploy/manifests/latest/crds.yaml, documentation/api.md
Added ability to create Instana DataSource CRs.
Fixes #434
=> Add Instana datasource

documentation/deploy_grafana.md, main.go
Added support for overriding Grafana image/tag and plugins image/tag through environment variables.
This is needed to allow configuration overrides when installing the operator in OpenShift 4.x using OLM, as the Subscription resource doesn't allow for adding command line arguments to the deployed operator.
- [x ] New feature (non-breaking change which adds functionality)
- [ x] This change requires a documentation update 
In OpenShift when deploying using Subscription, add a section as follows:
```
config:
env:
- name: GRAFANA_IMAGE_URL
value: someregistry.com/somegrafana
```
Verify that the Grafana deployments created uses the specified container image url.
=> feat: added support for flag overrides using environment variables

api/integreatly/v1alpha1/grafana_types.go, config/crd/bases/integreatly.org_grafanas.yaml, controllers/model/grafanaDeployment.go, deploy/manifests/latest/crds.yaml, documentation/api.md, documentation/plugins.md
- adds new configuration options for secure http proxy env vars to be used when downloading plugins
=> feat: add HTTPSProxy to env var

controllers/config/grafanaIni.go, controllers/config/grafanaIni_test.go
Many months ago, I added support for `login_maximum_inactive_lifetime_duration` and `login_maximum_lifetime_duration` in https://github.com/grafana-operator/grafana-operator/pull/345. It was quite important to have this functionality since grafana still doesn't fully track validity of OIDC sessions, which leads to forwarding stale tokens to data sources unless the right settings are made in both grafana and Keycloak. - Other parameters `login_maximum_lifetime_days` and `login_maximum_inactive_lifetime_days`, don't give enough flexibility in the period of time.
Haven't used grafana-operator since I changed companies. Recently, I rebuilt a local lab with a fresh grafana-operator, and noticed today that grafana was sending stale tokens, which shouldn't have been the case since I had all the …
=> fix: reintroduce login duration

api/integreatly/v1alpha1/grafanadatasource_types.go, config/crd/bases/integreatly.org_grafanadatasources.yaml, deploy/manifests/latest/crds.yaml, documentation/api.md
Whitelist the jsonData fields used by the [grafana-clickhouse-datasource](https://grafana.com/grafana/plugins/grafana-clickhouse-datasource/).
- https://github.com/grafana-operator/grafana-operator/issues/688
I'm not sure if this is breaking or not. It whitelists 3 fields in jsonData in the datasource CRD.
=> Whitelist fields for Grafana Clickhouse datasource

api/integreatly/v1alpha1/grafanadatasource_types.go, config/crd/bases/integreatly.org_grafanadatasources.yaml, deploy/manifests/latest/crds.yaml, documentation/api.md
Add support for the new field timezone, in jsonData, used by the MySQL data source:
https://grafana.com/docs/grafana/latest/datasources/mysql/
None
Not sure if this is breaking or not. It whitelists one field in jsonData in the datasource CRD.
- Create datasource with the field timestamp in jsonData and verify that the timezone is present in the datasource.
=> Add support for timezone in jsonData for MySQL data source

Dockerfile
When building the grafana operator from source within a network restricted environment, being able to use local images and GOPROXY/GOPRIVATE is a requirement.
#707
=> Enable restricted network builds

config/manifests/bases/grafana-operator.clusterserviceversion.yaml
This is the standard that we have been using in OLM.
Changing this will remove a manual step in the release.
This is how it looks in OLM:
https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/5c964fcff569a9131ceebc48f28869c4b9713860/operators/grafana-operator/4.2.0/grafana-operator.clusterserviceversion.yaml#L16
=> Documentation Clusterserviceversion manifest supported Red Hat

go.mod, go.sum
The project github.com/openshift/api has removed their tags and grafana-operator references the tag v3.9.0, which are unaccessable when not using proxy.golang.org where it's currently cached.
https://github.com/grafana-operator/grafana-operator/issues/706
https://github.com/openshift/api/issues/456
https://github.com/openshift/api/issues/587
https://github.com/openshift/api/issues/647
```
docker build --no-cache --build-arg GOPROXY=direct .
```
=> Use github.com/openshift/api@release-3.9

controllers/config/controller_config.go
update init container default image
1. deploy operator from the branch and create one of the example dashboards containing plugins
2. ensure that the plugin is installed correctly
=> fix: update default init container image to fix cve

controllers/config/controller_config.go, controllers/grafana/grafana_controller.go
When the GetDashboards function is called for the re-sync it gets called with the namespace specified as the empty string, this wasn't accounted for in #690. So, after #690 the reconciliation of dashboards (for the periodic re-sync) started getting an empty list of known dashboards which then caused any checking of existing dashboards to fail. 
Some people have noticed that this started happening in 4.3.0 (myself included): https://github.com/grafana-operator/grafana-operator/issues/686#issuecomment-1114753394
Built and tested on my home cluster and seems to have solved the issue of new versions being created each sync period.
Docker image available here: `ghcr.io/addreas/grafana-operator:v4.3.0-690-bugfix`
=> Fix bug introduced by #690

controllers/config/controller_config.go, controllers/grafana/grafana_controller.go, controllers/grafanadashboard/grafanadashboard_controller.go, controllers/grafananotificationchannel/grafananotificationchannel_controller.go, documentation/deploy_grafana.md, main.go
Allows the current default of refreshing dashboards every 10 seconds to be configured. This might be useful in the situation where something isn't configured correctly, or there are a huge amount of dashboards such that the operator is constantly busy updating dashboards which might make it hard to understand what is happening.
Tested on a home cluster and seems to work as intended.
=> Configurable RequeueDelay

PREPARE_RELEASE.md, bundle/manifests/grafana-operator.clusterserviceversion.yaml, config/manifests/bases/grafana-operator.clusterserviceversion.yaml
Update documentation to match.
=> Fix base manifest annotation to 4.4.0

controllers/model/grafanaService.go
Simple fix: add a nil check for service & service ports before iterating in GetServicePorts
https://github.com/grafana-operator/grafana-operator/issues/746
=> Add nil check for service & service ports before iterating

README.md
Grammatical and spelling error.
1. To get **a overview** of the available grafana-operator CRD see api.md.
2. Efficient dashboard management through jsonnet, plugins, **organisations** and folder assignment, which can all be done through `.yamls` !
1. To get **an overview** of the available grafana-operator CRD see api.md.
2. Efficient dashboard management through jsonnet, plugins, **organizations** and folder assignment, which can all be done through `.yamls` !
=> Fix grammar getting started docs

controllers/model/grafanaRoute.go
Fixed to return empty path when ingress termination is "passthrough".
Passthrough mode doesn't require path setting.
https://github.com/grafana-operator/grafana-operator/issues/766
0. Check environment
```
$ oc version
Client Version: 4.9.21
Server Version: 4.10.15
Kubernetes Version: v1.23.5+3afdacb
```
1. Create Grafana custom resouce like bellow.
```yaml
kind: Grafana
metadata:
name: grafana-sample
spec:
ingress:
enabled: True
termination: passthrough
config:
security:
admin_user: admin
admin_password: admin
```
2. Check generated route resouce
```
oc get route grafana-route -o yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
annotations:
openshift.io/host.generated: "true"
creationTimestamp: "2022-06-08T14:01:35Z"
name: grafana-route …
```
=> Return empty path for termination passthrough

api/integreatly/v1alpha1/grafana_types.go, config/crd/bases/integreatly.org_grafanas.yaml, controllers/model/grafanaDeployment.go, controllers/model/grafanaDeployment_test.go, controllers/model/grafanaRoute.go, deploy/manifests/latest/crds.yaml, documentation/api.md
Add noProxy setting in `spec.deployment.httpProxy` of Grafana resource.
#736
```
$ cat <<EOF | kubectl apply -f -
kind: Grafana
metadata:
name: grafana-sample-with-proxy
spec:
ingress:
enabled: True
config:
security:
admin_user: admin
admin_password: admin
deployment:
httpProxy:
enabled: true
url: http://192.168.1.10:8080
secureUrl: http://192.168.1.10:8080
noProxy: ".cluster.local,.svc,.example.com,localhost"
EOF
grafana.integreatly.org/grafana-sample-with-proxy created
$ kubectl get pod -o yaml | grep -A1 NO_PROXY
- name: NO_PROXY
value: .cluster.local,.svc,.example.com,localhost
```
=> Add noProxy setting n spec.deployment.httpProxy of Grafana resource

api/integreatly/v1alpha1/grafanadatasource_types.go, bundle/manifests/integreatly.org_grafanadatasources.yaml, config/crd/bases/integreatly.org_grafanadatasources.yaml, deploy/manifests/latest/crds.yaml, documentation/api.md
This PR adds support for `queryTimeout` (part of `jsonData`) in datasources.
Closes: #782 
1. Add a datasource with a custom `queryTimeout` in `jsonData`:
```yaml
kind: GrafanaDataSource
metadata:
name: example-grafanadatasource
spec:
name: middleware.yaml
datasources:
- name: Prometheus
type: prometheus
access: proxy
url: http://prometheus-service:9090
isDefault: true
version: 1
editable: true
jsonData:
tlsSkipVerify: true
timeInterval: "5s"
queryTimeout: 30s
```
2. In Grafana, inspect the datasource:
=> feat: add support for queryTimeout in datasources

controllers/grafana/grafana_controller.go
There's a cosmetic bug in `getGrafanaAdminUrl` - if unsupported protocol is chosen through `config.server.protocol`, the operator would always complain about `http` instead of actual protocol: `server protocol http is not supported, please use either http or https`.
The PR fixes that.
Deploy grafana with the following config:
```yaml
kind: Grafana
metadata:
name: example-grafana
spec:
client:
preferService: true
config:
server:
protocol: unknown-protocol
```
You should see a reference to `unknown-protocol` in the error message:
`grafana-operator-846d554b57-vvxgs grafana-operator 2022-07-20T16:28:21.238Z	DEBUG	controller-runtime.manager.events	Warning	{"object": {"kind":"Grafana","namespace":"monitoring","name":"example-grafana","uid":"f218c504-fd0a-4fc2 …
=> fix: return correct message about unsupported protocol

config/manifests/bases/grafana-operator.clusterserviceversion.yaml
An error in the prepare 4.5.1 commit. I fix this now so I don't forget it to the next release as well.
=> Update replaces for 4.5.1 manifests

api/integreatly/v1alpha1/grafanadatasource_types.go, config/crd/bases/integreatly.org_grafanadatasources.yaml, deploy/manifests/latest/crds.yaml, documentation/api.md
This addition allows setting the data-source HTTP client [timeout](https://github.com/grafana/grafana/blob/6d5bdf12e850b3df2a8b6d26f39c277b226f4c85/pkg/services/datasources/service/datasource.go#L503), to work around situations where the default timeout is to small. 
Note, I choose the type `int` for the timeout as this is what the Grafana [code primarily expects](https://github.com/grafana/grafana/blob/6d5bdf12e850b3df2a8b6d26f39c277b226f4c85/pkg/services/datasources/service/datasource.go#L503), technically `string` or `intstr.IntOrString` would also work.
Signed-off-by: Alexander Berger <alex.berger@nexxiot.com>
=> add support to set datasource timeout

documentation/deploy_grafana.md
Got confused constants.go had no changes since last summer. Line number is unlikely to change (has not in a year).
Check that link works and that file is updated last year.
=> Link to constants.go on master branch

api/integreatly/v1alpha1/grafana_types.go, api/integreatly/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/integreatly.org_grafanas.yaml, controllers/model/grafanaDeployment.go, controllers/model/grafanaDeployment_test.go, deploy/manifests/latest/crds.yaml, documentation/api.md
Adds specification of topology spread constraints to a managed Grafana deployment.
Closes #834.
1. With the Grafana operator running against a cluster, add a Grafana CR without TopologySpreadConstraints defined in the `deployment` specification.
2. Ensure the resultant Grafana deployment contains no topology spread constraints.
3. Specify a Grafana CR with some arbitrary TopologySpreadConstraints defined.
4. Ensure the resultant Grafana deployment contains the same topology spread constraints.
=> Adding Topology Spread Constraints to Grafana CR

controllers/model/grafanaDeployment.go
Documentation states that containerSecurityContext should also affect the init-container, this patch should actually apply this previously missing feature.
Documentation already contains this as a NOTE under https://github.com/grafana-operator/grafana-operator/blob/master/documentation/deploy_grafana.md#configuring-the-deployment
Ensure that deployment.containerSecurityContext is propagated to initContainer.
grafana.yaml
```
kind: Grafana
metadata:
name: grafana
spec:
client:
preferService: true
ingress:
enabled: False
config:
log:
mode: "console"
level: "error"
log.frontend:
enabled: true
auth:
disable_login_form: False
disable_signout_menu: True
auth.anonymous:
enabled: True
service:
name: "grafana"
labels:
app.kubernetes.io/name: grafana
type: …
```
=> Fix containerSecurityContext for init-container

controllers/model/adminUserSecret.go, controllers/model/grafanaConfig.go
=> Prevent configmap and secret annotations from being deleted.

api/integreatly/v1alpha1/grafana_types.go, api/integreatly/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/integreatly.org_grafanas.yaml, config/crd/bases/integreatly.org_grafanas.yaml, controllers/config/grafanaIni.go, controllers/config/grafanaIni_test.go, deploy/manifests/latest/crds.yaml, documentation/api.md
Very similar to https://github.com/grafana-operator/grafana-operator/pull/889
adds `pkce` support: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/#pkce
✅ built and tested with image: `maciekm/grafana-operator:use-pkce-1`
https://github.com/grafana-operator/grafana-operator/issues/877
=> Generic OAuth - add use_pkce field

controllers/model/grafanaService.go
When grafana instance is created, the port name configured for the service does not take effect. is also not effective when changed grafana nodeport
```
kind: Grafana
metadata:
name: grafana
namespace: monitoring
spec:
client:
preferService: true
ingress:
enabled: False
config:
log:
mode: "console"
level: "error"
security:
admin_user: "root"
admin_password: "12345"
log.frontend:
enabled: true
auth:
disable_login_form: False
disable_signout_menu: False
auth.anonymous:
enabled: True
service:
name: "grafana-service"
labels:
app: "grafana"
type: "grafana-service"
ports:
- { nodePort: 30004, port: 3000, protocol: TCP, name: web }
type: NodePort
dashboardLabelSelector:
- matchExpressions:
- { key: app, operator: In, values: [grafana] }
resources:
limits: …
```
=> Fix port name not in effect and nodePort changed failed when update

deploy/helm/grafana-operator/README.md, deploy/helm/grafana-operator/README.md.gotmpl
Need to come up with a better way of managing this in the future.
=> Update helm docs to point to v5.0.0-rc0

controllers/datasource_controller.go
Hit PR corrects some copy/paste issues in the datasource controller.
=> correct comments and error messages in datasource controller

deploy/base/serviceaccount.yaml, deploy/helm/grafana-operator/templates/serviceaccount.yaml
explicitly set `automountServiceAccountToken` to "true" in grafana-operator-controller-manager Serviceaccount for Operator
Since it's needed to connect to the in-cluster k8s API. The k8s default is "true", but it might be "false" on customized clusters, leading to failure when deploying the operator.
=> explicitly set `automountServiceAccountToken` to "true"

deploy/helm/grafana-operator/README.md, deploy/helm/grafana-operator/templates/deployment.yaml, deploy/helm/grafana-operator/values.yaml
The helm config of kube rbac proxy had some unmapped values, which are now correctly mapped.
Also additional properties such as securityContext, liveness- / readynessProbe and reyources can now be defined for the kube rbac proxy container.
=> extend kubeRbacProxy helm configuration

deploy/helm/grafana-operator/README.md, deploy/helm/grafana-operator/templates/deployment.yaml, deploy/helm/grafana-operator/values.yaml
In some use cases it might be nice to be able to disable rbac kube proxy all together.
=> [helm] make it possibel to disable rbac kube proxy

.github/workflows/pr-validation.yaml, Makefile, api/v1beta1/grafana_types.go, config/grafana.integreatly.org_grafanas.yaml, config/kustomization.yaml, docs/docs/api.md
Adding explanation to the grafana CRDs to make the operator usage clearer.
I also update the `make api-docs` command to point on the more detailed CRD definition.
This definition enables our online documentation to become more detailed.
Sadly these docs won't be shown in the k8s api, due to how big the grafana crd is due to all the default resources.
So for example 
``` shell
k explain grafana.spec.config 
KIND:     Grafana
VERSION:  grafana.integreatly.org/v1beta1
DESCRIPTION:
<empty>
```
Will keep on looking like this even after my change.
=> Generate grafana crd documentation

controllers/reconcilers/grafana/grafana_service_reconciler.go, docs/blog/v5-getting-started.md, tests/e2e/example-test/00-assert.yaml
When calling grafana by service name, we don't have to rely on FQDN. The change reintroduces a fix similar to #791.
Fixes: #959
=> fix: don't use hardcoded cluster domain

docs/docs/_index.md, docs/docs/dashboards.md
This is the behavior I have documented and not content cahce duration. I have added seperate documentation for it now.
=> [docs] Change contentChangeDuration to rsync

deploy/helm/grafana-operator/templates/deployment.yaml, deploy/helm/grafana-operator/templates/service.yaml
Target port name must match the pod exposed port, if not the service won't select the endpoints.
gave port a name of metrics so it is clear as to what it is, setting the service port as https provides clarity as to the protocol to use on connection.
**Why change was required:** metrics service was not selecting the pod due to port names not matching. this prevented Prometheus from scraping the pods metrics.
These changes have been tested in a clean kind cluster with the service now selecting the operator pod.
=> fix: [helm] service not selecting endpoints

.github/workflows/pr-validation.yaml, CONTRIBUTING.md, Makefile, deploy/kustomize/base/crds.yaml
=> Update make manifests to update deploy/base/

.github/workflows/release-github.yaml
This to make sure that our Kustomize release always is up-to-date, just like we do for helm.
=> During release update kustomize image to match tag version

deploy/helm/grafana-operator/templates/deployment.yaml
Set default value of WATCH_NAMESPACE to installation namespace if namespaceScope is set.
Closes #1005
=> Default value of WATCH_NAMESPACE when namespaceScope=true

examples/k3d/README.md, examples/k3d/resources.yaml
A small example that creates a working Ingress when deployed on k3s/k3d.
=> feat: example for k3s/k3d using the built in ingress controller

controllers/reconcilers/grafana/ingress_reconciler.go, examples/openshift/README.md, examples/openshift/resources.yaml
This makes the behaviour of routes similar to that of Ingress. An empty route spec in the CR is enough to trigger the creation of the route.
=> feat: do not create route until spec is provided

controllers/dashboard_controller.go
Grafana uses case-insensitive names for folders, so we should ignore case differences in dashboard controller.
NOTE: We had a similar fix for v4 a while ago: https://github.com/grafana-operator/grafana-operator/pull/830
=> fix: ignore folder title case in dashboard controller

controllers/controller_shared.go
This PR should prevent operator from crashing due to nil dereference when CRs are created without label selectors.
=> fix: crash due to nil labelSelector

controllers/dashboard_controller.go, controllers/datasource_controller.go, controllers/grafana_controller.go, controllers/grafanafolder_controller.go, controllers/reconcilers/grafana/complete_reconciler.go, controllers/reconcilers/grafana/deployment_reconciler.go, controllers/reconcilers/grafana/ingress_reconciler.go, controllers/reconcilers/grafana/plugins_reconciler.go, controllers/reconcilers/grafana/pvc_reconciler.go, main.go
Adds the reconciler log name to the log line.
Closes #1032
=> Add name to reconciler logs.

controllers/reconcilers/grafana/deployment_reconciler.go
Sets `TMPDIR` env var to `/var/lib/grafana` as the default location where temporary files can be written, e.g. plugin downloads.
Fixes issue https://github.com/grafana-operator/grafana-operator/issues/1034
=> fix: plugin installation due to read-only file system error

main.go
The following error is shown when starting the operator without specifying `WATCH_NAMESPACE`
```
1.683727162524107e+09	ERROR	setup	unable to get watch namespace, operator running in cluster scoped mode	{"error": "WATCH_NAMESPACE isn't set"}
main.main
/Users/jbriones/projects/github/grafana-operator/grafana-operator/main.go:96
runtime.main
/Users/jbriones/.gvm/gos/go1.19.5/src/runtime/proc.go:250
1.6837271625242188e+09	INFO	setup	operator running in cluster scoped mode
```
An error should not be shown in the logs if this is undefined as this is an optional env var. If the value of this env var is an empty string or undefined, the following info log will be shown instead:
```
operator running in cluster scoped mode
```
=> fix: error returned when WATCH_NAMESPACE is not defined

controllers/dashboard_controller.go
In #1027, dashboard exists method was not updated to use correct uid. As a result, the operator will never stop reconciling dashboards with hardcoded uids creating a loop:
- the operator creates a dashboard and updates CR status with correct uid;
- since CR is updated, the operator receives an update via WATCH. That's where it was supposed to stop by checking that dashboard exists, hash is the same, and periodic resync timeout hasn't elapsed. Though, since `uid` is taken from CR instead of the dashboard, the operator would think the dashboard does not yet exist in grafana, so it reuploads it and updates `lastResync` in CR status;
- CR status update triggers another reconciliation, and so on.
Fixes: #1045
=> fix: incorrect uid in dashboard exists method

api/v1beta1/grafanafolder_types.go, api/v1beta1/grafanafolder_types_test.go, bundle/manifests/grafana.integreatly.org_grafanafolders.yaml, config/crd/bases/grafana.integreatly.org_grafanafolders.yaml, config/grafana.integreatly.org_grafanafolders.yaml, controllers/grafanafolder_controller.go, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanafolders.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md
Several improvements for folder controller:
- I think there isn't much need in offering raw json for folders. - Their API is very limited ([docs](https://grafana.com/docs/grafana/latest/developers/http_api/folder/#create-folder)), we can simplify operator's code (no need to care about errors in json + no need to decode it) and UX a bit by exposing custom `title` in a separate field.
- Requeue folder sync in case of errors;
- Reorganize `onFolderCreated` a bit to make room for further introduction of permissions (those will be in json);
- Replace folder `uid` if needed (e.g. folder was created outside of operator or through dashboard controller => exists with different uid).
=> Simplify folder controller schema, change folder uid if needed

deploy/cluster_roles/README.md, deploy/cluster_roles/cluster_role_grafana_operator_namespace_selector.yaml
Fixes https://github.com/grafana-operator/grafana-operator/issues/1010.
In order to dashboardNamespaceSelector the ServiceOperator needs to be able to read namespace resources.
This documents that requirement.
=> Document need for access to namespaces with dashboardNamespaceSelector

api/v1beta1/grafanafolder_types.go, bundle/manifests/grafana.integreatly.org_grafanafolders.yaml, config/crd/bases/grafana.integreatly.org_grafanafolders.yaml, config/grafana.integreatly.org_grafanafolders.yaml, controllers/grafanafolder_controller.go, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanafolders.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md, docs/docs/folder.md, examples/folder/README.md, examples/folder/resources.yaml
Added support for raw folder permissions (JSON).
If we ever add support for teams, we can implement something more complex.
=> feat: add support for raw folder permissions

controllers/client/round_tripper.go
While troubleshooting #1040, I played with pprof and also looked at operator's metrics.
In a lab with 1 grafana instance and 27 dashboards (inline `json`, `resyncPeriod: 30s`), all `inuse_space` entries of pprof showed adequate memory consumption while metrics-server data was showing a constant increase in overall memory consumption. And it was interesting that both operator and grafana instances were affected at the same time.
I noticed that `go_goroutines` metric was increasing over time going to thousands, which didn't look right.
`goroutine` section of pprof showed that those thousands of goroutines were coming from http connections:
Then I found that we have a custom `Transport` for grafana client which was added to instrument http status metrics, and that implementation did not …
=> fix: goroutine leak in grafana client #1040

controllers/model/grafanaAlertService.go
Removes the application of the Grafana service annotations to the Grafana alert service annotations.
Fixes #1050.
=> Remove Grafana Alert Service Annotations

docs/blog/kustomize-installation.md, docs/blog/v5-getting-started.md, docs/docs/installation/kustomize.md, hugo/config.toml
See: https://gohugo.io/content-management/shortcodes/#param
=> doc: Use a Hugo shortcode for displaying the version from a param

PREPARE_RELEASE.md, deploy/helm/grafana-operator/Chart.yaml, deploy/helm/grafana-operator/README.md, deploy/helm/grafana-operator/README.md.gotmpl
This allows version to be properly generated in `deploy/helm/grafana-operator/README.md` using https://github.com/norwoodj/helm-docs/tree/master/cmd/helm-docs
=> doc: Set the version in helm README based in Chart.yaml

controllers/dashboard_controller.go
When `id` is hardcoded in a `GrafanaDashboard`, the operator is likely to fail to create the dashboard in a Grafana instance.
The PR makes sure `id` is nullified before dashboard model is passed to Grafana client.
(Strictly speaking, `id` should never be defined by a user in the first place, so it's more around improving UX.) 
Basically, when `id` is set, Grafana tries to update a dashboard by the `id`, not `uid`. And, expectedly, that can cause various issues, e.g. if the `id` is missing, Grafana responds with 404.
```yaml
kind: GrafanaDashboard
metadata:
name: grafanadashboard-sample
spec:
resyncPeriod: 30s
instanceSelector:
matchLabels:
dashboards: "grafana"
json: >
{
"id": 146,
"title": "Simple Dashboard",
"tags": [],
"style": "dark", …
```
=> feat(dashboard): nullify hardcoded id

.github/workflows/e2e.yaml, .github/workflows/release-github.yaml, .github/workflows/stale.yml
- `release-github`:
- Bump `ko` to `v0.14.1`, which should potentially make our builds [faster](https://github.com/ko-build/ko/pull/1005);
- Remove `--insecure-registry` `ko` flag. We added it early on as a workaround when there was a typo in ghcr name (=> certificate wasn't valid);
- `stale`:
- Since `actions/stale` operates in dates, I think there isn't much value in running the workflow every hour. - Once a day should be enough;
- `e2e`:
- Remove `docker/setup-buildx-action` step, because it's not needed for `ko`.
=> chore: minor changes in workflows

deploy/helm/grafana-operator/README.md, deploy/helm/grafana-operator/templates/cm.yaml, deploy/helm/grafana-operator/templates/deployment.yaml, deploy/helm/grafana-operator/templates/rbac-clusterscope.yaml, deploy/helm/grafana-operator/templates/rbac-namespace.yaml, deploy/helm/grafana-operator/templates/service.yaml, deploy/helm/grafana-operator/templates/serviceaccount.yaml, deploy/helm/grafana-operator/values.yaml
This allows us to set extra labels, which is useful to add extra information to resources.
=> feat: [helm] set additional labels

.github/workflows/e2e.yaml, CONTRIBUTING.md, Makefile, hack/kind/resources/cluster.yaml, hack/kind/resources/crd-ns/grafana-dashboard.yaml, hack/kind/resources/crd-ns/grafana-datasource.yaml, hack/kind/resources/crd-ns/kustomization.yaml, hack/kind/resources/default/grafana-dashboard.yaml, hack/kind/resources/default/grafana-datasource.yaml, hack/kind/resources/default/grafana.yaml, hack/kind/resources/default/kustomization.yaml, hack/kind/start-kind.sh
Closes #1052 
A script for starting kind from Makefile, to be used during development.
=> Add script for starting kind for local development.

controllers/config/grafana_ini.go
limit dashboard versions to 20 if not otherwise specified
=> fix: limit dashboard versions to 20 if not otherwise specified

controllers/datasource_controller.go, examples/datasource_variables/README.md, examples/datasource_variables/resources.yaml
This PR extends the existing functionality to inject values from Secrets into data sources. It allows replacement patterns (e.g. `Bearer ${TOKEN}`) instead of overwriting whatever is there in the first place.
Injecting bearer tokens is a typical use case for data sources. However this was not properly supported until now. The value of a bearer token starts with `Bearer` followed by the token. The existing mechanism replaced the whole value, including the `Bearer` part. You would have to include `Bearer` in the secret, but often you don't create or manage those secrets.
Bevor overwriting the value found at the given path, we fetch it and apply the replacement.
=> feat: allow replacement pattern in data sources

api/v1beta1/grafanadashboard_types.go, config/crd/bases/grafana.integreatly.org_grafanadashboards.yaml, config/grafana.integreatly.org_grafanadashboards.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanadashboards.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md
Fixes a wrong symbol used for tag splitting, this caused the field to be assigned the name of `value:omitempty`, rather than what the intent was, to assign the name `value` and add an omitempty call in the json tag.
=> fix secretkeyref omitempty wrong symbol causing invalid crd field generation

config/rbac/role.yaml, controllers/grafana_controller.go, deploy/helm/grafana-operator/templates/rbac-clusterscope.yaml, deploy/helm/grafana-operator/templates/rbac-namespace.yaml, deploy/kustomize/overlays/cluster_scoped/rbac.yaml, deploy/kustomize/overlays/namespace_scoped/rbac.yaml
Fix for #1197 - add RBAC permission to route sub-resource on OCP.
=> add back subresource on OCP for custom hostname

bundle/manifests/grafana-operator.clusterserviceversion.yaml, config/manager/manager.yaml, deploy/kustomize/base/deployment.yaml
OOM killed is encountered when running the operator on OpenShift environment. 
extending memory limits to 256Mi
=> extended operator resource memory limit

CONTRIBUTING.md, hugo/Makefile, hugo/README.md
=> Add target for detecting broken links in documentation

docs/docs/folder.md
Add new section in the GrafanaFolder documentation on how to resolve conflicts due to folder name changes.
Resolves https://github.com/grafana-operator/grafana-operator/issues/1171
=> docs: document how to resolve grafana folder conflicts due to name change

controllers/dashboard_controller.go
=> don't requeue if dashboard CR are broken

bundle/manifests/grafana-operator.clusterserviceversion.yaml, config/manager/manager.yaml, deploy/kustomize/base/deployment.yaml
On OpenShift with 22 dashboards, the manager pod peaks around 465Mi at startup and then goes down to 250-270Mi. Increase the limit otherwise pod is dies with OOMKilled error.
Increase all 3 types of deployment for consistency reasons even though the referenced issue was for OLM.
Fixes #1255
=> Increase grafana-operator-controller-manager memory limit

.github/workflows/release.yaml
Add operator release mirroring to quay
Tested on my own fork against my own quay repository: https://github.com/HubertStefanski/grafana-operator/actions/runs/6532690631/job/17736608088  (Not sure if this is visible)
During my testing the process works, but fails on authentication, although that's expected as my quay username is `hstefans` while my GH username is `HubertStefanski` and the workflow assumes that the organization and repository name is the same on Quay as it is for GHCR. This however won't be a problem for the operator, as https://quay.io/repository/grafana-operator/grafana-operator is an organization we own and matches the same naming convention as GHCR i,e `<host>/<org>/<project>:tag`
=> extend release workflow to push to quay

controllers/client/grafana_client.go, controllers/client/round_tripper.go, controllers/fetchers/grafana_com_fetcher.go, controllers/fetchers/url_fetcher.go, docs/docs/_index.md
As highlighted in #1295, it's not always easy to properly set `NO_PROXY` env to make sure requests to internal Grafana instances are not proxied.
Seems like it would make the most sense if we respect proxy settings only for external Grafana instances and for URL-based dashboards. Thus the PR.
Fixes: #1295
=> fix(proxy): don't use proxy for internal Grafana instances

controllers/client/round_tripper.go
That should fix nil deference for tls transport that was accidentaly introduced in #1300
=> fix(client): tls transport nil dereference

Makefile, deploy/helm/grafana-operator/Chart.yaml, deploy/helm/grafana-operator/README.md, hugo/config.toml
This is the first PR with the new release flow. We do not commit any changes made for OLM, those will instead be generated locally and pushed to the OLM upstream repos directly.
This is to be able to generate image digests to support disconnected mode.
=> prepare 5.5.0

config/manifests/bases/grafana-operator.clusterserviceversion.yaml
The current OLM instructions points that we should update `annotations.containerImage` but this resource currently doesn't exist.
It's needed for `make bundle/redhat` to be able to automatically generate the SHAs for OLM to work in disconnected mode. Without it, the upstream operator PRs don't pass basic tests.
=> re-add containerImage to config manifests

deploy/helm/grafana-operator/README.md, deploy/helm/grafana-operator/templates/deployment.yaml, deploy/helm/grafana-operator/values.yaml
Fixes #1315, introduced in 3166d43.
Should be noted, that the current v5.5.0 helm chart is completely broken because of this. So a patch release might be necessary :)
=> helm chart: fix broken default values

.github/workflows/pr-validation.yaml
As a part of a PR let's verify that the helm chart at least is possible to render the helm template command.
In the future we can add extra install steps to verify that it's possible to install and run some tests as well.
=> Run helm template as a basic check of the helm chart

docs/blog/operator-migration-to-upstream-grafana.md
Adding a new blogpost for the upcoming migration to the upstream Grafana organization
=> blog post entry for upcoming operator repo migration to upstream grafana

controllers/reconcilers/grafana/deployment_reconciler.go, controllers/reconcilers/grafana/deployment_reconciler_test.go
1. Perform a basic helm deployment (flux in my case) of the grafana-operater. 
2. Create a sample `Grafana` and `GrafanaDashboard` resource. 
The resultant `Deployment` artifact produces the following error:
```
Warning  InspectFailed  9s (x11 over 2m7s)  kubelet            Failed to apply default image tag "docker.io/grafana/grafana@9.1.6": couldn't parse image reference "docker.io/grafana/grafana@9.1.6": invalid reference format
Warning  Failed         9s (x11 over 2m7s)  kubelet            Error: InvalidImageName
```
After some checking, I found the cause related to a recent change made to the `deployment_reconciler.go` file. The issue seemed straightforward enough, so I made the fix and added some tests.
I have never done go before, so please accept my apologies if I made any …
=> fix(deployment reconciler): Couldn't parse image reference "docker.io/grafana/grafana@9.1.6"

deploy/helm/grafana-operator/Chart.yaml, deploy/helm/grafana-operator/README.md, deploy/helm/grafana-operator/templates/cm.yaml, deploy/helm/grafana-operator/templates/deployment.yaml, deploy/helm/grafana-operator/templates/rbac.yaml, deploy/helm/grafana-operator/templates/service.yaml, deploy/helm/grafana-operator/templates/serviceaccount.yaml
Adding namespaces to templates in order to avoid having objects deployed to the `default` namespace in certain deployment scenarios.
=> Add namespace to templates

controllers/fetchers/jsonnet_fetcher.go
I've noticed across multiple builds (e.g. [here](https://github.com/grafana/grafana-operator/actions/runs/7166202293/job/19509711911?pr=1341#step:4:109)) that we have a flaky test called `TestGetJsonProjectBuildRoundName`.
Basically, there is function `getJsonProjectBuildRoundName` that is supposed to return a 3-segment string (separated by hyphens) that consists of a dashboard name, a timestamp, and a random string. Sometimes, the latter contains a hyphen, which breaks the expected pattern in `TestGetJsonProjectBuildRoundName`.
It can be fixed in various ways, but I think a simple replace of `-` to something else (`a` in the PR) should be enough.
=> fix(jsonnet): flaky test TestGetJsonProjectBuildRoundName

bundle/manifests/grafana-operator.clusterserviceversion.yaml, config/samples/grafana_v1beta1_grafanafolder.yaml
The example values for a CR are used when creating a new instance of that CR in the OpenShift web-console. The example attribute `json:` is not valid for a `GrafanaFolder`. This Pull Request updates the example to set a custom title using the `title:` attribute.
=> Update GrafanaFolder example syntax

deploy/helm/grafana-operator/README.md, deploy/helm/grafana-operator/templates/rbac.yaml, deploy/helm/grafana-operator/values.yaml
Fixes #1331 
This removes all OpenShift related permissions (routes) from the Helm chart. I've verified that the Helm chart can still be deployed on OpenShift.
=> remove permissions for openshift only resources in helm chart

.github/workflows/release.yaml, docs/docs/security.md
* remake for loop and put it in prepare
* update ko to 0.15.1
* add document on how to verify image
=> spdx sbom for grafana-operator and sign image

examples/ldap/README.md, examples/ldap/resources.yaml
https://github.com/grafana/grafana-operator/issues/1369
=> Create ldap configmap example

deploy/helm/grafana-operator/templates/rbac.yaml, deploy/kustomize/overlays/cluster_scoped/rbac.yaml, deploy/kustomize/overlays/namespace_scoped/rbac.yaml
As discussed under #1330, `tokenreviews` and `subjectaccessreviews` are unused by the operator, so should be removed from our manifests.
Fixes: #1330
=> fix: remove unused permissions (tokenreviews, subjectaccessreviews)

Makefile, bundle/manifests/grafana-operator.clusterserviceversion.yaml, deploy/helm/grafana-operator/Chart.yaml, deploy/helm/grafana-operator/README.md, hugo/config.toml
This is a horrible PR, it's all about fixing OLM to skip 5.6.1 release.
OLM don't support patch versions in semver https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4002
To lazy to do 2 PRs for this.
=> cut 5.6.3 and fix OLM

bundle/manifests/grafana-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/grafana-operator.clusterserviceversion.yaml
I changed in the wrong location in https://github.com/grafana/grafana-operator/pull/1405
This is now corrected. I will still use 5.6.3 when fixing the OLM stuff, but it's good that it's correct for the future.
=> OLM add skips in correct location

.chainsaw.yaml, tests/e2e/example-test/00-assert.yaml, tests/e2e/example-test/chainsaw-test.yaml
Do not hardcode namespace used in e2e tests.
=> fix: do not hardcode namespace used in e2e tests

.github/workflows/e2e.yaml
Install chainsaw with GH action.
=> chore: install chainsaw with GH action

examples/persistent_volume/resources.yaml
This PR fixes our persistent volume example - indentation was a bit off.
Also, I commented out `storageClassName`. - In most environments, there would be a default storage class, so we don't necessarily need to override it => easier to deploy the example as is.
Fixes: #1418
=> fix: persistent volume example

.github/dependabot.yml
This to only get one PR from dependabot instead of n.
You can read more about groups in https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file.
=> use dependabot group feature

.chainsaw.yaml, controllers/dashboard_controller.go, tests/e2e/example-test/05-dashboard.yaml
Fixes a nil pointer exception caused by the logic attempting to parse SecretKeyRefs even if ConfigMapKeyRefs were declared in the `dashboard.Spec.EnvFrom`
Additionally, fix the ` envFrom:   - configMapKeyRef` case in e2e tests
=> fix nil pointer exception in jsonnet logic

controllers/dashboard_controller.go
This PR is a partial implementation of #1357. It only concerns itself with the dashboard controller to set the stage for other controllers to follow suit.
Tested normal use cases with a local instance & Grafana Cloud but would appreciate some more edge use cases to explore
=> refactor: use openapi client for dashboard controller

controllers/grafanafolder_controller.go
Partial implementation of #1357 only concerning folders
=> refactor: use openapi client for folder controller

controllers/client/grafana_client.go
Time multiplier was only applied when no timeout was provided.
=> fix: time multiplier was not applied if the timeout was in the spec

docs/docs/_index.md, docs/docs/alerting.md, docs/docs/api.md, docs/docs/overview.md, docs/docs/quick-start.md, hugo/templates/frontmatter-grafana-operator.tmpl
I've restructured the documentation a bit and added more alerting docs.
We might want to think about getting the documentation published under grafana.com/docs for consistency & discoverability :eyes:
=> docs: restructure documentation

controllers/client/grafana_client.go, go.mod, go.sum
now that all resources use the new client, we can safely remove the dependency
Closes: #1357
=> refactor: remove old client

deploy/helm/grafana-operator/Chart.yaml, deploy/helm/grafana-operator/README.md, deploy/helm/grafana-operator/README.md.gotmpl
Adds a section for upgrading helm with regards to CRDs
=> docs: add helm upgrade instructions

examples/crossnamespace/README.md
Inspired by https://github.com/grafana/grafana-operator/issues/1142.
=> Updated crossnamespace to mention that dashboards need spec.allowCrossNamespaceImport as well

hack/kind/resources/default/deployment-thanos.yaml, hack/kind/resources/default/grafana-datasource-thanos.yaml, hack/kind/resources/default/kustomization.yaml, hack/kind/resources/default/secret.yaml, hack/kind/resources/default/serviceaccount.yaml
This PR adds test files in kind for verifying the existence of Authorization header with GrafanaDatasources with secureJsonData.
=> chore: add test files for secure json data in kind

controllers/datasource_controller.go
This addresses a bug introduced in the changeover to using the openapi Grafana library where the secureJsonData field was being dropped.
To address this it's necessary to use the `UpdateDataSourceCommand` struct to ensure we're also not dropping the version if it's present.
This is a bit counter-intuitive to use the `Update` struct here and perhaps worth looking at another solution at some point.
Thanks to @mdelaney committed for the initial PR https://github.com/grafana/grafana-operator/pull/1488
=> bugfix - datasource controller was dropping secureJsonData

controllers/dashboard_controller.go
fixes #1498 
When a dashboard is not found, we should not try to delete it.
=> fix: do not delete non-existing dashboard

Makefile, config/grafana.integreatly.org_grafanaalertrulegroups.yaml, config/grafana.integreatly.org_grafanacontactpoints.yaml, config/grafana.integreatly.org_grafanadashboards.yaml, config/grafana.integreatly.org_grafanadatasources.yaml, config/grafana.integreatly.org_grafanafolders.yaml, config/grafana.integreatly.org_grafanas.yaml, config/kustomization.yaml, docs/docs/api.md
This PR supplements #1483.
It resolves two issues around documentation:
- In Makefile, we didn't have a step to regenerate CRDs that are stored in `config/`. Thus, documentation (`api-docs`) did not reflect the latest changes;
- kustomization.yaml in `config/` did not contain a reference to `grafana.integreatly.org_grafanacontactpoints.yaml`, thus it was not included in documentation.
**NOTE:** PR is split into 3 commits to distinguish "human-made" changes from autogenerated files.
=> fix(api-docs): generate CRDs for api-docs and add missing reference to grafanacontactpoints

.github/workflows/pr-validation.yaml, .golangci.yaml
`golangci-lint` has a built-in functionality to validate its config for presence of deprecated options. This PR adds a verification step. [Example](https://github.com/grafana/grafana-operator/actions/runs/8957833010/job/24601360787?pr=1518):
**Additional changes:**
- bump version to `v1.57.2`;
- remove deprecated options (**NOTE**: we no longer need to pin certain linters to specific go versions, it's all detected automatically through `go.mod`).
=> chore(workflows): verify golangci-lint config

.github/release.yml
Release note of grafana-operator seems to be generated by GitHub's auto-generation feature.
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
It is hard for us to read large number of changes that may contains important changes.
Special attention should be paid when important changes are mixed in with the large number of dependency change logs.
Fortunately, the PRs automatically generated by dependabot are labeled `dependencies`. This could be used to categorize the list of changes in the release notes to reduce the burden on the user.
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options
The release notes should now appear as follows:
```md
- chore: some …
```
=> chore: categorize dependency updates and other changes in auto-generated release notes

controllers/grafana_controller.go
This fixes an issue when the external instance is first reconciled as the status is not yet set when fetching the version
=> fix: use the external url for fetching version if set

controllers/grafanafolder_controller.go
Two fixes for `grafanafolder` controller:
- Previously, `onFolderDeleted` would treat a missing folder (e.g. deleted through Grafana UI) as an error, which should have never been the case. - We just overlooked a missing `!` in error handling logic;
- When cleaning up status for CRs that had been deleted, `syncFolders` was supposed to check if a folder still exists in Grafana, but instead of using method for folders, it used one for dashboards.
Two manual test cases to verify the fix:
- `onFolderDeleted`:
- Steps:
- deploy `GrafanaFolder` CR (e.g. from `examples/folder`);
- `Grafana` CR should contain a reference to the folder in `status.folders`;
- remove the folder from UI;
- remove the folder CR;
- Expected results:
- No errors;
- No event requeues;
- `Grafana` CR should no longer …
=> fix(GrafanaFolder): proper status updates for removed CRs, don't fail on missing folder in onFolderDeleted events 

.golangci.yaml, controllers/dashboard_controller.go
In #1504, we introduced a minor regression:
If a dashboard is deleted outside of the operator (e.g. through Grafana UI), then the operator skips Plugin and Status reconciliations. This PR should fix that.
Manual test case:
- Steps:
- deploy `GrafanaDashboard` CR (e.g. from `examples/basic`);
- `Grafana` CR should contain a reference to the dashboard in `status.dashboards`;
- remove the dashboard from UI;
- remove the dashboard CR;
- Expected results:
- No errors / panics;
- `Grafana` CR should no longer contain a reference to the dashboard in `status.dashboards`.
=> fix(GrafanaDashboard): properly finish reconciliation in onDashboardDeleted when dashboard is missing

api/v1beta1/grafanaalertrulegroup_types.go, api/v1beta1/grafanacontactpoint_types.go, api/v1beta1/grafanadashboard_types.go, api/v1beta1/grafanadatasource_types.go, api/v1beta1/grafanafolder_types.go, bundle/manifests/grafana-operator.clusterserviceversion.yaml, bundle/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml, bundle/manifests/grafana.integreatly.org_grafanacontactpoints.yaml, bundle/manifests/grafana.integreatly.org_grafanadashboards.yaml, bundle/manifests/grafana.integreatly.org_grafanadatasources.yaml, bundle/manifests/grafana.integreatly.org_grafanafolders.yaml, config/crd/bases/grafana.integreatly.org_grafanaalertrulegroups.yaml, config/crd/bases/grafana.integreatly.org_grafanacontactpoints.yaml, config/crd/bases/grafana.integreatly.org_grafanadashboards.yaml, config/crd/bases/grafana.integreatly.org_grafanadatasources.yaml, config/crd/bases/grafana.integreatly.org_grafanafolders.yaml, config/grafana.integreatly.org_grafanaalertrulegroups.yaml, config/grafana.integreatly.org_grafanacontactpoints.yaml, config/grafana.integreatly.org_grafanadashboards.yaml, config/grafana.integreatly.org_grafanadatasources.yaml, config/grafana.integreatly.org_grafanafolders.yaml, deploy/helm/grafana-operator/Chart.yaml, deploy/helm/grafana-operator/README.md, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanaalertrulegroups.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanacontactpoints.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanadashboards.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanadatasources.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanafolders.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md
As previously discussed, `instanceSelector` field must be made immutable to make sure we don't end up having abandoned resources and to be in line with k8s eco-system. The PR contains the required changes. 
Fixes: #1519
=> feat(controllers): make instanceSelector immutable 

.github/ISSUE_TEMPLATE/bug_report.md
We often have to clarify this in open issues, so we want to ask this information up front
=> docs: clarify deployment type in issue template

api/v1beta1/grafanaalertrulegroup_types.go, config/crd/bases/grafana.integreatly.org_grafanaalertrulegroups.yaml, config/grafana.integreatly.org_grafanaalertrulegroups.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanaalertrulegroups.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md
=> feat: add KeepLast as valid value for no data & exec err state

api/v1beta1/grafanacontactpoint_types.go, bundle/manifests/grafana.integreatly.org_grafanacontactpoints.yaml, config/crd-for-docs-generation/grafana.integreatly.org_grafanacontactpoints.yaml, config/crd/bases/grafana.integreatly.org_grafanacontactpoints.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanacontactpoints.yaml, docs/docs/api.md
Closes https://github.com/grafana/grafana-operator/issues/1548
Just added new items in list from
https://grafana.com/docs/grafana/latest/alerting/configure-notifications/manage-contact-points/
Basically, we have to keep backward compitability for old grafana versions and include new types. The users have to choose types in accordance with grafana version they use.
Tested manually:
<details>
<summary>Manifest</summary>
```
sources:
- repoURL: https://github.com/andrejshapal/grafana-operator.git
targetRevision: master
path: deploy/helm/grafana-operator
helm:
values: |
fullnameOverride: "grafana-operator"
namespaceScope: true
image:
repository: njuhaandrej/grafana-operator
pullPolicy: Always
tag: 8d1372eb04c3804416f724d98967bdb931ad026de458510f787866d818655757
resources:
limits:
cpu: 100m …
```
=> Adding Grafana v10 ContactPoint types

deploy/helm/grafana-operator/README.md, deploy/helm/grafana-operator/README.md.gotmpl
Came up in our community slack, so adding this to our docs
=> docs: add instructions for terraform installation

config/manager/manager.yaml, controllers/config/operator_constants.go, tests/e2e/example-test/00-assert.yaml, tests/e2e/example-test/00-create-versioned-grafana.yaml
Since we now store the version information in the spec, this will not affect existing resources
=> chore: update default grafana version

Makefile, deploy/kustomize/base/crds.yaml, deploy/kustomize/base/kustomization.yaml, deploy/kustomize/base/role.yaml
When Flux publishes an artifact to OCI, it's just a copy of a folder structure. Thus, `kustomization.yaml` cannot reference files that reside outside of `deploy/kustomize`.
To workaround that, unfortunately, we need to maintain an additional copy of CRDs and the `ClusterRole`. 
Fixes: #1561
=> fix(flux): maintain a copy of CRDs and the ClusterRole in deploy/kustomize/base

Makefile, deploy/helm/grafana-operator/Chart.yaml, deploy/helm/grafana-operator/README.md, hugo/config.toml
Preparing for new release to re-run release pipelines, fixing #1561
=> chore: bump version to 5.9.2 in prep for new release

deploy/helm/grafana-operator/Chart.yaml, deploy/helm/grafana-operator/templates/_helpers.tpl, deploy/helm/grafana-operator/templates/cm.yaml, deploy/helm/grafana-operator/templates/deployment.yaml, deploy/helm/grafana-operator/templates/rbac.yaml, deploy/helm/grafana-operator/templates/service.yaml, deploy/helm/grafana-operator/templates/serviceaccount.yaml, deploy/helm/grafana-operator/templates/servicemonitor.yaml
Add missing labels and refactoring additional labels.
I don't change Helm chart version, because it is `v0.1.4` but in [documentation](https://github.com/grafana/grafana-operator/tree/master/deploy/helm/grafana-operator#installation), it is `v5.9.0`:
```
helm upgrade -i grafana-operator oci://ghcr.io/grafana/helm-charts/grafana-operator --version v5.9.0
```
=> feat(helm): All recommended Kubernetes labels

CODEOWNERS
@HVBE has changed his handle a few weeks back, though we haven't updated `CODEOWNERS` yet.
That what the PR is for.
@theSuess Shall we just create a team in the Grafana org for our needs?
*(Upd):* Ah, forgot that most of the maintainers are not part of the org, so nevermind :)
=> chore(codeowners): fix handle for HVBE

controllers/model/dashboard_resources.go, controllers/model/grafana_resources.go
This fixes #1573. Without the controller reference, the owner reference only affects resource deletion.
While this causes faster reconciliation, it should not break any setup as the reconciliation would have happened anyway whenever the manager pod restarts
=> fix: use controller reference instead of owner reference

README.md
CHANGELOG:
- Fix auth.disable_login_form in the example in README.md
When we test the example of the README, it fails : 
`$ kubectl apply -f grafana.yaml
The Grafana "grafana" is invalid: spec.config.auth.disable_login_form: Invalid value: "boolean": spec.config.auth.disable_login_form in body must be of type string: "boolean"`
=> docs: Fix parameter auth.disable_login_form type in README.md

controllers/controller_shared.go, controllers/grafanaalertrulegroup_controller.go
=> fix: use correct error propagation logic in alert rule group handler

controllers/grafanafolder_controller.go
Currently grafanafolder controller tries to update folder permission using CR UID no matter if the folder was created by dashboard controller earlier.
=> fix: use correct folder uid to update permissions

docs/docs/proposals/005-grafanadashboard-folder-management-strategy-update.md
This MR aims to create a document to propose an evolution on the folder management related to the parent folder. 
The suggested new features are:
- Use a `folderRef` field to target a folder deployed thanks to the GrafanaFolder CR.
- Use a `folderUID` field to target an existing folder in Grafana.
- Enable or disable folder creation from GrafanaDashboard by adding a field `createFolder` (default: true for retrocompatibility). This field cannot be false if `folderUID` and `folderRef` are not set in the GrafanaDashboard manifest.
There is no breaking change because it is just a proposal document. Nothing is implemented yet.
This should be discussed during a maintainer meeting.
=> docs: add proposal for grafana dashboard parent folder management

CONTRIBUTING.md, deploy/helm/grafana-operator/README.md, deploy/helm/grafana-operator/templates/extraobjects.yaml, deploy/helm/grafana-operator/values.yaml
Sometimes additional objects are needed, such as  ExternalSecret for Grafana api token, (Cilium) Network policies etc.
=> HELM: Enable deploying additional objects with helm chart

api/folderreferencer.go, api/v1beta1/folderreferencer.go, api/v1beta1/grafanaalertrulegroup_types.go, api/v1beta1/grafanafolder_types.go, config/crd/bases/grafana.integreatly.org_grafanafolders.yaml, controllers/controller_shared.go, controllers/grafanaalertrulegroup_controller.go, controllers/grafanafolder_controller.go, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanafolders.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md
Implement the parentFolderRef functionality in the GrafanaFolder CRD.
There is no breaking change in this MR
* [Design document: GrafanaFolder parent folder management](https://grafana.github.io/grafana-operator/docs/proposals/004-grafanafolder-parent-folder-management/#proposal-2-target-an-existing-grafanafolder-deployed-by-the-grafana-operator)
I have made few tests on moving the folder with dashboard inside by changing the parentFolderRef/parentFolderUID. I have adapted the implementation based on #1600 changes.
=> feat: add parentFolderRef field in GrafanaFolder

docs/docs/proposals/006-ssl-specification-in-grafanaexternal.md
This MR aims to create a document to propose an evolution on the Grafana CR to permits to give certificate to the Grafana external block.
There is no breaking change because it is just a proposal document. Nothing is implemented yet.
This should be discussed during a maintainer meeting.
=> docs: Add proposal for ssl specification in Grafana external block

api/v1beta1/grafanafolder_types.go, config/crd/bases/grafana.integreatly.org_grafanafolders.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanafolders.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md
=> fix: remove required attribute from folder conditions

controllers/grafanaalertrulegroup_controller.go
reduces time to creation if folder & group are applied simultaneously
=> fix: requeue on apply errors

bundle/manifests/grafana-operator-operator-metrics-service_v1_service.yaml, config/default/metrics_service.yaml, config/manager/manager.yaml, deploy/helm/grafana-operator/README.md, deploy/helm/grafana-operator/templates/deployment.yaml, deploy/helm/grafana-operator/templates/service.yaml, deploy/helm/grafana-operator/values.yaml, deploy/kustomize/base/deployment.yaml, deploy/kustomize/base/service.yaml, main.go
Should help when debugging #1622
=> feat: enable pprof endpoint

deploy/helm/grafana-operator/Chart.yaml, deploy/helm/grafana-operator/README.md, deploy/helm/grafana-operator/templates/rbac.yaml, deploy/helm/grafana-operator/values.yaml
Enable or disable ClusterRole and RoleBinding creation and add the ability to custom the ClusterRole rules
Enabling the user to use existing ClusterRole and ClusterRoleBinding. The use case for us is to allow users to use this chart in clusters where creating such objetcs is not allowed by helm deployment but must go throught something else (eg Terraform).
Also, it's adding the ability to customise the rules, as not all of them are required for the operator to work.
None - this just adds a new feature
Tested by hand, by trying different values in `values.yaml`
```sh
cd deploy/helm/grafana-operator
helm dependency build
helm template . --output-dir /tmp/grafana-operator
```
Test case with no creation of roles:
```yaml
[...]
rbac:
create: false
rules:
- apiGroups:
- ""
resources:
- …
```
=> feat(helm): add option to disable rbac creation

Makefile
I was attempting to generate some CRD changes and I was unable to use the Makefile provided `yq` binary.
```bash
> git rev-parse HEAD
26fc2cb328892dda47b2af970882bfd049c06543
> make yq
awk: cmd. line:1: {print tolower()}
awk: cmd. line:1:                ^ 0 is invalid as number of arguments for tolower
> ./bin/yq --version
./bin/yq: 1: Not: not found
> ls -al ./bin/
-rwxr-xr-x  1 ste ste  22M Aug 12 20:58 controller-gen
-rwxr-xr-x  1 ste ste  15M Aug 12 20:43 kustomize
-rwxr-xr-x  1 ste ste 9.1M Aug 12 20:45 setup-envtest
-rwxr-xr-x  1 ste ste    9 Aug 12 21:42 yq
```
And the `manifests` target did not reference the YQ variable properly and instead relied on PATH
```bash
> make manifests
test -s /home/ste/grafana-operator/bin/controller-gen || GOBIN=/home/ste/grafana-operator/bin go …
```
=> Local `yq` is not downloaded or referenced properly in Makefile

deploy/helm/grafana-operator/templates/deployment.yaml
Since #1538 landed, it's not possible to set additional pod labels. The only way of setting pod labels would be to change
`grafana-operator.selectorLabels`, but doing that breaks current deployments as selector labels are immutable.
`grafana-operator.labels` includes `grafana-operator.selectorLabels`, so it's safe to include them instead in the pod labels, and doing so fixes the current issue without causing side-effects as well as restores previous chart behavior.
This is the alternative fix discussed in PR #1560
fixes #1546 #1642
=> fix(helm): allow setting pod labels

api/v1beta1/grafana_types.go, api/v1beta1/grafanaalertrulegroup_types.go, api/v1beta1/grafanacontactpoint_types.go, api/v1beta1/grafanadashboard_types.go, api/v1beta1/grafanadatasource_types.go, api/v1beta1/grafanafolder_types.go, api/v1beta1/grafananotificationpolicy_types.go, config/crd/bases/grafana.integreatly.org_grafanaalertrulegroups.yaml, config/crd/bases/grafana.integreatly.org_grafanacontactpoints.yaml, config/crd/bases/grafana.integreatly.org_grafanadatasources.yaml, config/crd/bases/grafana.integreatly.org_grafanafolders.yaml, config/crd/bases/grafana.integreatly.org_grafananotificationpolicies.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanaalertrulegroups.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanacontactpoints.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanadatasources.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanafolders.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafananotificationpolicies.yaml, deploy/kustomize/base/crds.yaml
Kubernetes CRD definitions support a nifty `categories` field which is a list of strings that can be used for grouping CRs together under umbrella terms.
An example of this is Istio resources all having the category [`istio-io`](https://github.com/istio/istio/blob/master/manifests/charts/base/crds/crd-all.gen.yaml#L17)
Making use of categories allows for a pleasant way of listing all resources in a given scope.
And it is currently necessary to write pretty long commands to get an overview of all `Grafana-Operator` CRs in a cluster:
```sh
kubectl get grafanas,grafanadashboards -A
kubectl get grafanas.grafana.integreatly.org,grafanadashboards.grafana.integreatly.org -A
> NAMESPACE    NAME                                           VERSION   STAGE      STAGE STATUS   AGE
> monitoring …
```
=> Annotate CRD structs with categories

docs/docs/installation/kustomize.md
Document that `kubectl apply ...` will produce the error
```
invalid: metadata.annotations: Too long: must have at most 262144 bytes
```
=> documentation comment about `kubectl apply` error

controllers/model/dashboard_resources.go, controllers/model/grafana_resources.go, controllers/model/utils.go, controllers/reconcilers/grafana/admin_secret_reconciler.go, controllers/reconcilers/grafana/config_reconciler.go, controllers/reconcilers/grafana/deployment_reconciler.go, controllers/reconcilers/grafana/grafana_service_reconciler.go, controllers/reconcilers/grafana/ingress_reconciler.go, controllers/reconcilers/grafana/plugins_reconciler.go, controllers/reconcilers/grafana/pvc_reconciler.go, controllers/reconcilers/grafana/service_account_reconciler.go
First step to reduce memory consumption caused by cached resources.
See https://github.com/grafana/grafana-operator/issues/1622 for more details
=> fix: add common labels to created resources

Makefile, README.md, deploy/helm/grafana-operator/Chart.yaml, deploy/helm/grafana-operator/README.md, deploy/helm/grafana-operator/README.md.gotmpl, hugo/config.toml
Cutting a release before #1666 and #1670 to limit the blast radius if some unexpected changes occur
=> chore: release 5.13.0

api/v1beta1/grafana_types.go, api/v1beta1/grafanadashboard_types.go, config/crd/bases/grafana.integreatly.org_grafanadashboards.yaml, config/crd/bases/grafana.integreatly.org_grafanas.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanadashboards.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanas.yaml, deploy/kustomize/base/crds.yaml
Looks like I was too hasty when I redid my changes for #1650 
Here's a quick fix to ensure GrafanaDashboards and Grafanas also get the `grafana-operator` category
=> Move category annotation to the correct struct in GrafanaDashboard and Grafanas

docs/docs/overview.md
#1682 pointed out a discrepancy between the documentation and observed behavior. This PR addresses the documentation issue
=> docs: add resync period warning

.github/workflows/e2e.yaml, .github/workflows/release.yaml, .ko.yaml, controllers/client/round_tripper.go, embeds/README.md, embeds/grafana_embeds.go, main.go
This adds a user agent which includes the operator version to all requests made by the operator. By doing this, Grafana administrators can better differentiate between requests that originated from humans and those performed by the operator
=> feat: add user agent to requests made by operator

controllers/reconcilers/grafana/grafana_service_reconciler.go
This patch fixes #1712 where the issue is that the url used to connect to a Grafana instance through a Service is incorrectly generated by the reconciler. This causes errors like.
```
Get \"https://grafana-service.grafana:3000/api/folders?limit=1000&page=1\": tls: failed to verify certificate: x509: certificate is valid for grafana-service.grafana.svc, grafana-service.grafana.svc.cluster.local, not grafana-service.grafana
```
=> Adds `.svc` to internal grafana `adminUrl`

Makefile, api/v1beta1/grafanafolder_types.go, api/v1beta1/grafanafolder_types_test.go, config/crd/bases/grafana.integreatly.org_grafanafolders.yaml, controllers/controller_shared.go, controllers/dashboard_controller.go, controllers/grafanafolder_controller.go, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanafolders.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md, hack/kind/start-kind.sh
Disclaimer: I'm not a Go developer in any capacity, feel free to address any issues as I will gladly modify the PR to suit the project.
I took a stab at #1636 and limited it to the GrafanaFolder resource for now, I'm planning a separate PR for both `GrafanaNotificationPolicy` and `GrafanaContactPoint` with almost identical changes once the design in this PR has been approved.
The Makefile changes were mainly due to me trying to figure out how to work with the Operator locally and I found a lot of discrepancies with the `make help` target.
I struggled a fair bit with testing and validating as I'm unfamiliar with the project, hence I spent a lot of time in the Makefile.
For now, I have yet to find an existing way to easily deploy the most recently built ko-image into my local kind cluster, …
=> Implement `spec.uid` for `GrafanaFolder`

api/v1beta1/grafanaalertrulegroup_types.go, config/crd/bases/grafana.integreatly.org_grafanaalertrulegroups.yaml, controllers/grafanaalertrulegroup_controller.go, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanaalertrulegroups.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md
Resolve https://github.com/grafana/grafana-operator/issues/1716
=> feat: add Name field to GrafanaAlertRuleGroupSpec

Makefile, api/v1beta1/grafanadashboard_types.go, api/v1beta1/grafanadashboard_types_test.go, config/crd/bases/grafana.integreatly.org_grafanadashboards.yaml, controllers/dashboard_controller.go, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanadashboards.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md, tests/e2e/example-test/05-dashboard.yaml, tests/e2e/immutable_uids/grafanadashboard/base-resources.yaml, tests/e2e/immutable_uids/grafanadashboard/chainsaw-test.yaml
Followed the same pattern as #1686 for the CustomUID.
As discussed in the weekly sync, `spec.uid` or `metadata.uid` will always overwrite `dashboardModel.uid`.
Thanks to the existing `Status.UID` update detection, existing dashboards are automatically migrated to using `metadata.uid` by the operator.
<details>
<summary>Local procedure for testing</summary>
```bash
make e2e-local-gh-actions TESTS=immutable_uids
```
```bash
make start-kind
make deploy
kind export kubeconfig --name kind-grafana
kubectl apply -f https://raw.githubusercontent.com/grafana-operator/grafana-operator/master/examples/basic/resources.yaml
kubectl apply -f ../test-dashboard.yaml
kubectl get grafanas -A -o yaml
make ko-build-kind
IMG=ko.local/grafana/grafana-operator make deploy
kubectl patch deploy -n …
```
=> Implement `spec.uid` for `GrafanaDashboard`

api/v1beta1/common.go, api/v1beta1/grafanacontactpoint_types.go, api/v1beta1/grafanadatasource_types.go, config/crd/bases/grafana.integreatly.org_grafanacontactpoints.yaml, config/crd/bases/grafana.integreatly.org_grafanadatasources.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanacontactpoints.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanadatasources.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md
The `valuesFrom[*].valuefrom` field on `GrafanaContactPoint` can be an empty `{}` resulting in nil errors in the log when reconciling.
I personally ran into this when I missed a capital `K` in `secretKeyRef` by mistake and Kubernetes dropped the field once applied.
The following test resources are perfectly valid but the last `GrafanaContactPoint` will trigger a panic.
<details>
<summary>Expand...</summary>
```
2024-10-27T11:53:13Z    ERROR   Observed a panic        {"controller": "grafanacontactpoint", "controllerGroup": "grafana.integreatly.org", "controllerKind": "GrafanaContactPoint", "GrafanaContactPoint": {"name":"invalid-ref","namespace":"default"}, "namespace": "default", "name": "invalid-ref", "reconcileID": "c2b210b4-9b41-485c-8182-6c74fd1e8371", 
"panic": "runtime error: …
```
=> feat: CEL validation of valuesFrom object ensuring refs are defined

.chainsaw.yaml, controllers/grafanafolder_controller.go, tests/e2e/force_delete_folder/chainsaw-test.yaml, tests/e2e/immutable_uids/grafanadashboard/chainsaw-test.yaml, tests/e2e/testdata-resources.yaml, tests/example-resources.yaml
Usually the Grafana folder API will reject a `DELETE` if the folder contains alert rules, this can be overwritten with the [`forceDeleteRules=true`](https://grafana.com/docs/grafana/latest/developers/http_api/folder/#delete-folder) query parameter.
Which luckily is included in the Generated [Grafana openapi client](https://github.com/grafana/grafana-openapi-client-go/blob/main/client/folders/delete_folder_parameters.go#L150-L154)
This PR enables the forced deletion of folders specifically when declared with a CR.
Folders created from the `GrafanaDashboard#spec.folder` field are currently not forced as there is no CR declaring them.
See: [link](https://github.com/grafana/grafana-operator/blob/master/controllers/dashboard_controller.go#L739)
I spent 10 times as longer writing the tests for …
=> Enable forced deletion of `GrafanaFolder`

.github/workflows/release.yaml, Makefile, deploy/helm/cr.yaml, deploy/helm/grafana-operator/Chart.yaml
Implements #1732 
Uses the same approach as the k6-operator to publish releases to the grafana/helm-charts repo
=> feat: release helm charts to grafana/helm-charts

Makefile, api/v1beta1/grafanacontactpoint_types.go, config/crd/bases/grafana.integreatly.org_grafanacontactpoints.yaml, controllers/grafanacontactpoint_controller.go, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanacontactpoints.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md
While implementing this, I noticed a lot of discrepancies between the `ContactPoint` CR and the others.
Once this is merged I'll open a PR fixing the missing error logs when ContactPoints fail to reconcile as well as implementing the same Status fields that other CRs use. (See: https://github.com/grafana/grafana-operator/commit/7e81cb417c4ae83bb851ade5b1973773f0958249)
```bash
make start-kind
kind export kubeconfig --name kind-grafana
kubectl delete grafana-operator --all
kubectl apply -f tests/example-resources.yaml
kubectl apply -f tmp.yml # See resources below
kubectl port-forward svc/grafana-testdata-service 3000 >/dev/null &
```
```yaml
---
kind: GrafanaContactPoint
metadata:
name: metadata-uid
namespace: default
spec:
resyncPeriod: 3s …
```
=> Implement `spec.uid` for `GrafanaContactPoint`

deploy/helm/grafana-operator/templates/servicemonitor.yaml
```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
name: release-name-grafana-operator
namespace: default
labels:
helm.sh/chart: grafana-operator-v5.15.1
app.kubernetes.io/name: grafana-operator
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: "v5.15.1"
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/part-of: grafana-operator
app.kubernetes.io/component: operator
spec:
jobLabel: release-name
namespaceSelector:
matchNames:
- default
selector:
matchLabels:
app.kubernetes.io/name: grafana-operator
app.kubernetes.io/instance: release-name
endpoints:
- port: metrics
path: /metrics
interval: 1m
scrapeTimeout: 10s
metricRelabelings:
- action: replace
replacement: my-cluster
targetLabel: cluster
relabelings:
- action: replace
replacement: …
```
=> fix(helm): yaml indentation for ServiceMonitor

config/manager/manager.yaml, controllers/config/grafana_ini.go, controllers/config/operator_constants.go, examples/alertrulegroups/resources.yaml, tests/e2e/example-test/00-assert.yaml, tests/e2e/example-test/11-assert.yaml
- set `rule_version_record_limit` to `5` by default:
- Prior to Grafana 11.3.0, `alert_rule_version` table would uncontrollably grow to accommodate multiple copies of alert rules;
- In Grafana 11.3.0, a new field (`rule_version_record_limit`, which is part of `unified_alerting` section) was introduced to enforce a limit on the rule versions. It is set to `0` there by default. To mitigate the behaviour, this PR instructs the operator to set the value to 5 by default;
- Other changes:
- bumped the default Grafana version to 11.3.0 (I can drop that commit if needed).
If someone wants to preserve the previous behaviour or postpone initial database cleanup, it's possible to pass:
```yaml
kind: Grafana
spec:
config:
unified_alerting: …
```
=> feat(config): set rule version record limit by default, bump grafana to 11.3.0

controllers/grafana_controller.go, controllers/reconcilers/grafana/deployment_reconciler.go, controllers/reconcilers/grafana/deployment_reconciler_test.go
This allows for simpler replacement of images used.
Fixes #1758 by setting the version based on the RELATED_IMAGE_GRAFANA if it's a hash which allows for overrides later on
=> feat: allow for images in spec.version

examples/grafana_deployment/resources.yaml, examples/persistent_volume/resources.yaml
Rewrites the examples in accordance to #1768. Security context overrides are not needed in a working k8s setup and will only confuse if left in examples uncommented
=> docs: update security context in docs

controllers/reconcilers/grafana/ingress_reconciler.go
This spec prevents our default rules from being used, as a merge will always override them.
Fixes #1774
=> fix: remove rules requirement for ingress

api/common_interfaces.go, api/v1beta1/common.go, api/v1beta1/grafanafolder_types.go, controllers/controller_shared.go, controllers/controller_shared_test.go, controllers/grafanafolder_controller.go, controllers/notificationpolicy_controller.go
This PR aims to improve how reconciliation functions are written going forward, starting with the folder controller.
The goal is to reduce duplicated code by moving more logic into matching Grafana instances.
This is achieved by namespacing the client to limit the scope of the search when resources do not specify `allowCrossNamespaceImport: true`
Additional functions have been added for simplifying building conditions when no matching instances are found.
Lastly, it aligns the existing folder reconcile error logging with other resources
=> Chore(Internal): Add new shared reconciliation functions and migrate `GrafanaFolder`

Makefile, docs/docs/overview.md
- With #1765 the default resyncPeriod for all resources was updated to `10m0s`
- I ran into an issue building with Ko after #1700 added the .ko.yaml
- The Makefile searched the PATH for Chainsaw twice: 
https://github.com/grafana/grafana-operator/blob/1c2641cbec8d2185421300f3cf75f0cae6a9e8aa/Makefile#L35-L40
https://github.com/grafana/grafana-operator/blob/1c2641cbec8d2185421300f3cf75f0cae6a9e8aa/Makefile#L279-L287
=> chore: cleanup Makefile, update docs regarding default resyncPeriod

Makefile, main.go
Switching to production mode has the side-effect that the default encoder also changed to `jsonEncoder`
It might make sense to keep the `consoleEncoder`, hence `Development mode` is explicitly enabled in the makefile.
Should I also create an overlay or similar configuration for the `make deploy` target which enables `Development mode` for outputting debug logs?
In case we start using them.
=> Chore: Update default log level `Debug`->`Info`

controllers/client/tls.go
- Modified `tls.go` to dynamically set the secret namespace based on the `CertSecretRef.Namespace`
These changes were made to support the use of TLS secrets in different namespaces, which is important for multi-tenant environments.
=> Update TLS to support custom secret namespaces

api/v1beta1/common.go, controllers/controller_shared.go, controllers/grafana_controller.go
I spotted a mistake in #1770 resulting in unready instances not being logged if there's only one.
Additionally, the log [`version not yet found`](https://github.com/grafana/grafana-operator/blob/master/controllers/grafana_controller.go#L215) in the `Grafanas` controller was sent to a null sink due to `r.Log` being `nil`.
lastly, I removed the `ResyncPeriodHasElapsed` requirement for `CommonResource` as it is not required in the functions defined in [controllers_shared.go](./controllers/controllers_shared.go)
=> Fix: Invalid `if` condition in `GetScopedMatchingInstances` when only 1 instance is unready

controllers/controller_shared.go, controllers/dashboard_controller.go, controllers/datasource_controller.go, controllers/grafana_controller.go, controllers/grafanafolder_controller.go
Cleaned up some `const` declarations used across different controllers but scattered around.
=> Chore(internal): Refactor const usage and unready info message

api/v1beta1/grafanacontactpoint_types.go, config/crd/bases/grafana.integreatly.org_grafanacontactpoints.yaml, controllers/grafanacontactpoint_controller.go, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanacontactpoints.yaml, deploy/kustomize/base/crds.yaml
- fix: Warnings when returning `ctrl.Result` and an `error` and logging errors twice.
- fix: `status` subresource updates are now ignored
- feat: `status.lastResync` is now updated and registered as a printed column (for `GrafanaFolder` and `GrafanaNotificationTemplate` as well)
It was not clear to me if `Age` should be added as well
=> chore: Update `GrafanaContactPoint` reconcile loop

Makefile, api/v1beta1/grafanafolder_types.go, api/v1beta1/grafananotificationtemplate_types.go, config/crd/bases/grafana.integreatly.org_grafanafolders.yaml, config/crd/bases/grafana.integreatly.org_grafananotificationtemplates.yaml, controllers/grafananotificationtemplate_controller.go, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanafolders.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafananotificationtemplates.yaml, deploy/kustomize/base/crds.yaml, main.go, tests/example-resources.yaml
- chore: Align an error message in Notification Template
- feat: Ensured`lastResync` and `Age` as a printed columns for `GrafanaFolder` and `GrafanaNotificationTemplate`
- chore: Align info log when watching a list of namespaces
- chore: Remove unused loggers in `main()`
- fix: Allow multiple golangci processes to run simultaneously
(I can now run `make` with my editor open...)
=> Chore: Enable concurrent golangci and Update `PrintedColumns` and log messages.

api/v1beta1/grafananotificationpolicy_types.go, config/crd/bases/grafana.integreatly.org_grafananotificationpolicies.yaml, controllers/notificationpolicy_controller.go, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafananotificationpolicies.yaml, deploy/kustomize/base/crds.yaml
I was done updating the reconciler when I realised that there was no cross namespace check to delete and I remembered #1762 existed.
I decided to open this regardless as it looked like it had stagnated.
Feel free to close this if progress will resume.
- fix: Warnings when returning `ctrl.Result` and an `error` and logging some errors twice.
- chore: Folded `r.resetInstance` under finalize to align with other finalize functions as it was only invoked from finalize.
- feat: `status.lastResync` is now updated and registered as a printed column (for `GrafanaFolder` and `GrafanaNotificationTemplate` as well)
It was not clear to me if `Age` should be added as well
`kubectl get grafanas -n default grafana-testdata -o yaml`
```yaml
kind: Grafana …
```
=> Fix: `GrafanaNotificationPolicy` reconcile loop ignoring namespace boundaries

controllers/controller_shared.go, controllers/controller_shared_test.go, controllers/grafanafolder_controller.go, controllers/grafananotificationtemplate_controller.go
- chore: Only fetch scoped matching instances in `GrafanaFolder` finalize
- chore: Only fetch scoped matching instances in `GrafanaNotificationTemplate` finalize
- chore: remove `GetAllMatchingInstances` and relevant tests
=> Fix: Move finalizers away from `GetAllMatchingInstances`

api/v1beta1/common.go, api/v1beta1/common_test.go, config/crd/bases/grafana.integreatly.org_grafanaalertrulegroups.yaml, config/crd/bases/grafana.integreatly.org_grafanacontactpoints.yaml, config/crd/bases/grafana.integreatly.org_grafanadashboards.yaml, config/crd/bases/grafana.integreatly.org_grafanadatasources.yaml, config/crd/bases/grafana.integreatly.org_grafanafolders.yaml, config/crd/bases/grafana.integreatly.org_grafananotificationpolicies.yaml, config/crd/bases/grafana.integreatly.org_grafananotificationtemplates.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanaalertrulegroups.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanacontactpoints.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanadashboards.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanadatasources.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanafolders.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafananotificationpolicies.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafananotificationtemplates.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md
Figured out a validation rule that accomplishes to block `true -> false` and `true -> undefined`
Added tests for validating the behavior as well
=> Fix: Force recreate when disabling `spec.allowCrossNamespaceImport`

api/v1beta1/grafanaalertrulegroup_types.go, config/crd/bases/grafana.integreatly.org_grafanaalertrulegroups.yaml, controllers/controller_shared.go, controllers/grafanaalertrulegroup_controller.go, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanaalertrulegroups.yaml, deploy/kustomize/base/crds.yaml
- Fix: Warnings when returning `ctrl.Result` and an `error` and logging some errors twice.
- Feat: `status.lastResync` is now updated and registered as a printed column
- Refactor: Use `GetScopedMatchingInstances` for `Reconcile` and `finalize`
=> Refactor: Update `GrafanaAlertRuleGroup` reconcile loop

controllers/grafanacontactpoint_controller.go
In order to maintain the functionality of `valuesFrom` on various CRDs, we're planning to disable caching entirely for `ConfigMaps` and `Secrets` in #1818
Referencing the ContactPoint Reconcile function during implementation of #1826 I noticed that `buildSettings`, which fetched referenced `ConfigMaps` and `Secrets` was called once per matched `Grafana` instance.
Which is not an issue when they are cached, but will cause unnecessary requests to the api-server afterwards.
While fixing this, I also added the `InvalidSpec` condition when `buildContactPointSettings` returns an error.
=> Fix: Fetch `ConfigMaps` and `Secrets` once per `GrafanaContactPoint` reconciliation

main.go
Quick PR for unblocking other PRs running into main function complexity lints (#1818 and #1833)
I reduced the calls to `ctrl.GetConfigOrDie()` to one as none of it was cached and the exact same config was read and parsed multiple times.
=> Refactor: Move scope helper functions out of main

go.mod, go.sum, main.go
To make Go runtime aware of CGroup limits, added two calls that set appropriate values for `GOMEMLIMIT` (affects GC schedule) and `GOMAXPROCS` (affects number of OS threads that can execute user-level Go code simultaneously).
If the operator is deployed without resource limits, then `GOMEMLIMIT` and `GOMAXPROCS` will not be set.
If the respective environment variables are already present, then no changes are made.
=> feat(runtime): automatically optimize Go runtime based on cgroup limits

controllers/controller_shared.go, controllers/controller_shared_test.go, controllers/dashboard_controller.go, controllers/dashboard_controller_test.go, controllers/datasource_controller.go, controllers/datasource_controller_test.go, controllers/grafana_controller.go, controllers/grafanaalertrulegroup_controller.go, controllers/grafanacontactpoint_controller.go, controllers/grafanafolder_controller.go, controllers/grafanamutetiming_controller.go, controllers/grafananotificationtemplate_controller.go, controllers/notificationpolicy_controller.go, controllers/reconcilers/grafana/complete_reconciler.go, controllers/reconcilers/grafana/config_reconciler.go, controllers/reconcilers/grafana/deployment_reconciler.go, controllers/reconcilers/grafana/grafana_service_reconciler.go, controllers/reconcilers/grafana/ingress_reconciler.go, controllers/reconcilers/grafana/plugins_reconciler.go, controllers/reconcilers/grafana/pvc_reconciler.go
Was looking to implement an option for configuring `MaxConcurrentReconciles` when registering controllers.
But realised that the Reconciler structs seem to be shared across reconcile requests, meaning `r.Log` could be replaced with context values from a later reconcileRequest.
This is especially likely for `GrafanaContactPoints` due to the `Watches` in [`GrafanaNotificationPolicy`](https://github.com/grafana/grafana-operator/blob/0d53646ac1952e891d164a85a0d52d23836cdaf1/controllers/notificationpolicy_controller.go#L207-L223).
Kubebuilder suggests using the plain [`log := log.FromContext(ctx)`](https://book.kubebuilder.io/cronjob-tutorial/controller-implementation#implementing-a-controller)
Kubebuilder  recommends to always have the ctx as the first argument and I have ensured that is the …
=> Refactor: Reconcile loggers, prepare for concurrent reconcilers

catalog-info.yaml
Required for our internal developer catalog at Grafana Labs.
=> chore: add catalog info for the grafana developer catalog

api/v1beta1/grafanadatasource_types.go, api/v1beta1/grafanadatasource_types_test.go, config/crd/bases/grafana.integreatly.org_grafanadatasources.yaml, controllers/datasource_controller.go, controllers/datasource_controller_test.go, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanadatasources.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md, tests/e2e/example-test/01-assert.yaml, tests/e2e/example-test/06-assert.yaml, tests/e2e/example-test/07-assert.yaml, tests/e2e/examples/crossnamespace/assertions.yaml
This was a significantly more complex rewrite than earlier reconcile loops simply due to how different the controller was written.
I recommend to review this one commit at a time and to have at least 2 separate reviewers verify it due to the amount of changes.
I had to split `finalize` into two separate functions to get past a nasty "Not found" error loop that is correct on an updated uid, but a problem when trying to delete a crd.
I would like some comments on whether `ReconcilePlugins` is needed in both or just finalize?
See commit messages for detailed changes.
This should close #1681 and tick off GrafanaDatasource on #1450
=> Refactor: Update `GrafanaDatasource` reconcile loop

docs/docs/grafana.md
Small docs update reflecting recent changes and community asks
=> docs: update grafana resource docs

api/v1beta1/grafananotificationpolicy_types.go, api/v1beta1/grafananotificationpolicy_types_test.go, api/v1beta1/grafananotificationpolicyroute_types.go, config/crd/bases/grafana.integreatly.org_grafananotificationpolicies.yaml, config/crd/bases/grafana.integreatly.org_grafananotificationpolicyroutes.yaml, controllers/notificationpolicy_controller.go, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafananotificationpolicies.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafananotificationpolicyroutes.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md
While working on #1837 on I was unable to provoke the `LoopDetected` status and discovered that it was removed immediately after being set, the detection itself seems to work without issues.
The above resulted in loops being detected, dynamic routes being ignored and an `ApplySucceeded` condition on `GrafanaNotificationPolicy` CRs
This means that previously working NotificationPolicy trees with dynamic routes would be overwritten with only the static routes in the main `GrafanaNotificationPolicy`, if any.
This changes the behaviour from applying only static routes and ignoring everything dynamic to refusing updates entirely.
`LoopDetected` is now before fetching instances resulting in it having higher priority.
`InvalidSpec` is an error and the `NoMatchingInstances` is not.
`receiver` is …
=> Fix: NotificationPolicy LoopDetected condition and `route.receiver` validation

controllers/controller_shared.go, controllers/datasource_controller.go, controllers/grafanaalertrulegroup_controller.go, controllers/grafanacontactpoint_controller.go, controllers/grafanafolder_controller.go, controllers/grafanamutetiming_controller.go, controllers/grafananotificationtemplate_controller.go, tests/e2e/conditions/01-no-matching-instances-assertions.yaml, tests/e2e/conditions/02-apply-failed-assertions.yaml, tests/e2e/conditions/03-additional-invalid-spec.yaml, tests/e2e/conditions/03-invalid-spec-assertions.yaml, tests/e2e/conditions/03-testdata-invalid-specs.yaml, tests/e2e/conditions/chainsaw-test.yaml, tests/e2e/force_delete_folder/chainsaw-test.yaml, tests/e2e/testdata-assertions.yaml, tests/e2e/testdata-resources.yaml, tests/example-resources.yaml
I forgot that the `buildSynchronizedCondition` function applies either a successful or a failed condition depending on whether errors where present.
This was noticed by @msvechla in #1800
To ensure something like this never happens again, tests have been added to provoke and test every condition currently implemented.
Future PRs will include conditions and tests for `GrafanaDashboards` and potentially `Grafanas`.
Any future CR or condition implementation should probably expand these tests to ensure that the conditions can be provoked appropriately.
=> Fix: Apply error condition never registered due to early return

api/v1beta1/grafanacontactpoint_types.go, bundle/manifests/grafana.integreatly.org_grafanacontactpoints.yaml, config/crd/bases/grafana.integreatly.org_grafanacontactpoints.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanacontactpoints.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md
Currently there's no support for Amazon SNS contactpoint even tough it's available on grafana:
https://grafana.com/docs/grafana/v11.3/alerting/configure-notifications/manage-contact-points/integrations/configure-amazon-sns/
If you try to configure it, you get the following error:
```
GrafanaContactPoint.grafana.integreatly.org "sns" is invalid: [spec.type: Unsupported value: "sns": supported values: "alertmanager", "prometheus-alertmanager", "dingding", "discord", "email", "googlechat", "kafka", "line", "opsgenie", "pagerduty", "pushover", "sensugo", "sensu", "slack", "teams", "telegram", "threema", "victorops", "webex", "webhook", "wecom", "hipchat", "oncall",
```
Modified enums adding sns as an option
=> patch: add support for amazon sns contactpoint

controllers/datasource_controller.go
I noticed that the datasource `onDatasourceDelete` function, that I recently split into a finalize, had an unconditional return at the end of the delete loop.
This means that on the first successful delete of a datasource, the for loop would [return](https://github.com/grafana/grafana-operator/blob/ff3fb07b25ca8ddd171e7a9af297891613c1cdad/controllers/datasource_controller.go#L310) and no other data source would be removed from other instances.
Luckily, this means that no other `Grafana` CRs status was updated.
All other `Grafanas` still have it listed in the status, a restart of the operator will force a datasource sync and delete them from the instances.
This seems to be a two year old bug 😅 
Try applying the below resources to replicate that bug, then delete the datasource and see that …
=> Fix: Finalize only deletes datasource from the first instance

Makefile, deploy/kustomize/base/deployment.yaml, deploy/kustomize/base/kustomization.yaml
* added an indication of the image version in `kustomization.yaml`
* added auto installation of image version for customize in `Makefile`
=> chore: version image in kustomize

controllers/grafanafolder_controller.go
Grafana folders with the same name caused conflicts. This fix allows multiple folders with the same name to exist in a filetree. 
Fixes:  #1847
=> fix: folder title had to be unique

controllers/config/operator_constants.go, controllers/model/grafana_resources.go, controllers/reconcilers/grafana/deployment_reconciler.go, controllers/reconcilers/grafana/grafana_service_reconciler.go, examples/multiple_replicas/resources.yaml, tests/e2e/examples/basic/assertions.yaml, tests/e2e/examples/crossnamespace/assertions.yaml
This PR implements the steps described in the [Grafana documentation](https://grafana.com/docs/grafana/latest/alerting/set-up/configure-high-availability/) to configure a HA grafana:
- Headless Service
- Expose port 9094 on the deployment
- `POD_IP` environment variable from downward API
While most of it can already be added manually with overrides in the CR, the headless service has to be manually created. I think that providing all the key components to run a HA Grafana makes sense.
The "Multiple replicas" doc example has also been updated to include a config snippet for HA setup.
=> feat: add headlessService for grafana high availability

config/crd/kustomization.yaml, deploy/kustomize/base/crds.yaml
The operator kept crashing in my local Kind cluster with:
```
2025-02-27T22:19:40.549Z        error   controller-runtime.source.EventHandler  if kind is a CRD, it should be installed before calling Start   {"kind": "GrafanaLibraryPanel.grafana.integreatly.org", "error": "no matches for kind \"GrafanaLibraryPanel\" in version \"grafana.integreatly.org/v1beta1\""}
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind[...]).Start.func1.1
sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/source/kind.go:71
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2
k8s.io/apimachinery@v0.32.2/pkg/util/wait/loop.go:87
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext
k8s.io/apimachinery@v0.32.2/pkg/util/wait/loop.go:88 …
```
=> fix: Kustomize artifact did not include new library panel CRD

deploy/helm/grafana-operator/README.md, deploy/helm/grafana-operator/templates/deployment.yaml, deploy/helm/grafana-operator/values.yaml
the 'additionalLabels' setting is a bit too coarse-grained especially if you want to utilize e.g. istio sidecar injection, which is only valid for pods.
=> feat: enable setting labels just for pods

controllers/datasource_controller.go, controllers/grafanafolder_controller.go
A similar PR as for the issue regarding `grafanafolder` controller #1516 but for the `grafanadatasource` controller.
Looks like when we retrieve the ID or try to the delete the resource and we receive an error we only return the exception on `NotFound`. While we should proceed on `NotFound` (to delete the resource from the Grafana CRD) and return on any other exception.
This will happen when a datasource is for example manually deleted using the the UI. And will loop forever. `Reconciler error`
The other side of this is that when an error occurs that is anything _but_ `NotFound`: `if errors.As(err, &notFound) > False > remove datasource` the datasource is removed from the Grafana CRD status anyway. 
```go
... 
if errors.As(err, &notFound) {
return ctrl.Result{}, err
}
... …
```
=> don't treat missing datasource as an error when deleting datasource

examples/persistent_volume/resources.yaml
The default strategy `RollingUpdate` conflicts with the `ReadWriteOnce` accessMode. Changing the default strategy to `Recreate` on the "Persistent Volume" example seems like a sensible way to workaround this.
=> fix(examples): use Recreate strategy to fit PVC with ReadWriteOnce access mode

api/v1beta1/grafanadashboard_types.go, controllers/content/fetchers/jsonnet_fetcher.go, controllers/content/resolver.go, controllers/content/resolver_test.go, controllers/controller_shared.go, controllers/dashboard_controller.go, controllers/datasource_controller.go, controllers/librarypanel_controller.go, tests/e2e/conditions/01-no-matching-instances-assertions.yaml, tests/e2e/conditions/02-apply-failed-assertions.yaml, tests/e2e/conditions/03-additional-invalid-spec.yaml, tests/e2e/conditions/03-invalid-spec-assertions.yaml, tests/e2e/conditions/03-testdata-invalid-specs.yaml, tests/e2e/testdata-resources.yaml
Similar to the Datasource reconciler, this was another big refactor.
When I was adding models I had a look over the [NewContentResolver](https://github.com/grafana/grafana-operator/pull/1868/files#diff-5723394742dbfbf05333333388ae1b0de1f9f47650f514bfba6b5d91ace771aa) func.
From what I can tell, the error check and return is unnecessary as [structs don't have a zero value](https://go.dev/ref/spec#The_zero_value) and the `GrafanaContentResource` struct is not embedded as a pointer.
Closes: #1021 #1164 #1679 #1850
PS. @theSuess I did not forget about validating all pre-conditions before updating the status.
But I decided to wait and have a look at that in a different PR.
=> Refactor dashboard reconcile loop

main.go
Use `NewEncoder` instead of `Encoder` as only `NewEncoder` is overriden when using flags.
Fixes: #1878
=> fix: correctly set encoder

controllers/controller_shared.go, tests/e2e/conditions/02-apply-failed-assertions.yaml
At the moment, CR's condition `Status` is always set to `True` meaning it does not reflect some of the apply errors (e.g. when a resource cannot be accepted by Grafana instance, because a feature toggle is not enabled).
Instead, we should set `Status` to `False` when `applyErrors > 0`. Thus, the PR.
=> fix(controllers): set Status in synchronized condition to False when hitting apply errors

controllers/controller_shared.go, controllers/controller_shared_test.go, controllers/notificationpolicy_controller.go
In some files, we have double imports for our API. The PR fixes that.
=> chore(controllers): remove double imports

api/v1beta1/grafanacontactpoint_types.go, config/crd/bases/grafana.integreatly.org_grafanacontactpoints.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanacontactpoints.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md
As we agreed on in the last weekly meeting.
The list of valid `contactpoint.type` inputs is a moving target which inhibits users unnecessarily.
The field is required according to the [HTTP API DOCS](https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#span-idembedded-contact-pointspan-embeddedcontactpoint) hence I opted to add a `MinLength=1` validation and remove `omitEmpty`
=> chore: Remove enum validation of contactpoint type

.github/workflows/e2e.yaml
- workflows:
- removed `docs_only_check` that relied on `tj-actions/changed-files`, which got compromised ([more details](https://news.ycombinator.com/item?id=43367987)), the account is already taken down, so actions are simply failing.
=> chore(workflows): remove docs_only_check job that relies on compromised action

.github/workflows/e2e.yaml
See https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised for more info.
Using the step-security fork instead to keep the same functionality.
=> chore(workflows): update changed-files into using step-security action instead

controllers/alertrulegroup_controller.go
Currently, the operator is updating/persisting the mute timing configuration within the notification settings.
```yaml
...
notificationSettings:
receiver: my-receiver-1
mute_time_intervals:
- mute-pods-weekend
```   
This Pull Request (PR) adds the MuteTimeInterval field to the Alert Group Rule update to support the configuration of mute time intervals.
=> fix(GrafanaAlertRuleGroup): apply mute_time_intervals

controllers/alertrulegroup_controller.go
Instead of removing individual alerts, the operator removed the entire group like it does for folders (presence of individual dashboards is not checked there).
=> chore(GrafanaAlertRuleGroup): simplify finalize stage

controllers/controller_shared.go, controllers/notificationpolicy_controller.go
Similar to  #1801 this fixes potential config drift when Update is invoked by only patching the exact fields.
=> fix(GrafanaNotificationPolicy): use patch instead of update when applying the notification policy annotation to avoid Grafana CR drift

controllers/grafana_controller.go, controllers/reconcilers/grafana/admin_secret_reconciler.go, controllers/reconcilers/grafana/complete_reconciler.go, controllers/reconcilers/grafana/config_reconciler.go, controllers/reconcilers/grafana/deployment_reconciler.go, controllers/reconcilers/grafana/ingress_reconciler.go, controllers/reconcilers/grafana/plugins_reconciler.go, controllers/reconcilers/grafana/pvc_reconciler.go, controllers/reconcilers/grafana/service_account_reconciler.go, controllers/reconcilers/grafana/service_reconciler.go, controllers/reconcilers/reconciler.go, main.go
- Status updates no longer trigger full reconciles of instances.
- All Grafana instance reconciler signatures no longer take a `GrafanaStatus` struct.
Locally unused args are prefixed with `_` for clarity.
- Status is now updated in a Defer similar to other resources.
- `updateStatus` func has been removed.
I spent a long time to boil this one down, but in the end I had to change the if conditions within the for loop to properly support a deferred status update.
The logic itself should be almost exactly the same with no major changes to the flow unlike in #1880
=> Chore(Grafana): Refactor grafana reconciler status

controllers/controller_shared.go, controllers/grafana_controller.go, tests/e2e/conditions/02-apply-failed-assertions.yaml, tests/e2e/conditions/chainsaw-test.yaml
Marks internal instances where Version is empty as failed and omits them when reconciling resources.
A special annotation has been added to ensure that it's possible to provoke the `ApplyFailed` condition in the E2E tests.
`grafana/skip-readiness-check: "true"`
=> chore(Grafana): mark internal Grafana as failed if version cannot be fetched

.github/workflows/e2e.yaml
Found no documentation on the versions we aim to support.
Since [AKS](https://endoflife.date/azure-kubernetes-service) and [EKS](https://endoflife.date/amazon-eks) both support `1.27` I left that in the matrix of supported versions.
The versions were sourced from [kinds latest release](https://github.com/kubernetes-sigs/kind/releases/tag/v0.27.0) except `1.27.14` which was unavailable to pull??
=> Chore: Bump k8s versions in E2E tests

controllers/controller_shared.go
Currently we only display the result as a status condition, we do not log that no instances matched during the current reconciliation.
To partially accomodate #1570 `"AllowCrossNamespaceImport": true/false` has been added to the log line.
Example log line:
```log
2025-03-29T11:36:11.216Z        info    GrafanaDashboardReconciler      No instances matched selector, reconciliation will be retried   {"controller": "grafanadashboard", "controllerGroup": "grafana.integreatly.org", "controllerKind": "GrafanaDashboard", "GrafanaDashboard": {"name":"external-grafanadashboard-sample","namespace":"default"}, "namespace": "default", "name": "external-grafanadashboard-sample", "reconcileID": "5cd532f1-9bd2-4d7e-a722-ce42d5b0f595", "AllowCrossNamespaceImport": false}
```
=> chore(controllers): log cases when none of available Grafana instances match selector

controllers/reconcilers/grafana/deployment_reconciler.go
The previous way of mounting the `configmap` was masking the default content of `/etc/grafana`. This could be troublesome especially if one wants to mount something in the container under `/etc/grafana/provisioning/*` on its own/without relying on the operator to do so.
```shell
docker run -it --entrypoint /bin/bash grafana/grafana
24832c31ab77:/usr/share/grafana$ tree /etc/grafana/
/etc/grafana/
├── grafana.ini
├── ldap.toml
└── provisioning
├── access-control
├── alerting
├── dashboards
├── datasources
├── notifiers
└── plugins
7 directories, 2 files
```
The following patch mounts only `grafana.ini` under `/etc/grafana/grafana.ini`.
=> fix(Grafana): avoid grafana-ini's configmap mount masking the existing files/directories

controllers/grafana_controller.go
In #1901, we added an instruction to skip reconciliation in case generation is the same as before. The issue with that approach is that it leads to skipped reconciles triggered by owned Deployment / ConfigMap (holds a list of plugins) updates, so, e.g., the Deployment is not updated when a new plugin is added.
The PR rolls back the change (until we have a better filtering logic should the need for that be).
=> fix(Grafana): do not skip reconciliation if generation is the same as before

api/v1beta1/grafana_types.go, config/crd/bases/grafana.integreatly.org_grafanas.yaml, controllers/grafana_admin_secret_reconciler_test.go, controllers/reconcilers/grafana/admin_secret_reconciler.go, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanas.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md
When you have a custom secret created for Grafana credentials like this one:
```yaml
kind: Secret
apiVersion: v1
metadata:
name: credentials
namespace: grafana
stringData:
GF_SECURITY_ADMIN_PASSWORD: secret
GF_SECURITY_ADMIN_USER: root
type: Opaque
```
The default one is misleading.
Here is an option to disable it.
```yaml
kind: Grafana
metadata:
name: grafana
spec:
disableDefaultAdminSecret: true
=> feat(Grafana): add an option to disable default admin secret

controllers/controller_shared.go, controllers/controller_shared_test.go, controllers/dashboard_controller.go, controllers/datasource_controller.go, controllers/reconcilers/grafana/deployment_reconciler.go
During recent refactoring of dashboard and datasource controllers, a small defect was introduced around re-queuing CRs in case plugin or home dashboard reconciliation fails (e.g. when resource version changed) . - Such errors were only logged, whereas the operator should have re-queued CRs.
I think there's probably no need to introduce additional conditions for those errors like it was suggested in "TODOs". Instead, we can simply join strings containing various errors. In the end, those belong to the same dashboards / datasources, so the contents of the respective conditions would not cause any confusion.
This part is funny. Prior to #1574, we used `controllerutil.SetOwnerReference` for all resources including Deployments and ConfigMaps. This function doesn't set `controller: true`. After …
=> fix(controllers): retry reconciliation for plugins and home dashboards and fix ownerReferences for plugins and Deployment

controllers/librarypanel_controller.go, controllers/metrics/metrics.go, main.go
Similar to #1897 and #1896, this simplifies the finalize stage by removing the initial GET request to the instances.
This also implements the startup synchronisation for cleaning up Grafana statuses in cases where the library panel CR has been removed.
Unlike other resources, the sync does not attempt to remove the panel from the instance and is not part of the standard reconcile loop.
Due to this, the protection against bombarding a single instance have been removed.
With less logic in the sync function, it was possible to reduce the amount of loops compared to other sync functions.
=> Chore(GrafanaLibraryPanel): Implement startup sync and simplify finalize stage

.github/workflows/hugo.yaml, .github/workflows/pr-hugo.yaml
[dart-sass-embedded](https://github.com/sass/dart-sass-embedded) The repo has been deprecated as the project was merged into the dart-sass compiler.
Additionally, the step has begun to fail in CI recently due to long snap timeouts.
Hence the installation was changed to install from the Github releases directly.
The initial resolution was to remove the dart-sass installation entirely, but we use a couple of .scss files and likely need it to be available, which did not fail the build?
I checked and `dart-sass` is not available in ubuntu-latest per default, unlike go which is necessary to compile the modules defined in `/hugo/config.yaml`
The output is a bit difficult to compare, but from what I can tell, the only difference is the "last update date" in the HTML tags and other files.
The …
=> Chore(Hugo): Remove installation of deprecated dart-sass-embedded in hugo actions

controllers/controller_shared.go, controllers/grafana_controller.go
Tested with an external Grafana with an invalid url.
This extends the base timeout when an error or requeue: true is returned from a reconcile.
```
2025-04-12T13:01:59.167+0200    error   Reconciler error        {"controller": "grafana", "controllerGroup": "grafana.integreatly.org", "controllerKind": "Grafana", "Grafana": {"name":"external-grafana","namespace":"default"}, "namespace": "default", "name": "external-grafana", "reconcileID": "2f962a5a-0278-4382-8175-9f7f425a512d", "error": "failed to get version from external instance: parsing health endpoint data: invalid character '<' looking for beginning of value"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
/home/ste/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/co …
```
=> chore(grafana): Slow down exponential backoff retries on errors

api/v1beta1/grafanadatasource_types.go, controllers/datasource_controller.go, controllers/datasource_controller_test.go
- Break datasources to delete logic in a separate function (similar as for the dashboards [here](https://github.com/grafana/grafana-operator/blob/0dda0c7fc9f23364b8b4928ce0be7ef54a2682b0/controllers/dashboard_controller.go#L134))
- Add a unit test for above function
A `Grafana` resource with multiple datasources with the _same_ name but _different_ ID will not have the duplicate datasources removed.
```yaml
kind: Grafana
...
status:
datasources:
- test-datasource/AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAA
- test-datasource/BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBB < should be deleted if there is not datasource with BB..BB ID
```
If the `kubectl get grafanadatasources` returns
```
NAME                                                     UID
test-datasource …
```
=> Unit test for syncDatasources

Makefile
In #1949, we switched from `config/manager` to `deploy/kustomize/overlays/cluster_scoped`, but did not update `kustomize edit set image` step. As a result, no overrides were happening meaning `make deploy` would always deploy the version that is set in `base/deployment.yaml`.
The PR fixes the behavior.
=> fix(Makefile): properly set new image in deploy target

api/v1beta1/common.go, api/v1beta1/grafanaalertrulegroup_types.go, api/v1beta1/grafanacontactpoint_types.go, api/v1beta1/grafanadashboard_types.go, api/v1beta1/grafanadatasource_types.go, api/v1beta1/grafanafolder_types.go, api/v1beta1/grafanalibrarypanel_types.go, api/v1beta1/grafanamutetiming_types.go, api/v1beta1/grafananotificationpolicy_types.go, api/v1beta1/grafananotificationtemplate_types.go, controllers/alertrulegroup_controller.go, controllers/contactpoint_controller.go, controllers/controller_shared.go, controllers/dashboard_controller.go, controllers/datasource_controller.go, controllers/folder_controller.go, controllers/librarypanel_controller.go, controllers/mutetiming_controller.go, controllers/notificationpolicy_controller.go, controllers/notificationtemplate_controller.go
Figured out a way to have all CRs defer the same `UpdateStatus` function.
It did require to extend the `GrafanaCommonResource` interface to ensure all CRs had a way to return the `GrafanaCommonStatus`.
=> chore(Internal): Refactor deferred status update to share the same function

controllers/model/dashboard_resources.go, controllers/model/grafana_resources.go, controllers/model/utils.go, controllers/reconcilers/grafana/admin_secret_reconciler.go, controllers/reconcilers/grafana/config_reconciler.go, controllers/reconcilers/grafana/deployment_reconciler.go, controllers/reconcilers/grafana/ingress_reconciler.go, controllers/reconcilers/grafana/plugins_reconciler.go, controllers/reconcilers/grafana/pvc_reconciler.go, controllers/reconcilers/grafana/service_account_reconciler.go, controllers/reconcilers/grafana/service_reconciler.go, main.go
As it was described in #1959, it's currently possible to override the label that we use for cache tuning. Bitnami's chart (not supported by us) has the bug, which breaks visibility of PVCs.
It would make sense to prohibit such overrides, thus the PR.
Extra changes:
- switch from `var CommonLabels` to `GetCommonLabels()` to make code more idiomatic (`CommonLabels` was meant to behave like a `const`);
- prevent controller overrides for other child resources, similar to #1932.
Fixes: #1959
=> fix(controllers): prevent label and controller reference overrides

controllers/grafana_controller.go, controllers/reconcilers/grafana/complete_reconciler.go
- Moved `r.getVersion` from `GrafanaReconciler` to `CompleteReconciler`
- External and internal instances now use the same reconciliation logic.
=> Chore(Grafana): Reduce differences between Internal and External Grafana instance reconciliation.

.github/labeler.yml
As discussed in the weekly, we do not use the refactor label.
When this is merged we can [remove/replace the refactor label](https://github.com/grafana/grafana-operator/issues?q=label%3Arefactor%20state%3Aclosed)
=> chore(labeler): Remove `refactor` label

.github/workflows/release.yaml
Permissions are not inherited so we need to explicitly set them on each job
=> ci: explicitly set all required permissions

.github/workflows/release.yaml
Decouple the push process per registry to make sure we're not blocked when quay is down
=> ci: decouple ghcr and quay image publishing

.github/workflows/e2e.yaml, tests/e2e/example-test/08-alert-folder.yaml, tests/e2e/example-test/08-alert-rule-group.yaml, tests/e2e/example-test/08-folder-assert.yaml, tests/e2e/example-test/10-assert-contact-points.yaml, tests/e2e/example-test/10-contact-points.yaml, tests/e2e/example-test/10-notification-policy.yaml, tests/e2e/example-test/chainsaw-test.yaml
I noticed that it is largely the same two E2E `example-test`s  that are unstable.
Isolating requisite resources and lowering their `resyncPeriod` should allow more reconcile attempts which seems to have lowered CI failures in my testing.
=> ci: Stabilize E2E tests

controllers/dashboard_controller.go
Fixes two bugs:
1. Dashboards are not moved when `.spec.folderRef` is changed.
2. Folders owned by a CR or other tool are deleted if empty, usually indicated by `folderRef` and `folderUID`
fixes: #1930
=> fix(dashboard): Recreate dashboard when folderRef is updated

.github/workflows/release.yaml
=> ci: use github artifact attestations instead of cosign

controllers/datasource_controller.go, controllers/datasource_controller_test.go
=> chore(datasource): Remove code that deletes missing CRs from instances

controllers/grafana_controller.go
Should be the last controller that needs the `ignoreStatusUpdates` filter to finally close #1220 
It has previously been attempted to ignore status updates in #1901.
But using the `WithEventFilter` options filters events for Owned resources as well, even if they do not have the `.metadata.generation` field.
See #1931
Using the examples: grafana_deployment and plugins.
Any change to either of:
- `grafanadashboard/keycloak-dashboard#spec.plugins`
- `grafanadatasource/example-grafanadatasource#spec.plugins`
Is reflected in the `cm/grafana-plugins` and triggers an update to `deploy/grafana-deployment`
Unlike the previous attempt.
=> chore(grafana controller): Ignore status updates on Grafanas and Deployments

controllers/reconcilers/grafana/admin_secret_reconciler.go
Was looking at some lints and I discovered these two lines.
I simply could not figure out where and how they were used.
Nowhere else are we reading the variables and removing them still allows the operator to function when using `make run`
Apparently they were introduced back at the beginning of V5 8bed473923b59388228d19dc2836a5f7e25b9344
=> chore(AdminSecret): Remove unnecessary env variables

controllers/alertrulegroup_controller.go, controllers/contactpoint_controller.go, controllers/dashboard_controller.go, controllers/datasource_controller.go, controllers/folder_controller.go, controllers/librarypanel_controller.go, controllers/mutetiming_controller.go, controllers/notificationpolicy_controller.go, controllers/notificationtemplate_controller.go
This removes all the places we store a pointer to the scheme unnecessarily and refactors the controllers to use the `req.NamespacedName` when fetching the resource in the beginning of all Reconcile functions.
=> chore(controllers): Use `req.NamespacedName` directly

.github/workflows/pr-validation.yaml, CONTRIBUTING.md, Makefile
- Makefile & workflows (where applicable):
- logging:
- added log messages to highlight which target is being run (helpful for complex targets like `test`);
- suppressed logging of comments in `manifests` target to declutter outputs;
- golangci-lint:
- added config verify step;
- renamed `code/golangci-lint` target to `golangci-lint` and added comments to make the target appear in `help` target;
- deprecated `go-lint` job in favour of running `golangci-lint` only through Makefile, it should help to avoid behaviour and version inconsistency in workflows;
- moved the target to Development section of Makefile;
- helm-docs:
- added `helm-docs` to `test` target;
- passed path to the helm chart to prevent scanning of the whole repository tree;
- added `.PHONY` statement;
- vet:
- moved `vet` …
=> chore(Makefile): further improvements

api/v1beta1/grafanadashboard_types.go, api/v1beta1/grafanadatasource_types.go, api/v1beta1/grafanafolder_types.go, controllers/dashboard_controller.go, controllers/datasource_controller.go, controllers/folder_controller.go
Thanks to the `ignoreStatusUpdates` event filter on all the reconcilers, we can expect every `reconcile.Request` to happen on spec changes or the resyncPeriod elapsing, but managed by the `controller.Runtime`
Hence, the check is always true or irrelevant as the Content diff verifies the spec changes.
=> chore: Remove `resyncPeriodHasElapsed` checks

api/v1beta1/typeoverrides.go, config/crd/bases/grafana.integreatly.org_grafanas.yaml, deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanas.yaml, deploy/kustomize/base/crds.yaml, docs/docs/api.md
closes #2056 
I took a look at what it would take to implement the remaining [`HTTPHeaders`](https://github.com/openshift/api/blob/674ad74beffcbdf6aa7a577bf23a269c24f92fe8/route/v1/types.go#L162C2-L162C14). 
Turns out it requires a LOT of structs and hence will leave it until requested.
=> feat(Grafana): Allow specifying subdomain on routes. `.spec.route.subdomain`

.github/workflows/release.yaml
KO now uses chainguard as base image.
Only supported
- linux/amd64
- linux/arm64
=> chore(workflows): deprecate arm/v7 and ppc64le from the list of target platforms

controllers/client/grafana_client.go, controllers/client/grafana_client_test.go
This allows using the `.spec.config` as a source of credentials for external instances.
=> fix(Grafana): `.spec.config.security.admin_*` as fallback for external instances

controllers/alertrulegroup_controller_test.go, controllers/contactpoint_controller_test.go, controllers/dashboard_controller_test.go, controllers/datasource_controller_test.go, controllers/folder_controller_test.go, controllers/librarypanel_controller_test.go, controllers/mutetiming_controller_test.go, controllers/notificationpolicy_controller_test.go, controllers/notificationtemplate_controller_test.go, controllers/suite_test.go
Adds `ApplySuccessful` to all resource controllers.
Additionally, it synchronizes the `pre-existing` `GrafanaFolder` into the Grafana testcontainer so it's available to all controller tests.
Previously a `apply-failed-helper` `GrafanaFolder` was created but not synchronized.
Coverage of controllers has gone from `42.2%` to `52.6%`
=> chore(tests): `ApplySuccessful` conditions

.github/workflows/pr-validation.yaml, Makefile
- workflows:
- as we now depend on Grafana image in `test` job (used in tests covering external instances), it makes sense to pre-pull the image to make it available by the time the tests begin instead of waiting for extra ~10-20 seconds till the pulling process is over.
I'll check how to speed up e2e workflow in a similar way.
=> chore(workflows): pre-pull grafana image to speed up CI

.github/workflows/pr-validation.yaml
As we currently don't have any builds running from master branch, its cache is always empty causing:
- the first execution of builds in PRs to be much slower:
- e.g. ~4m for [the first run](https://github.com/grafana/grafana-operator/actions/runs/16562377844/attempts/1), ~2m - for [the second](https://github.com/grafana/grafana-operator/actions/runs/16562377844). - The second execution is faster only because it re-uses the cache uploaded during the first run;
- causing all merge queue executions to be much slower as they rely on temporary read-only branches, which also don't have cache for the same reason.
To mitigate the behaviour, added a workflow trigger that would run jobs from PR validation workflow upon merge to master (all of those jobs generate cache, the main focus of the PR is …
=> chore(workflows): warm up Go cache

.github/workflows/e2e.yaml
- `workflows`:
- Added pre-pull step for kind image to make the e2e workflow a bit faster (~7-10 sec).
=> chore(workflows): pre-pull kind image

controllers/reconcilers/grafana/deployment_reconciler.go, tests/e2e/example-test/00-create-external-grafana.yaml, tests/e2e/example-test/00-create-grafana.yaml, tests/e2e/example-test/00-create-versioned-grafana.yaml, tests/e2e/examples/basic/resources.yaml, tests/e2e/examples/crossnamespace/resources.yaml, tests/e2e/examples/dashboard_immutable_uid/base-resources.yaml
- controllers:
- deprecated initial delay for `readinessProbe` as it was impossible to set it to 0 and it has never made sense anyway;
- as a side-effect for user deployments, existing pods will get recreated, but I think that should be fine due to dynamic nature of k8s. We can add a side-note about that to release description;
- e2e:
- reduced `periodSeconds` for `readinessProbe` from 10 (default) to 2 seconds. With the initial delay removed (5 sec), initial reconciliation of a `Grafana` resource should go down from 15sec+ down to a few seconds (we rely on k8s Service, which adds an Endpoint only when a pod is ready).
=> chore(e2e): faster grafana reconciliation, deprecate default initial delay for readinessProbe

controllers/alertrulegroup_controller.go, controllers/alertrulegroup_controller_test.go, controllers/contactpoint_controller.go, controllers/contactpoint_controller_test.go, controllers/controller_shared.go, controllers/dashboard_controller.go, controllers/dashboard_controller_test.go, controllers/datasource_controller.go, controllers/datasource_controller_test.go, controllers/folder_controller.go, controllers/folder_controller_test.go, controllers/librarypanel_controller.go, controllers/librarypanel_controller_test.go, controllers/mutetiming_controller.go, controllers/mutetiming_controller_test.go, controllers/notificationpolicy_controller.go, controllers/notificationpolicy_controller_test.go, controllers/notificationtemplate_controller.go, controllers/notificationtemplate_controller_test.go
By treating this condition as an error, it will use an exponential backoff timer instead of periodic reconciling.
Should fix #2100
=> feat: treat no matching instances as error

api/v1beta1/common.go, api/v1beta1/grafanaalertrulegroup_types.go, api/v1beta1/grafanacontactpoint_types.go, api/v1beta1/grafanadashboard_types.go, api/v1beta1/grafanadatasource_types.go, api/v1beta1/grafanafolder_types.go, api/v1beta1/grafanalibrarypanel_types.go, api/v1beta1/grafanamutetiming_types.go, api/v1beta1/grafananotificationpolicy_types.go, api/v1beta1/grafananotificationtemplate_types.go, controllers/alertrulegroup_controller_test.go, controllers/contactpoint_controller_test.go, controllers/controller_shared.go, controllers/dashboard_controller_test.go, controllers/datasource_controller_test.go, controllers/folder_controller_test.go, controllers/grafana_controller_test.go, controllers/librarypanel_controller_test.go, controllers/mutetiming_controller_test.go, controllers/notificationpolicy_controller_test.go, controllers/notificationtemplate_controller_test.go, controllers/suite_test.go
- tests:
- added two helpers:
- `containsEqualCondition` - returns true if a CR has a condition of the same `Type` and `Reason`;
- `reconcileAndValidateCondition` - helps to simplify tests for conditions (creates a resource, does a reconcile, requests the result and validates whether a condition and error text match):
- for that to work, had to add `GrafanaCommonReconciler` interface and to expand `CommonResource` interface to expose `metav1.ObjectMeta`;
- simplified condition tests by:
- switching to the new helpers;
- switching from ginkgo over-expressive asserts to testify;
- slightly adjusting structs with tests.
=> chore(controllers): simplify tests around conditions

controllers/alertrulegroup_controller.go, controllers/controller_shared.go, controllers/dashboard_controller.go, controllers/folder_controller.go, controllers/librarypanel_controller.go
I noticed that in a few controllers `getFolderUID` is called once per instance rather than once overall.
Moved getFolderUID before the main synchronize loop in relevant controllers which gives a few benefits
- The k8sclient cache is checked for the `folder` once per reconcile.
- Early exit in AlertRuleGroup when folderUID cannot be resolved.
=> chore: call getFolderUID once before looping instances

controllers/client/grafana_client.go, go.mod
This solves the "issue" of the Grafana HTTP Client using the default internal [`context.Background()`](https://github.com/go-openapi/runtime/blob/master/client/runtime.go#L270) by propagating the top-level ctx into the client overwriting the default.
In general, we have relied on the default request timeout of 10 seconds, but an alternative approach exists where a context can be attached to a Params struct which can then be used to cancel requests.
But, unless necessary, we do not create a Params struct and use the special variant functions accepting the parameters.
Idiomatic Go would mean passing a context in as a function argument, but the HTTP client does not support that.
This avoids having to update almost all the usages of the HTTP Client across the controllers.
=> chore: override default ctx in Grafana httpclient

controllers/alertrulegroup_controller.go, controllers/dashboard_controller.go, controllers/datasource_controller.go, controllers/folder_controller.go, controllers/librarypanel_controller.go, controllers/notificationpolicy_controller.go, controllers/suite_test.go
The initial goal was to just delete created CRs and trigger the finalizer.
Unfortunately `GrafanaDashboard`, `GrafanaDatasource`, and `GrafanaFolder` all returned successful when attempting to finalize against the `dummy` Grafana instance used to provoke Synchronization failures.
I removed the early exit in favour of attempting and potentially failing to delete the resource.
All finalizers will now return a success if the resource was deleted or didn't exist, and an error otherwise.
This should lead to a few more requests when finalizing resources, but more correct deletion outcomes in edge cases.
The downside of this is the need to expect an error when the `dummy` instance, which never responds, is being deleted from.
=> chore(controllers): Test CR deletion, Update finalizer behaviour of Dashboard, Datasource, and Folder

api/v1beta1/grafana_types.go, api/v1beta1/plugin_list.go, api/v1beta1/plugin_list_test.go, controllers/reconcilers/grafana/deployment_reconciler.go, examples/plugins/README.md, examples/plugins/dashboard.yaml, examples/plugins/datasource.yaml
- plugins:
- features:
- added support for "latest" version;
- added `String()` method to `GrafanaPlugin` to simplify `PluginList` `String()` method;
- fixes:
- `Update` method (used in plugins reconciler to pick the newest plugin version) had no effect, because the update was done on a copy of `GrafanaPlugin`, not on a slice element. Fixed the behaviour and added a test for that;
- tests:
- added tests for `HasExactVersionOf`, `HasNewerVersionOf`, `SomeVersionOf`;
- extended `Sanitize` tests to cover incorrect versions;
- deprecations:
- unused `PLUGINS_HASH` env (it became obsolete about ~3 years ago when we moved away from a custom plugin installer to `GF_INSTALL_PLUGINS`);
- unused `GetInstalledVersionOf`, `Hash`, `VersionsOf` methods.
**NOTE:** I felt like it'd be better to cover the …
=> feat(plugins): add support for latest version, fix version preference for duplicate plugins

.github/workflows/e2e.yaml, Makefile, hack/kind/start-kind.sh
- e2e:
- bumped kind to the latest supported k8s releases;
- bumped `envtest` to `1.34.0`.
=> chore(e2e): bump kind to the latest supported k8s releases

controllers/controller_shared.go, controllers/controller_shared_test.go
This PR fixes a defect that was introduced during the recent plugin data types refactoring. - Instead of removing a ConfigMap key when no plugins are left or when a CR is removed, the operator updates the key with null-value.
To mitigate the behaviour, added a length check, so now the keys will get properly garbage collected.
**NOTE:** no releases got affected, only the code in master branch.
=> fix(plugins): remove ConfigMap key if no plugins left

controllers/datasource_controller.go, controllers/datasource_controller_test.go, main.go
When a GrafanaDatasource CR references secrets or configmaps through the `valuesFrom` field, the operator will now automatically reconcile the datasource whenever those referenced resources change.
Fixes [#2142](https://github.com/grafana/grafana-operator/issues/2142)
- Followed the same approach mentioned here - https://github.com/grafana/grafana-operator/issues/2142#issuecomment-3219444576
- Added unit tests for the indexing functionality
Note:
Should we add to add reconciler logic here too or in a separate PR? it says todo
https://github.com/grafana/grafana-operator/blob/37a6cfd761e358b3caef2706506fc3416e47acd6/controllers/serviceaccount_controller.go#L829
lemme know
=> feat: added watchers for cm, secrets in datasource_controller

controllers/librarypanel_controller.go
- `LibraryPanel`:
- fixes:
- finalize plugins (#2172);
- mitigate HTTP errors for non-existent panels (finalize stage):
- current Grafana API behaviour is a bit weird in a sense that it responds with an HTTP 403 when the operator tries to fetch the number of linked dashboards for a non-existent library panel (`GetLibraryElementConnections`). To mitigate the error, switched the operator to another API endpoint;
- chores:
- unified variable naming in finalize.
Fixes: #2172
Depends on: #2179
`grafana-operator-controller-manager-6cbfb78484-899f8 manager 2025-09-01T14:42:53.646Z error Reconciler error {"controller": "grafanalibrarypanel", "controllerGroup": "grafana.integreatly.org", "controllerKind": "GrafanaLibraryPanel", "GrafanaLibraryPanel": …
=> fix(librarypanel): finalize plugins, mitigate HTTP errors for non-existent panels

main.go
I noticed that we create two separate contexts in the main function.
Both of which listen to `SIGINT` and `SIGTERM`.
Funnily enough, the manual `NotifyContext` registered `SIGINT` twice and also had `SIGPIPE`?
`ctrl.SetupSignalHandler` listens to almost the same signals and is also a background context.
=> Chore: Only register interrupts to a single context
