Gopkg.lock
deploy/olm-catalog/grafana-operator/1.3.0/grafana-operator.package.yaml
deploy/olm-catalog/grafana-operator/1.3.0/grafana-operator.v1.3.1.clusterserviceversion.yaml
version/version.go

Prepare release v1.3.1
* fixes #31

prepeare release v1.3.1

---

templates/grafana-deployment.yaml

- A noop, just cleaning the if statement up in the template

Template Fix

---

pkg/controller/grafana/grafana_controller.go
pkg/controller/model/constants.go
pkg/controller/model/grafanaService.go

fix: do not overwrite existing node port

---

pkg/apis/integreatly/v1alpha1/grafana_types.go
pkg/controller/config/grafanaIni.go

added support role_attribute_path in auth.generic_oauth

---

pkg/apis/integreatly/v1alpha1/grafana_types.go
pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
pkg/controller/config/grafanaIni.go

adding missing part of OAuth type GitLab.

adding type AuthGitlab

---

deploy/roles/role.yaml

fix https://github.com/integr8ly/grafana-operator/issues/134
Signed-off-by: Slach <bloodjazman@gmail.com>

fix https://github.com/integr8ly/grafana-operator/issues/134

---

pkg/apis/integreatly/v1alpha1/grafanadatasource_types.go

fix https://github.com/integr8ly/grafana-operator/issues/148
fix https://github.com/integr8ly/grafana-operator/issues/156

add jsonData, jsonSecureData usefull fields for generate grafana datasources YAML 

---

deploy/operator.yaml
pkg/apis/integreatly/v1alpha1/grafana_types.go
pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
pkg/controller/model/grafanaServiceAccount.go

Fix #199: ImagePullSecret for ServiceAccount

---

deploy/examples/dashboards/Grafonnet.yaml
deploy/examples/jsonnet/Configmapjsonnet.yaml
deploy/examples/jsonnet/GrafanaWithJsonnet.yaml
pkg/controller/grafana/grafana_controller.go
pkg/controller/grafana/grafonnet_utils.go

JIRA Link: https://issues.redhat.com/browse/INTLY-8796
changes to read and create libs from config maps.
validation checks and reconciling the dashboards
with config maps support.

Support for Grafonnet.

---

deploy/operator.yaml
documentation/deploy_grafana.md

see https://github.com/integr8ly/grafana_plugins_init/issues/1
also, fix https://github.com/integr8ly/grafana-operator/issues/229

fix --grafana-plugins-init-container-tag default value in documentation and rollback operator image URL

---

SECURITY.MD

Add SECURITY.md doc

---

Makefile
deploy/cluster_roles/cluster_role_binding_grafana_operator.yaml

Signed-off-by: dongdwdw <dongdwdw@cn.ibm.com>

fix issue-224

---

.gitignore
.gitmodules

Add the grafonnet submodule

---

build/Dockerfile

Make sure jsonnet libs can be created

---

README.md

Updating the Readme to include some benefits of the operator over standalone Grafana 
Feel free to suggest/include more, these are just a few off the top of my mind.

add benefits of grafana-operator to readme

---

Makefile
deploy/operatorMasterImage.yaml
documentation/deploy_grafana.md

- Add specified latest tag
- Add operatorMasterImage.yaml
- Fix makefile
- Update documentation where relevant
Fixes: #281 
@tux-o-matic

Fix #281, operator.yaml should not use `latest` tag

---

OWNERS

- Adds preqrequisites for eventual openshift-ci integration
N/A
N/A
N/A

Adding prereqs for openshift-ci

---

deploy/crds/GrafanaDashboard.yaml

- Adding in a missing crd field `customFolderName` for Grafanadashboards

add missing crd field

---

openshift-ci/Dockerfile.tools
openshift-ci/OWNERS
openshift-ci/README.md
openshift-ci/test/e2e/main_test.go
openshift-ci/test/run

- Adding Dockerfile.tools for openshift-ci setup requirements
N/A
N/A

add Dockerfile.tools

---

deploy/crds/Grafana.yaml

fix grafana.yaml

---

.github/dependabot.yml
.github/workflows/build-image.yml
Makefile
build/Dockerfile

https://github.com/integr8ly/grafana-operator/issues/277
Use the docker official github workflow actions https://github.com/docker/setup-buildx-action
to make setup buildx easier.
Need add secret `DOCKER_USERNAME` & `DOCKER_PASSWORD` and `QUAY_USERNAME` & `QUAY_PASSWORD` for `quay.io` 
example:
https://hub.docker.com/r/querycap/grafana-operator/tags?page=1&ordering=last_updated

build: multi-arch builds

---

.github/workflows/release.yaml

- Adds GoReleaser to automate binary compilation & checksums for releases
Addresses #318

add goReleaser workflow

---

deploy/examples/dashboards/DashboardFromURL.yaml

Looking at the Repo I saw this was out of place. so I will look at fixing all of these
none, did for myself
- ~~[ ] This change requires a documentation update~~ 
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added a test case that will be used to verify my changes~~ 
running on a local CRC cluster to see if it will work shortly

fix(examples): change example to be cleaner

---

documentation/dashboards.md

Fixed customFolderName casing in docs

---

documentation/README.md
documentation/dashboards.md
documentation/datasources.md
documentation/multi_namespace_support.md
documentation/plugins.md

- Clearing up documentation around datasources and plugin installations (automated or via Env-Var)
/closes #155

Clear up documentation around plugin installation and datasources

---

pkg/controller/model/constants.go

Updates the Grafana version to 7.3.10. Many bugs have been fixed in Grafana 7.3.x: https://github.com/grafana/grafana/compare/v7.3.1...v7.3.10
I don't know what's involved in supporting a new minor version of Grafana with grafana-operator, so this PR only updates to the latest patch version on the currently used minor version, 7.3.

Update grafana version to 7.3.10

---

pkg/apis/integreatly/v1alpha1/grafana_types.go
pkg/controller/config/grafanaIni.go

add default_theme parameter passing to grafana.ini (closes #394)

---

Dockerfile

Hadolint issue: https://github.com/hadolint/hadolint/wiki/DL3020
N/A
Download and run https://github.com/hadolint/hadolint on your computer.
hadolint Dockerfile

Fix Dockerfile COPY instead of ADD

---

.github/workflows/pr-validation.yaml
.golangci.yaml
Makefile

A initial PR-validation using github action that will trigger on each PR
N/A
See a example of the PR run here: https://github.com/NissesSenap/grafana-operator/actions/runs/900398268

Initial PR-validation github action

---

documentation/dashboards.md

fixing a typo in the dashboards doc

fix typo in dashboards doc

---

controllers/config/controller_config.go
controllers/grafana/grafana_controller.go
controllers/grafana/grafana_reconciler.go
controllers/grafana/pluginsHelper.go
controllers/grafanadashboard/dashboard_pipeline.go
controllers/grafanadashboard/grafanadashboard_controller.go
controllers/grafanadatasource/datasource_controller.go
controllers/grafanadatasource/datasource_pipeline.go
controllers/model/grafanaDeployment.go
main.go

Fix some of the linting errors I get when running golangci-lint run
* Removing unsued vars
* Simplefying if statments
* Update import order
* https://staticcheck.io/docs/checks
N/A
I should have only changed some implementation details. We shouldn't even need to regenerate the CRD:s after this get's merged.

Fix: Make linter happier

---

.github/workflows/pr-validation.yaml
.trivyignore
Dockerfile

* Use golang:1.16 just like we do in go.mod
* Update ubi to 8.4
* Run make manager in build pipeline
More general cleanup
N/A
Create a new PR

Update dockerfile & pr-validation

---

.golangci.yaml
controllers/common/clusterActions.go
controllers/common/clusterState.go
controllers/config/controller_config.go
controllers/config/controller_config_test.go
controllers/constants/constants.go
controllers/grafana/grafana_reconciler.go
controllers/grafana/grafonnet_utils.go
controllers/grafana/pluginsHelper.go
controllers/grafanadashboard/grafana_client.go
controllers/grafanadashboard/grafanadashboard_controller.go
controllers/grafanadatasource/datasource_controller.go
controllers/model/grafanaConfig.go
controllers/model/grafanaDeployment.go
controllers/model/grafanaIngress.go
internal/k8sutil/k8sutil.go
main.go

* Fix switch case https://golangci-lint.run/usage/linters/#exhaustive
* removing new-lines
* add error checks
* ignore gosec errors
* remove lll lint check
* minor spell fix
* clean up unused code
* prealloc variabels at creation
N/A
Linting

Lint improvments

---

controllers/config/grafanaIni.go
controllers/config/grafanaIni_test.go
go.mod
go.sum

Refactor grafanaIni and write some basic tests.
Run unit tests

Refactor grafanaIni to become smaller

---

pkg/controller/grafana/grafana_controller.go

fix service name resolution | v3

---

.golangci.yaml
api/integreatly/v1alpha1/grafanadashboard_types.go
controllers/common/auto_detect.go
controllers/common/clusterActions.go
controllers/config/controller_config.go
controllers/config/grafanaIni.go
controllers/config/grafanaIni_test.go
controllers/grafana/grafana_controller.go
controllers/grafana/grafana_reconciler.go
controllers/grafana/grafonnet_utils.go
controllers/grafana/pluginsHelper.go
controllers/grafanadashboard/dashboard_pipeline.go
controllers/grafanadashboard/grafanadashboard_controller.go
controllers/grafanadatasource/datasource_controller.go
controllers/model/grafanaDeployment.go
controllers/model/grafanaIngress.go
go.mod
go.sum
main.go

fix linter errors and disable some of the more unreasonable rules (mostly preallocating an array when the size is unknown and depends on conditions in the CR)

fix linter errors and adapt rules

---

.github/workflows/pr-validation.yaml

This way contributes don't have to take care of old technical debt
even if we enable a new linter or change the current linting rules.
N/A

golangci-lint on error on new issues in a PR

---

config/manager/manager.yaml

* Update Makefile to make it easier for new developers
* Create develpoment docs
* Update manager.yaml with custom grafana-operator env vars
to work out of the box
- #447

Update 4.0 yaml to work out of the box

---

Makefile
documentation/develop.md

* Add submodule to Makefile to make it easier for developers with a clean repo
to get started.
* Create documentation for developers that want to contribute to the operator.

Create develop.md and update Makefile

---

.gitignore

remove binary file and update .gitignore

fix: remove binary file

---

controllers/model/grafanaDeployment.go

Add code to actually use InitImage parameter from CR Spec.
Add if, to check for Spec variable.
Move fmt String code to the else block, and only use image variable later on.
Fixes issue #450 
Bug fix (non-breaking change which fixes an issue)
To test the changes :
* Use InitImage in CR deployment definition, with a custom registry, 
* Verify that the image is actually pulled from it and not the default.

Add InitImage missing code

---

Dockerfile

- Removes unnecessary COPY from the dockerfile
-  cc @NissesSenap 
- Checkout this branch and run `make docker-build` then `docker run quay.io/integreatly/grafana-operator:latest`

remove useless COPY from dockerfile

---

.gitignore
Makefile
deploy/olm-catalog/grafana-operator/3.x.x/3.10.3/grafana-operator.v3.10.3.clusterserviceversion.yaml
deploy/olm-catalog/grafana-operator/3.x.x/3.10.3/grafanadashboards.integreatly.org.crd.yaml
deploy/olm-catalog/grafana-operator/3.x.x/3.10.3/grafanadatasources.integreatly.org.crd.yaml
deploy/olm-catalog/grafana-operator/3.x.x/3.10.3/grafanas.integreatly.org.crd.yaml
deploy/operator.yaml
go.sum
version/version.go

Prepare for v3.10.3:
* move image to the new quay.io/grafana-operator org
* update version from 3.10.2 to 3.10.3
TODO:
update community operators repo

Release v3.10.3

---

deploy/olm-catalog/grafana-operator/3.x.x/3.0.2/grafanas.integreatly.org.crd.yaml
deploy/olm-catalog/grafana-operator/3.x.x/3.10.0/grafanas.integreatly.org.crd.yaml
deploy/olm-catalog/grafana-operator/3.x.x/3.2.0/grafanas.integreatly.org.crd.yaml
deploy/olm-catalog/grafana-operator/3.x.x/3.5.0/grafanas.integreatly.org.crd.yaml
deploy/olm-catalog/grafana-operator/3.x.x/3.6.0/grafanas.integreatly.org.crd.yaml
deploy/olm-catalog/grafana-operator/3.x.x/3.7.0/grafanas.integreatly.org.crd.yaml
deploy/olm-catalog/grafana-operator/3.x.x/3.8.0/grafanas.integreatly.org.crd.yaml
deploy/olm-catalog/grafana-operator/3.x.x/3.8.1/grafanas.integreatly.org.crd.yaml
deploy/olm-catalog/grafana-operator/3.x.x/3.9.0/grafanas.integreatly.org.crd.yaml

update CRD to fix invalid key name

---

config/crd/bases/integreatly.org_grafanas.yaml

In a earlier PR we have forgotten to check for updates in CR and it have been merged. Due to that other PR:s complains about uncommited changes. 
This shouldn't happen in the future, since we now check for it in each PR
check out master branch
```shell
make manifests
git status
```
and you will see none commited changes.

Fix make crd yaml clean after missed update

---

controllers/model/grafanaDeployment.go

fix deployment labels loss
1. add deployment label config in grafana
```yaml
deployment:
labels:
myapp: grafana
```
2. check deployment labels

fix: add deployment labels

---

api/integreatly/v1alpha1/grafana_types.go
api/integreatly/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/integreatly.org_grafanas.yaml
controllers/model/grafanaDeployment.go

Replicas will be not required with this PR and will default back to Kubernetes if not defined. 
Issue: https://github.com/grafana-operator/grafana-operator/issues/491

Make replicas not required

---

controllers/model/grafanaDeployment.go

Fixes nil pointer exceptions when deployment is not defined.
1. Create a Grafana CR without a spec.deployment section
2. Make sure the instance is created and there are no exceptions in the Operator logs.

fix: nil pointers when spec.deployment is not defined

---

Dockerfile

This way the operator will take even less space
https://www.redhat.com/en/blog/introduction-ubi-micro

Change Dockerfile to ubi:micro

---

Makefile
documentation/api.md

The api.md docs get's updated thanks to a change in crdoc cli. I have pinned the version now so this shouldn't happen again.
```
rm $(which crdoc)
make api-docs
```

Specify version of crdoc to generate api.md

---

documentation/api.md

Looks like we managed to check in code that didn't contain API docs updates. This PR fixes it so it's back in sync on the master branch so all PR:s don't fail for no reason.
`make test`

Fix api-docs sync

---

.github/workflows/stale.yml

- Adds a github action to check for stale issues and pull requests
For more info see https://github.com/actions/stale, includes an explanation of all input options
N/A - discussed during weekly triage call

add stale action workflow

---

deploy/crds/GrafanaDataSource.yaml
deploy/examples/datasources/Alertmanager.yaml
pkg/apis/integreatly/v1alpha1/grafanadatasource_types.go

Added the possibility for Alertmanager Datasources to define the `implementation` flag in the crds.
It is a minor addition in the CRD.

Added support for grafana 8.2.x Alertmanager Datasource jsonData implementation: <prometheus|cortex>

---

deploy/examples/oauth/README.md

The current link is broken.
- [ X ] Bug fix (non-breaking change which fixes an issue)

fix a broken link

---

controllers/constants/constants.go

Upgrade default grafana version to 7.5.15
https://grafana.com/blog/2022/02/08/grafana-7.5.15-and-8.3.5-released-with-moderate-severity-security-fixes/

Upgrade default grafana version to 7.5.15

---

Makefile
bundle/manifests/grafana-operator.clusterserviceversion.yaml
bundle/manifests/integreatly.org_grafanadatasources.yaml
bundle/manifests/integreatly.org_grafanas.yaml
config/manager/kustomization.yaml
config/manifests/bases/grafana-operator.clusterserviceversion.yaml
deploy/manifests/latest/deployment.yaml
deploy/manifests/v4.2.0/crds.yaml
deploy/manifests/v4.2.0/deployment.yaml
deploy/manifests/v4.2.0/kustomization.yaml
deploy/manifests/v4.2.0/rbac.yaml
version/version.go

Prepare release v4.2.0

---

documentation/upgrade.md

Simple documentation fix. Created the PR as I was following the documentation myself and encountered the error.

DOCIFX fixed typo in v3 to v4 upgrade docs

---

Makefile
bundle/manifests/grafana-operator.clusterserviceversion.yaml
bundle/manifests/integreatly.org_grafanadatasources.yaml
config/manager/kustomization.yaml
config/manifests/bases/grafana-operator.clusterserviceversion.yaml
deploy/manifests/latest/deployment.yaml
deploy/manifests/v4.3.0/crds.yaml
deploy/manifests/v4.3.0/deployment.yaml
deploy/manifests/v4.3.0/kustomization.yaml
deploy/manifests/v4.3.0/rbac.yaml
version/version.go

Prepare release v4.3.0

---

Makefile
bundle/manifests/grafana-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
config/manifests/bases/grafana-operator.clusterserviceversion.yaml
deploy/manifests/latest/deployment.yaml
deploy/manifests/v4.4.0/crds.yaml
deploy/manifests/v4.4.0/deployment.yaml
deploy/manifests/v4.4.0/kustomization.yaml
deploy/manifests/v4.4.0/rbac.yaml
version/version.go

Prepare release v4.4.0

---

Makefile
bundle/manifests/grafana-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
config/manifests/bases/grafana-operator.clusterserviceversion.yaml
deploy/manifests/latest/deployment.yaml
deploy/manifests/v4.4.1/crds.yaml
deploy/manifests/v4.4.1/deployment.yaml
deploy/manifests/v4.4.1/kustomization.yaml
deploy/manifests/v4.4.1/rbac.yaml
version/version.go

Prepare release v4.4.1

---

go.mod
go.sum

fixes a vulnerability in golang.org/x/text dependency

update golang.org/x/text to v0.3.7 to mitigate vulnerability

---

documentation/deploy_grafana.md

Fix a few typos in docs

---

go.mod
go.sum

Make trivy pass by upgrading golang net package.

Upgrade golang net dependency

---

controllers/model/grafanaDeployment.go

re-apply @HubertStefanski 's fix for #381 
fixes #850

change maxUnavailable and MaxSurge to use percentages as opposed to int

---

controllers/config/controller_config.go

Sort dashboards by namespace

---

docs/_index.html

Fix minor typo in _index.html

---

.github/workflows/kind-e2e.yaml
.github/workflows/pr-validation.yaml
.github/workflows/release.yaml
README.md

Update README to reflect the new branching strategy.
Solves: https://github.com/grafana-operator/grafana-operator/issues/914

Adopt to v4

---

deploy/base/deployment.yaml

This was changed in our container image after we switched over to ko. Apparently we missed the fix in the kustomize file. Solves: #928

Remove hardcoded entrypoint in kustomize

---

deploy/helm/grafana-operator/README.md
deploy/helm/grafana-operator/templates/deployment.yaml
deploy/helm/grafana-operator/values.yaml

Update the deployment to use the correct env var name.
Solves: #939

[helm] WATCH_NAMESPACE not WATCH_NAMESPACES

---

docs/docs/dashboards.md

As part of #957, added a section explaining how the operator works with dashboard uid.

docs: added section regarding dashboard uid

---

docs/blog/flux-gitops/grafana-operator.yaml
docs/blog/flux-gitops/grafana.yaml
docs/blog/flux-gitops/grafana/dashboard.yaml
docs/blog/flux-gitops/grafana/grafana.yaml
docs/blog/flux-gitops/grafana/kustomization.yaml
docs/blog/kustomize-installation.md

I needed to verify how this worked, so I wrote a blog about it.
This is very much a draft and I will continue to work.

blog install Grafana-operator using flux and kustomize

---

api/v1beta1/typeoverrides.go
config/crd/bases/grafana.integreatly.org_grafanas.yaml
config/grafana.integreatly.org_grafanas.yaml
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanas.yaml
deploy/kustomize/base/crds.yaml
docs/docs/api.md

Fix for #958 . Applies same fix as [PR 1009](https://github.com/grafana-operator/grafana-operator/pull/1009) but running make test and kustomize-crds.

Add annotations to template metadata

---

bundle/manifests/grafana.integreatly.org_grafanafolders.yaml

Seems like we forgot to update bundle CRD again :)

fix: update folder CRD for resyncPeriod in bundle

---

docs/docs/datasources.md

This is needed to match https://github.com/grafana-operator/grafana-operator/pull/1055 by @pb82

doc: Fix GrafanaDataSource example to match current schema

---

docs/blog/v4-v5-migration.md

A blog about migrating grafanaDashboards from v4 to v5.
It's not meant to solve all problems you might have, but rather an inspiration source.

[docs] blog/script to migrate from v4-v5

---

bundle/manifests/grafana-operator.clusterserviceversion.yaml
config/manifests/bases/grafana-operator.clusterserviceversion.yaml

Operatorhub requires setting a min kube version

add min kube version to csv

---

Makefile
docs/docs/api.md
hugo/templates/frontmatter-grafana-operator.tmpl

Incorporate pending fixes to upstream template:
* https://github.com/fybrik/crdoc/pull/239
* https://github.com/fybrik/crdoc/pull/240

fix: Add local hugo templates 

---

controllers/dashboard_controller.go
controllers/datasource_controller.go

Only update LastResync if it has expired

---

Makefile
bundle/manifests/grafana-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
config/manifests/bases/grafana-operator.clusterserviceversion.yaml

version bump

---

Makefile
bundle/manifests/grafana-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
config/manifests/bases/grafana-operator.clusterserviceversion.yaml

Update resources and manifests to v5.0.2

bump version to v5.0.2

---

Makefile
bundle/manifests/grafana-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
config/manifests/bases/grafana-operator.clusterserviceversion.yaml
deploy/helm/grafana-operator/Chart.yaml
deploy/helm/grafana-operator/README.md
hugo/config.toml

feat: prepare release v5.2.0

---

bundle/manifests/grafana-operator.clusterserviceversion.yaml
config/manifests/bases/grafana-operator.clusterserviceversion.yaml

Related to: https://github.com/grafana-operator/grafana-operator/commit/91d73f2fa8cb43b709e451269e1660735b8c6e33

fix: change operator provider to "Community"

---

main.go

Fixes #1246, by shamelessly repurposing the existing `getNamespaceConfig` function. Seems like `strings.split` works even if there's no `,` found :) (https://go.dev/play/p/0jLImFAifi7)
Test image available via `ttl.sh/grafana-operator-1246:24h@sha256:daa310d8b85f2603f3070495f4ea1dc77eac89bed4c7543efc3c06fe6a40e2aa` (expires 2023/09/28 21:37:05 CEST)

fix namespace scope with single namespace

---

bundle/manifests/grafana-operator.clusterserviceversion.yaml
config/manifests/bases/grafana-operator.clusterserviceversion.yaml

Forgot to update this in #1344

fix: set updated provider in olm bundle

---

.github/workflows/pr-validation.yaml
Makefile
controllers/datasource_controller.go

- bump golangci-lint version to 1.55.2
Signed-off-by: Edvin Norling <edvin.norling@kognic.com>

fix G601: Implicit memory aliasing in for loop in datasource_controller

---

Makefile
deploy/helm/grafana-operator/Chart.yaml
deploy/helm/grafana-operator/README.md
hugo/config.toml

As @HubertStefanski pointed out, during the meeting,  the OLM PRs don't want you to update an existing release.
So just to make sure everything is in sync I created this PR

prepare 5.6.2

---

.github/workflows/e2e.yaml

Fix debug logs in e2e tests workflow.

fix: debug logs in e2e tests workflow

---

controllers/datasource_controller.go

Partial implementation of #1357 focusing on data sources

refactor: use openapi client for data sources controller

---

api/v1beta1/grafana_types.go
config/crd/bases/grafana.integreatly.org_grafanas.yaml
config/grafana.integreatly.org_grafanas.yaml
controllers/client/grafana_client.go
controllers/grafana_controller.go
controllers/reconcilers/grafana/deployment_reconciler.go
controllers/reconcilers/grafana/deployment_reconciler_test.go
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanas.yaml
deploy/kustomize/base/crds.yaml
docs/docs/api.md
tests/e2e/example-test/00-assert.yaml
tests/e2e/example-test/00-create-external-grafana.yaml
tests/e2e/example-test/00-create-versioned-grafana.yaml
tests/e2e/example-test/chainsaw-test.yaml

feat: expose grafana version in spec & status

---

Makefile

This PR bumps chainsaw to 0.1.9.

chore: bump chainsaw version to 0.1.9

---

README.md

Before merging - do we want to pin this to the daylight savings cycle of Europe (as most maintainers are based there)?
Not urgent to decide right now but winter will come ;)

Update Meeting Time

---

controllers/dashboard_controller.go

fix: do not return error if no env is defined

---

docs/docs/installation/kustomize.md

to latest https://github.com/grafana/grafana-operator/releases

update pinned release documentation

---

controllers/grafanacontactpoint_controller.go

fix: correctly set `disableResolveMessage` for contact points

---

docs/docs/datasources.md

Example was not working. Needed to change some fields

Fix example prometheus datasource

---

Makefile
README.md
deploy/helm/grafana-operator/Chart.yaml
deploy/helm/grafana-operator/README.md
hugo/config.toml

Forgot to update the docs before releasing - shouldn't cause any issues to merge this later as far as I'm aware

docs: update version in docs

---

docs/docs/installation/kustomize.md

@weisdd This is the docs PR we talked about!

docs: add docs on how to change the log encoder using kustomize

---

controllers/grafanacontactpoint_controller.go

fix: remove logging of override values

---

.github/workflows/release.yaml
Makefile
README.md
deploy/helm/grafana-operator/Chart.yaml
deploy/helm/grafana-operator/README.md
hugo/config.yaml

This fixes an issue with the configuration of the chart-releaser

chore: bump release v5.15.1

---

docs/docs/grafana.md

docs: fix number of installation modes

---

.github/labeler.yml
.github/release.yml
.github/workflows/labeler.yaml

Automatically label PRs and separate into sections for release notes

chore: automatically label PRs

---

api/v1beta1/grafanaalertrulegroup_types.go
api/v1beta1/grafanacontactpoint_types.go
api/v1beta1/grafanadashboard_types.go
api/v1beta1/grafanadatasource_types.go
api/v1beta1/grafanafolder_types.go
config/crd/bases/grafana.integreatly.org_grafanaalertrulegroups.yaml
config/crd/bases/grafana.integreatly.org_grafanacontactpoints.yaml
config/crd/bases/grafana.integreatly.org_grafanadashboards.yaml
config/crd/bases/grafana.integreatly.org_grafanadatasources.yaml
config/crd/bases/grafana.integreatly.org_grafanafolders.yaml
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanaalertrulegroups.yaml
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanacontactpoints.yaml
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanadashboards.yaml
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanadatasources.yaml
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanafolders.yaml
deploy/kustomize/base/crds.yaml
docs/docs/api.md

Addresses concerns around lacking documentation & restrictions for valid UIDs

docs: further specify uid requirements

---

tests/e2e/examples/crossnamespace/assertions.yaml
tests/e2e/examples/crossnamespace/resources.yaml

test: add test case for cross namespace isolation

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

This switches from labels to issue types

docs: update issue template

---

controllers/config/grafana_ini.go
docs/docs/grafana.md

feat: support top level configuration options

---

Makefile
config/manifests/bases/grafana-operator.clusterserviceversion.yaml

needs manuall generation as the operator-sdk command enters an infinite loop due to the recursive type

fix: add NotificationPolicyRoute to CSV base

---

controllers/contactpoint_controller.go

A `DELETE` always returns 202 whether contactpoint UID exists or not. the `GET` is entirely unnecessary.
You can confirm repeating:
`curl -v -u root:secret -X DELETE  localhost:3000/api/v1/provisioning/contact-points/any-uid`

chore(GrafanaContactPoint): simplify finalize stage

---

api/v1beta1/common.go
config/crd/bases/grafana.integreatly.org_grafanaalertrulegroups.yaml
config/crd/bases/grafana.integreatly.org_grafanacontactpoints.yaml
config/crd/bases/grafana.integreatly.org_grafanadashboards.yaml
config/crd/bases/grafana.integreatly.org_grafanadatasources.yaml
config/crd/bases/grafana.integreatly.org_grafanafolders.yaml
config/crd/bases/grafana.integreatly.org_grafanalibrarypanels.yaml
config/crd/bases/grafana.integreatly.org_grafanamutetimings.yaml
config/crd/bases/grafana.integreatly.org_grafananotificationpolicies.yaml
config/crd/bases/grafana.integreatly.org_grafananotificationtemplates.yaml
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanaalertrulegroups.yaml
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanacontactpoints.yaml
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanadashboards.yaml
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanadatasources.yaml
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanafolders.yaml
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanalibrarypanels.yaml
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanamutetimings.yaml
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafananotificationpolicies.yaml
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafananotificationtemplates.yaml
deploy/kustomize/base/crds.yaml
docs/docs/api.md

fix: use stricter validation for resyncPeriod

---

Makefile
README.md
deploy/helm/grafana-operator/Chart.yaml
deploy/helm/grafana-operator/README.md
deploy/kustomize/base/kustomization.yaml
hugo/config.yaml

Preps 5.17.1 to include fixes around reconciliation logic

chore: prep release 5.17.1

---

config/default/kustomization.yaml

see https://github.com/grafana/grafana-operator/issues/1925#issuecomment-2796696098

fix: remove service monitor from OLM deployment

---

.github/workflows/e2e.yaml
.github/workflows/hugo.yaml
.github/workflows/labeler.yaml
.github/workflows/pr-hugo.yaml
.github/workflows/pr-validation.yaml
.github/workflows/release.yaml
.github/workflows/stale.yml

This PR fixes potential security issues discovered using [zizmor](https://github.com/woodruffw/zizmor?tab=readme-ov-file).
It also pins _all_ actions used to a hash version to prevent any hostile takeovers of external dependencies.

ci: zizmor fixes

---

controllers/dashboard_controller.go
controllers/librarypanel_controller.go
docs/docs/dashboards.md

If a dashboard or a library panel reference their content from a ConfigMap I would expect that if I change the cm it will trigger a reconcile. However this seems currently not to be the case also not if caching is disabled.
The dashboard and libraryPanel controllers now are indexed by the configmaps they may point at. Changes the referenced configmaps will now trigger a reconciliation.
**Important** By default grafana-operator has caching enabled and only invokes reconciles for matching `managed-by` labels.
If one wants to actually use the configmap reconciles either of these will work:
* Use a custom shard selector (WATCH_LABEL_SELECTORS)
* ENFORCE_CACHE_LABELS=off
* Set the managed-by label to the configmaps (Although I don't recommend this)

fix: trigger reconcile if referenced configmap change

---

docs/docs/datasources.md

docs: document how to use PDC with the operator

---

.github/workflows/release.yaml

Allows for more fine grained access control and auditing

ci: move helm-release-app secret to vault

---

controllers/dashboard_controller.go
controllers/dashboard_controller_test.go

chore(dashboard): Remove code that deletes missing CRs from instances

---

deploy/helm/grafana-operator/templates/servicemonitor.yaml
docs/docs/installation/ops-and-monitoring.md

docs: document service monitor for integrated dashboard

---

.github/workflows/release.yaml

Last set of credentials remaining that were not in vault before

ci: move quay credentials to vault

---

api/v1beta1/grafana_types.go
api/v1beta1/grafananotificationtemplate_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/grafana.integreatly.org_grafanas.yaml
controllers/grafana_controller.go
controllers/notificationtemplate_controller.go
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanas.yaml
deploy/kustomize/base/crds.yaml
docs/docs/api.md

Adds `.status.notificationTemplates[]` to Grafana CRs showing instance with the resource applied.

feat(Grafana): reflect matching NotificationTemplates on Grafanas status

---

hugo/package-lock.json
hugo/package.json

Address reported security vulnerabilities in our documentation dependencies.
Both are dev dependencies and could be dismissed entirely, but updating feels "Correct"

chore(npm deps): Security vulnerabilities warnings on docs site

---

.github/workflows/release.yaml

- Sign SBOM
- Attest containers
Solves: https://github.com/grafana/grafana-operator/issues/2080

support attestation and sbom for multi platform

---

api/v1beta1/grafanaalertrulegroup_types.go
config/crd/bases/grafana.integreatly.org_grafanaalertrulegroups.yaml
controllers/alertrulegroup_controller_test.go
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanaalertrulegroups.yaml
deploy/kustomize/base/crds.yaml
docs/docs/api.md

fix(AlertRuleGroup): default `for` to 0s

---

api/v1beta1/grafanaalertrulegroup_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/grafana.integreatly.org_grafanaalertrulegroups.yaml
controllers/alertrulegroup_controller.go
deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanaalertrulegroups.yaml
deploy/kustomize/base/crds.yaml
docs/docs/api.md

Adds the `keepFiringFor` field to the alert rule group resource

feat: add keepFiringFor to alert rule group

---

Makefile
README.md
deploy/helm/grafana-operator/Chart.yaml
deploy/helm/grafana-operator/README.md
deploy/kustomize/base/kustomization.yaml
hugo/config.yaml

chore: release 5.19.0

---

.github/workflows/release.yaml

This should fix the release issues we encountered

prefix platform with v5

---

.github/workflows/release.yaml

Should fix the quay distribution step

chore: remove tty from docker run command
